// Generated by pssc <VERSION> -- do not edit.
// Root component: wb_dma_c

package wb_dma_c_pkg;
  import pssc_reg_pkg::*;

  // ----- Register value layouts (packed structs). -----
  typedef struct packed {
    bit [8:0] rsvd_23;   // [31:23] reserved
    bit int_chk_done;   // [22] sw=r hw=w reset=0x0 dropped: onread=rclr, intr, enable
    bit int_done;   // [21] sw=r hw=w reset=0x0 dropped: onread=rclr, intr, enable
    bit int_err;   // [20] sw=r hw=w reset=0x0 dropped: onread=rclr, intr, enable
    bit ine_chk_done;   // [19] sw=rw hw=r reset=0x0
    bit ine_done;   // [18] sw=rw hw=r reset=0x0
    bit ine_err;   // [17] sw=rw hw=r reset=0x0
    bit rest_en;   // [16] sw=rw hw=r reset=0x0
    bit [2:0] prio;   // [15:13] sw=rw hw=r reset=0x0
    bit err;   // [12] sw=r hw=w
    bit done;   // [11] sw=r hw=w
    bit busy;   // [10] sw=r hw=w
    bit stop;   // [9] sw=w hw=r reset=0x0
    bit sz_wb;   // [8] sw=rw hw=r reset=0x0
    bit use_ed;   // [7] sw=rw hw=r reset=0x0
    bit ars;   // [6] sw=rw hw=r reset=0x0
    bit mode;   // [5] sw=rw hw=r reset=0x0
    bit inc_src;   // [4] sw=rw hw=r reset=0x0
    bit inc_dst;   // [3] sw=rw hw=r reset=0x0
    bit src_sel;   // [2] sw=rw hw=r reset=0x0
    bit dst_sel;   // [1] sw=rw hw=r reset=0x0
    bit ch_en;   // [0] sw=rw hw=r reset=0x0
  } wb_dma_csr_s;
  // Field positions of wb_dma_csr_s, for write_field/read_field.
  localparam reg_field_t WB_DMA_CSR_ch_en        = '{mask:64'h0000000000000001, shift:0};
  localparam reg_field_t WB_DMA_CSR_dst_sel      = '{mask:64'h0000000000000002, shift:1};
  localparam reg_field_t WB_DMA_CSR_src_sel      = '{mask:64'h0000000000000004, shift:2};
  localparam reg_field_t WB_DMA_CSR_inc_dst      = '{mask:64'h0000000000000008, shift:3};
  localparam reg_field_t WB_DMA_CSR_inc_src      = '{mask:64'h0000000000000010, shift:4};
  localparam reg_field_t WB_DMA_CSR_mode         = '{mask:64'h0000000000000020, shift:5};
  localparam reg_field_t WB_DMA_CSR_ars          = '{mask:64'h0000000000000040, shift:6};
  localparam reg_field_t WB_DMA_CSR_use_ed       = '{mask:64'h0000000000000080, shift:7};
  localparam reg_field_t WB_DMA_CSR_sz_wb        = '{mask:64'h0000000000000100, shift:8};
  localparam reg_field_t WB_DMA_CSR_stop         = '{mask:64'h0000000000000200, shift:9};
  localparam reg_field_t WB_DMA_CSR_busy         = '{mask:64'h0000000000000400, shift:10};
  localparam reg_field_t WB_DMA_CSR_done         = '{mask:64'h0000000000000800, shift:11};
  localparam reg_field_t WB_DMA_CSR_err          = '{mask:64'h0000000000001000, shift:12};
  localparam reg_field_t WB_DMA_CSR_prio         = '{mask:64'h000000000000e000, shift:13};
  localparam reg_field_t WB_DMA_CSR_rest_en      = '{mask:64'h0000000000010000, shift:16};
  localparam reg_field_t WB_DMA_CSR_ine_err      = '{mask:64'h0000000000020000, shift:17};
  localparam reg_field_t WB_DMA_CSR_ine_done     = '{mask:64'h0000000000040000, shift:18};
  localparam reg_field_t WB_DMA_CSR_ine_chk_done = '{mask:64'h0000000000080000, shift:19};
  localparam reg_field_t WB_DMA_CSR_int_err      = '{mask:64'h0000000000100000, shift:20};
  localparam reg_field_t WB_DMA_CSR_int_done     = '{mask:64'h0000000000200000, shift:21};
  localparam reg_field_t WB_DMA_CSR_int_chk_done = '{mask:64'h0000000000400000, shift:22};
  localparam reg_field_t WB_DMA_CSR_rsvd_23      = '{mask:64'h00000000ff800000, shift:23};

  typedef struct packed {
    bit [6:0] rsvd_25;   // [31:25] reserved
    bit [8:0] chk_sz;   // [24:16] sw=rw hw=r
    bit [3:0] rsvd_12;   // [15:12] reserved
    bit [11:0] tot_sz;   // [11:0] sw=rw hw=r
  } wb_dma_sz_s;
  // Field positions of wb_dma_sz_s, for write_field/read_field.
  localparam reg_field_t WB_DMA_SZ_tot_sz  = '{mask:64'h0000000000000fff, shift:0};
  localparam reg_field_t WB_DMA_SZ_rsvd_12 = '{mask:64'h000000000000f000, shift:12};
  localparam reg_field_t WB_DMA_SZ_chk_sz  = '{mask:64'h0000000001ff0000, shift:16};
  localparam reg_field_t WB_DMA_SZ_rsvd_25 = '{mask:64'h00000000fe000000, shift:25};

  typedef struct packed {
    bit [31:0] addr;   // [31:0] sw=rw hw=r
  } wb_dma_addr_s;
  // Field positions of wb_dma_addr_s, for write_field/read_field.
  localparam reg_field_t WB_DMA_ADDR_addr = '{mask:64'h00000000ffffffff, shift:0};

  typedef struct packed {
    bit [31:0] mask;   // [31:0] sw=rw hw=r reset=0xfffffffc
  } wb_dma_amask_s;
  // Field positions of wb_dma_amask_s, for write_field/read_field.
  localparam reg_field_t WB_DMA_AMASK_mask = '{mask:64'h00000000ffffffff, shift:0};

  typedef struct packed {
    bit [31:0] ptr;   // [31:0] sw=rw hw=rw
  } wb_dma_descptr_s;
  // Field positions of wb_dma_descptr_s, for write_field/read_field.
  localparam reg_field_t WB_DMA_DESCPTR_ptr = '{mask:64'h00000000ffffffff, shift:0};

  typedef struct packed {
    bit en;   // [31] sw=rw hw=r reset=0x0
    bit [30:0] ptr;   // [30:0] sw=rw hw=r reset=0x0
  } wb_dma_swptr_s;
  // Field positions of wb_dma_swptr_s, for write_field/read_field.
  localparam reg_field_t WB_DMA_SWPTR_ptr = '{mask:64'h000000007fffffff, shift:0};
  localparam reg_field_t WB_DMA_SWPTR_en  = '{mask:64'h0000000080000000, shift:31};

  typedef struct packed {
    bit [30:0] rsvd_1;   // [31:1] reserved
    bit pause;   // [0] sw=rw hw=r reset=0x0
  } wb_dma_gcsr_s;
  // Field positions of wb_dma_gcsr_s, for write_field/read_field.
  localparam reg_field_t WB_DMA_GCSR_pause  = '{mask:64'h0000000000000001, shift:0};
  localparam reg_field_t WB_DMA_GCSR_rsvd_1 = '{mask:64'h00000000fffffffe, shift:1};

  typedef struct packed {
    bit rsvd_31;   // [31] reserved
    bit [30:0] ch;   // [30:0] sw=rw hw=r reset=0x0
  } wb_dma_intmsk_s;
  // Field positions of wb_dma_intmsk_s, for write_field/read_field.
  localparam reg_field_t WB_DMA_INTMSK_ch      = '{mask:64'h000000007fffffff, shift:0};
  localparam reg_field_t WB_DMA_INTMSK_rsvd_31 = '{mask:64'h0000000080000000, shift:31};

  typedef struct packed {
    bit rsvd_31;   // [31] reserved
    bit [30:0] ch;   // [30:0] sw=r hw=w reset=0x0
  } wb_dma_intsrc_s;
  // Field positions of wb_dma_intsrc_s, for write_field/read_field.
  localparam reg_field_t WB_DMA_INTSRC_ch      = '{mask:64'h000000007fffffff, shift:0};
  localparam reg_field_t WB_DMA_INTSRC_rsvd_31 = '{mask:64'h0000000080000000, shift:31};

  // ----- Register-group classes. -----
  class wb_dma_ch_regs_c;
    reg_c #(wb_dma_csr_s)        csr;
    reg_c #(wb_dma_sz_s)         sz;
    reg_c #(wb_dma_addr_s)       adr0;
    reg_c #(wb_dma_amask_s)      am0;
    reg_c #(wb_dma_addr_s)       adr1;
    reg_c #(wb_dma_amask_s)      am1;
    reg_c #(wb_dma_descptr_s)    desc;
    reg_c #(wb_dma_swptr_s)      swptr;

    function new(pss_mem_if bus, addr_handle_t base);
      csr = new(bus, base + 64'h0);
      sz = new(bus, base + 64'h4);
      adr0 = new(bus, base + 64'h8);
      am0 = new(bus, base + 64'hc);
      adr1 = new(bus, base + 64'h10);
      am1 = new(bus, base + 64'h14);
      desc = new(bus, base + 64'h18);
      swptr = new(bus, base + 64'h1c);
    endfunction
  endclass

  class wb_dma_regs_c;
    reg_c #(wb_dma_gcsr_s)       csr;
    reg_c #(wb_dma_intmsk_s)     int_msk_a;
    reg_c #(wb_dma_intmsk_s)     int_msk_b;
    reg_c #(wb_dma_intsrc_s, READONLY) int_src_a;
    reg_c #(wb_dma_intsrc_s, READONLY) int_src_b;
    wb_dma_ch_regs_c             bank[4];

    function new(pss_mem_if bus, addr_handle_t base);
      csr = new(bus, base + 64'h0);
      int_msk_a = new(bus, base + 64'h4);
      int_msk_b = new(bus, base + 64'h8);
      int_src_a = new(bus, base + 64'hc);
      int_src_b = new(bus, base + 64'h10);
      foreach (bank[i])
        bank[i] = new(bus, base + 64'h20 + i * 64'h20);
    endfunction
  endclass

  // ----- Data types used by the export API. -----
  typedef enum {WB_DMA_DONE = 0, WB_DMA_ERROR = 1, WB_DMA_PENDING = 2} wb_dma_status_e;
  typedef enum {WB_DMA_IF0 = 0, WB_DMA_IF1 = 1} wb_dma_if_e;
  typedef enum {WB_DMA_SOFTWARE = 0, WB_DMA_HW_HANDSHAKE = 1} wb_dma_mode_e;
  typedef enum {WB_DMA_INT_A = 0, WB_DMA_INT_B = 1} wb_dma_int_bank_e;

  typedef struct {
    bit present;
    bit ars;
    bit ed;
    bit cbuf;
  } wb_dma_ch_caps_s;

  typedef struct {
    bit [31:0] src;
    bit [31:0] dst;
    bit [31:0] src_mask;
    bit [31:0] dst_mask;
    bit [11:0] tot_sz;
    bit [8:0] chk_sz;
    wb_dma_if_e src_if;
    wb_dma_if_e dst_if;
    bit inc_src;
    bit inc_dst;
    wb_dma_mode_e mode;
    bit [2:0] prio;
    bit auto_restart;
    bit hw_restart_en;
    bit sz_wb;
    bit int_on_done;
    bit int_on_err;
    bit int_on_chunk;
  } wb_dma_ch_cfg_s;

  typedef struct packed {
    bit [10:0] reserved1;
    bit eol;
    bit inc_src;
    bit inc_dst;
    bit src_sel;
    bit dst_sel;
    bit [3:0] reserved0;
    bit [11:0] tot_sz;
  } wb_dma_desc_csr_s;

  typedef struct packed {
    bit [31:0] next;
    bit [31:0] adr1;
    bit [31:0] adr0;
    wb_dma_desc_csr_s csr;
  } wb_dma_desc_s;

  // ----- Programming API: wb_dma_ch_c -----
  /**
   * The per-channel MMIO operation model (§3).
   *
   * Every operation the processor initiates against ONE DMA channel lives here.
   * The engine-global operations live on :pss:comp:`wb_dma_c`, which owns an
   * array of these.
   *
   * **Why per-channel components rather than a `chan` parameter.** The completion
   * condition is a channel register, so making the channel an instance rather
   * than an index keeps every access in the operation code index-free
   * (``regs.csr.read()``), which is both clearer and safer than indexing a
   * register array with a runtime value. It also matches the review decision that
   * a waking thread reads its own channel's status register (§3.1.1). The cost is
   * that each channel binds its own top-level register group.
   *
   * **Two layers, and every target gets both.**
   *
   * ``core``
   *     ``configure_channel``, ``set_auto_restart``, ``set_software_pointer``,
   *     ``transfer_single_start``, ``transfer_list_start``,
   *     ``stop_channel_start``, ``check_completion``. Arm-and-return plus a
   *     single-read poll; nothing here ever waits. The low-level driver API.
   *
   * ``end-to-end``
   *     ``wait_completion``, ``transfer_single``, ``transfer_list``,
   *     ``stop_channel``. Each is a ``*_start()`` followed by
   *     ``repeat { probe_status; wait_hint }``.
   *
   * What varies between profiles is one function body -- ``wait_hint()``, which
   * either suspends on :pss:field:`wake` or spins with ``yield``. Nothing else
   * reads ``HAS_EVENT_WAIT`` except ``notify_irq()``, the event producer.
   *
   * The end-to-end layer adds no device knowledge, only the loop. That is what
   * makes the core trustworthy without a second regression: every SystemVerilog
   * run drives the core through the end-to-end wrappers.
   */
  interface class wb_dma_ch_c_if;

    /**
     * Block until the operation running on this channel reaches a terminal state.
     *
     * *§3.1.* Not an operation in its own right: it is the ONE place in this tree
     * that waits for a completion, and therefore the whole of what the end-to-end
     * operations add over their ``*_start()`` halves. Present on every profile --
     * these functions do not need a scheduler, they need a way to wait, and that
     * choice is made once, in ``wait_hint()``.
     *
     * Waiting is realised as ``repeat { probe_status; wait_hint }``, where
     * ``probe_status()`` is the same single CSR read ``check_completion()`` uses.
     * Nothing is edge-triggered: the condition is re-read from the device on every
     * iteration, waking threads test their own conditions, and a spurious wake is
     * harmless. That is what makes the loop correct whether ``wait_hint()``
     * suspends on an interrupt or merely spins -- the two differ in what a lap
     * costs, not in what the loop concludes. **The wake is a hint; CHn_CSR is the
     * event.**
     *
     * That sharing is the argument for the whole start/wait split. The
     * non-blocking core is not a second implementation to be kept in step with
     * this one -- it is the body of this one, hoisted. A SystemVerilog regression
     * that only ever calls ``transfer_single()`` still executes every register
     * access a firmware caller will make, in the same order, so the two paths
     * cannot drift. That is why there is no second regression for the firmware
     * profile.
     *
     * **The side-effect problem (§3.1.1).** ``probe_status()`` runs an unbounded
     * number of times and it consumes state: reading CHn_CSR clears ERR and the
     * three interrupt-source bits. It is safe because the value is captured by the
     * same read that observes it, the loop exits holding it, and AT MOST ONE
     * OPERATION PER CHANNEL AT A TIME makes the polling thread the sole consumer.
     * ``stop_channel()`` is the one deliberate exception.
     *
     * **The guard is released here** because an operation is over when its
     * completion has been reported, which is this return. Releasing here rather
     * than in each caller keeps the claim and the release one fact in two places
     * instead of one in three.
     *
     * A stale ``wake`` token costs one read, exactly, and only on the event-wait
     * profile: the loop probes BEFORE it ever waits, and ``wake``'s depth of 1
     * caps the leftover at one, so the worst case is probe, wait-immediate, probe,
     * wait-blocks. There is deliberately no drain step at entry -- it would cost
     * the same read it saves.
     *
     * .. warning::
     *    On the event-wait profile the routing prerequisite is load-bearing. A
     *    test that never called ``configure_interrupt_routing()`` raises no
     *    interrupt, so nothing calls ``notify_irq()``, so this blocks forever.
     *    Blind posting softens it -- any ONE routed channel's interrupt wakes
     *    every waiter -- so a partially routed test still makes progress and a
     *    test that routes nothing deadlocks. That is intended: a hang is a more
     *    honest result than a green test whose completion path was never real. If
     *    you are debugging a hang here, check INT_MSK_A/B before you look at the
     *    DMA. A polling profile has no such exposure, because ``wait_hint()``
     *    spins -- the routing requirement belongs to the wait primitive, not to
     *    this operation.
     */
    pure virtual task wait_completion(output wb_dma_status_e status);

    /**
     * Run one transfer to completion and report how it ended.
     *
     * *§3.2 group 1, end-to-end.* Completes when the channel's DONE (or ERR)
     * interrupt has been observed and the CHn_CSR read has returned the status and
     * cleared the source. Waits for channel DONE or ERR -- this is the core driver
     * FSM: submit, RUNNING, completion.
     *
     * The body is the two halves, named. All of the device knowledge -- what to
     * program, in what order, which write arms the channel -- is in
     * ``transfer_single_start()``; all of the waiting is in ``wait_completion()``.
     * This function contributes the composition and the return type.
     *
     * .. warning::
     *    Two callers' obligations this signature does not encode, both stated in
     *    full on ``transfer_single_start()``. With
     *    ``mode == WB_DMA_HW_HANDSHAKE`` this call cannot complete on its own:
     *    something must be calling ``request_chunk()`` on the matching
     *    ``wb_dma_hs_c`` concurrently (§2.2). With ``cfg.auto_restart`` this call
     *    is DELIBERATELY NON-TERMINATING: another thread must clear ARS or abort
     *    the channel. It is a blocking read on a stream that ends when someone
     *    closes it, so an ARS transfer must never be the only operation a scenario
     *    waits on.
     *
     * :param cfg: what to program before arming
     */
    pure virtual task transfer_single(output wb_dma_status_e status, input wb_dma_ch_cfg_s cfg);

    /**
     * Run a descriptor chain to completion and report how it ended.
     *
     * *§3.2 group 3, end-to-end.* Completes when a descriptor with EOL set has
     * been processed -- the engine stops, sets DONE in CHn_CSR, and raises the
     * channel interrupt. Waits for EOL DONE, plus optional intermediate wakes:
     * RUNNING has internal structure here, being per-descriptor progress inside
     * one outstanding request.
     *
     * The four-step arming procedure of §3.3 lives in ``transfer_list_start()``,
     * along with the note about which configuration a descriptor does NOT carry
     * and must therefore come from a prior ``configure_channel()``.
     *
     * Unlike ``transfer_single()`` this completion is unconditional: ARS is
     * documented as meaningless and ignored with external descriptors (§3.3). Two
     * end-to-end operations differing only in completion contract is why neither
     * subsumes the other -- and the difference is entirely in the arming half, not
     * in the wait, which is why both share one ``wait_completion()``.
     *
     * :param head: head of the descriptor chain, as returned when the list was
     *              built; must be reachable from interface 0
     */
    pure virtual task transfer_list(output wb_dma_status_e status, input addr_handle_t head);

    /**
     * Abort whatever is running on this channel and wait for the abort to land.
     *
     * *§3.2 group 1, end-to-end.* Completes when STOP has been written, the
     * channel has aborted, ERR is set, and the error interrupt (if enabled) has
     * been raised. Waits for channel ERR -- an abort path that completes the SAME
     * outstanding request from a second entry point.
     *
     * An abort is reported as an ERROR, not as a clean stop. Note the consequence
     * for the scenario layer: the aborted ``transfer_single()`` also returns, with
     * ``WB_DMA_ERROR``. Two end-to-end operations complete off one event.
     *
     * **It has its own loop rather than calling** ``wait_completion()``. By
     * definition it aborts a transfer that is still running, so it violates the
     * one-operation-per-channel rule that makes the polling read safe.
     * ``stop_channel_start()`` claims no token, so this function holds none -- and
     * ``wait_completion()`` ends by RELEASING one, which would take the aborted
     * transfer's. Hence the loop below: identical to ``wait_completion()``'s
     * except that it does not touch the guard. The duplication is five lines and
     * it is the honest shape; a "do not release" flag would hide the one place in
     * this model where two operations legitimately share a channel.
     *
     * See ``stop_channel_start()`` for what that sharing costs -- which read
     * consumes the ERR is not determined by this model -- and for open item §6.5.
     */
    pure virtual task stop_channel(output wb_dma_status_e status);

    /**
     * Poll whether the operation running on this channel has finished.
     *
     * The non-blocking half of every end-to-end operation, present on every
     * profile -- this is what firmware polls. Completes immediately: one
     * register read, one answer. It never suspends and never spins; the caller
     * supplies the loop.
     *
     * **The contract is narrower than it looks.**
     *
     * 1. An operation must have been STARTED on this channel, by one of
     *    ``transfer_single_start()`` or ``transfer_list_start()``.
     * 2. Once this returns anything other than ``WB_DMA_PENDING``, the operation
     *    is over. DO NOT CALL AGAIN until the next ``*_start()``.
     *
     * Both rules exist because reading CHn_CSR is destructive: ERR and the three
     * interrupt-source bits are read-to-clear, so this call CONSUMES the
     * completion it reports. A second call after DONE does not re-report DONE --
     * it reads a channel whose status has already been taken and answers PENDING
     * forever. That failure is invisible from the device side, because a stale
     * read and a live one look identical.
     *
     * **How the guard works.** :pss:field:`inflight` holds one token for the
     * life of an operation. This takes it, reads, and puts it back only if the
     * answer was PENDING:
     *
     * ``try_get`` fails
     *     Rule 1 or rule 2 has been broken. Report it.
     * ``WB_DMA_PENDING``
     *     Restore the token; the operation continues.
     * ``WB_DMA_DONE`` / ``WB_DMA_ERROR``
     *     Leave it taken; the operation is over.
     *
     * Take-and-restore rather than a peek because ``channel_c`` has no peek
     * (§21.9.1 offers get/put/try_get/try_put and nothing else). It is safe
     * under the one-operation-per-channel rule that already governs this model:
     * the polling thread is the only one entitled to that token.
     *
     * .. note::
     *    "Report it" is weaker than it should be. This stdlib has no runtime
     *    ``error()``, so a violation is a message at ``NONE`` verbosity -- the
     *    loudest thing available, and still only a message. A runtime that wants
     *    it fatal should bind the model's message sink to one; the text is
     *    deliberately distinctive so it can be matched. Returning
     *    ``WB_DMA_ERROR`` was considered and rejected: it would make a
     *    PROGRAMMING error indistinguishable from a DEVICE error. It answers
     *    PENDING instead, because the state needed for an honest answer was
     *    consumed by whoever broke the rule.
     */
    pure virtual task check_completion(output wb_dma_status_e status);

    /**
     * Program a channel's registers from a config, without arming it.
     *
     * *§3.2 group 1, configuration.* Completes when CHn_SZ / A0 / AM0 / A1 /
     * AM1 and the RW bits of CHn_CSR reflect ``cfg``; the channel is NOT
     * enabled. Waits for nothing -- straight-line stores, no driver state,
     * callable from any context including with a lock held.
     *
     * Kept alongside ``transfer_single()``, which takes the same config and
     * subsumes this for the common case, for exactly one reason:
     * ``transfer_list()`` needs CHK_SZ programmed BEFORE the chain is armed
     * (§3.3), and a descriptor carries no chunk size.
     *
     * The CSR is written whole rather than read-modify-written, because at this
     * point nothing is running on the channel and a read would consume the
     * read-to-clear status bits for no reason.
     *
     * :param cfg: what to program; capability-gated fields are skipped when the
     *             channel was built without the capability
     */
    pure virtual task configure_channel(input wb_dma_ch_cfg_s cfg);

    /**
     * Decode one read of CHn_CSR into a status. The unguarded primitive both
     * layers are built from.
     *
     * Not an operation, and not the API: no in-progress guard, no blocking, no
     * loop. It exists because the guard and the decode are separable concerns
     * and exactly one caller needs the decode without the guard.
     *
     * ``check_completion()``
     *     Guard plus this. The non-blocking API; firmware calls it.
     *
     * ``wait_completion()``
     *     This, in a loop, under a wake. The guard would be wrong inside a loop
     *     -- it is claimed once by the ``*_start()`` and released once by the
     *     operation that started it, not taken and put back on every poll.
     *
     * ``stop_channel()``
     *     This, in a loop, holding no token. Stop is the documented exemption
     *     from the one-operation-per-channel rule, so it has none to release.
     *
     * ERR is tested before DONE because the two are not exclusive: an aborted
     * transfer can retire with both set, and a stop that lands on an
     * already-completed channel certainly does. Reporting ERROR is the
     * conservative reading -- a scenario that expected DONE learns something
     * went wrong, where the reverse order would hide it.
     *
     * .. warning::
     *    Callers outside this component should use ``check_completion()``. PSS
     *    has no visibility control, so this cannot be enforced -- but reaching
     *    past the guard opts out of the only detector for the read-to-clear
     *    hazard, and the read is a side effect every time.
     */
    pure virtual task probe_status(output wb_dma_status_e status);

    /**
     * Set or clear the channel's auto-restart bit.
     *
     * *§3.2 group 1, configuration.* Completes when ARS has been updated; waits
     * for nothing.
     *
     * Distinct from ``configure_channel()`` because clearing ARS mid-flight is
     * the documented way to terminate an auto-restarting channel (§3.2.1),
     * invoked on its own against a live channel from a parallel scenario branch.
     * Rewriting the whole register bank to do that would be wrong.
     *
     * It is therefore the TERMINATING EVENT for an auto-restarting
     * ``transfer_single()``: once ARS is clear, the in-flight iteration retires
     * and DONE asserts.
     *
     * .. warning::
     *    A read-modify-write against a live channel, so it shares the hazard
     *    described on ``stop_channel_start()``: the read consumes any pending
     *    read-to-clear status. Enabling ARS before arming is unaffected;
     *    disabling it mid-flight is the exposed case.
     *
     * :param enable: 1 to auto-restart on completion, 0 to stop after the
     *                current iteration
     */
    pure virtual task set_auto_restart(input bit enable);

    /**
     * Publish how far a software reader has drained a FIFO in memory.
     *
     * *§3.2 group 1, configuration.* Completes when CHn_SWPTR has been updated
     * -- a channel stalled on the old pointer may resume as a side effect.
     * Waits for nothing.
     *
     * The consumer side of a FIFO in memory (§3.5): the DMA stalls rather than
     * overrun the software reader, and publishing a new pointer un-stalls it. So
     * this is invoked repeatedly during a live transfer, always concurrent with
     * a ``transfer_single()``.
     *
     * Note what that implies about scope: the FIFO's DATA is read on the test
     * writer's own memory path. This operation only publishes how far that
     * reader has got.
     *
     * Requires ``caps.cbuf``, and only means anything with a circular-buffer
     * address mask programmed on the same channel.
     *
     * :param ptr:    the new software pointer
     * :param enable: whether the pointer is honoured at all
     */
    pure virtual task set_software_pointer(input bit [30:0] ptr, input bit enable);

    /**
     * Write STOP to abort whatever is running on this channel, and return.
     *
     * *§3.2 group 1.* The non-blocking half of ``stop_channel()``, present on
     * every profile. Completes when STOP has been written -- the abort itself
     * has not necessarily happened yet. Waits for nothing.
     *
     * An abort is reported as an ERROR, not as a clean stop: the device sets ERR
     * on a STOP write (§3.2.2). That is carried into the contract verbatim.
     *
     * **This claims no** :pss:field:`inflight` **token, deliberately.** By
     * definition it aborts a transfer that is still running, so the channel it
     * targets is already holding one. Claiming would report the one case the
     * model explicitly permits as a violation. Stop is the documented exemption
     * from the one-operation-per-channel rule, and the exemption is now visible
     * in the code rather than only in a comment.
     *
     * **Two consequences a firmware caller must know.**
     *
     * The ``write_field`` below IS a read-modify-write: the LRM defines the
     * field-wise write as one (§21.14.1), so the CHn_CSR read is there even
     * though the call no longer spells it out, and it still clears ERR and the
     * interrupt sources. That read happens BEFORE STOP is written, so it can
     * only consume status that was already there -- the abort's own ERR is set
     * afterwards and is still seen by the aborted transfer's poll. What it can
     * lose is a completion that landed in the instant before the abort.
     *
     * Who reports the abort is NOT determined by this model. The aborted
     * transfer polls the same CSR, and whichever read lands first consumes the
     * ERR. On the non-blocking profile the loser's ``check_completion()``
     * answers PENDING forever -- a firmware hang rather than an action that does
     * not retire.
     *
     * There is no ``check_completion()`` pairing for stop: it holds no token, so
     * it has nothing to poll with. A caller aborts, then keeps polling the
     * TRANSFER it aborted, which is the operation that owns the completion.
     *
     * .. note::
     *    Open question (§6.5): is write-1-to-STOP acknowledged before or after
     *    the current WISHBONE cycle retires? That decides whether an abort can
     *    be considered delivered on return, which matters post-silicon.
     */
    pure virtual task stop_channel_start();

    /**
     * Point a channel at a descriptor list and arm it, returning with the chain
     * running.
     *
     * *§3.2 group 3.* The non-blocking half of ``transfer_list()``, present on
     * every profile. Completes when the channel points at the list, external
     * descriptors are enabled, and the channel is armed. Waits for nothing.
     *
     * §3.3's four-step arming procedure IS this function's body, except step 2
     * (chunk size), which must come from a prior ``configure_channel()`` because
     * it outlives any single descriptor. A descriptor carries only src, dst,
     * tot_sz, the increment flags, the interface selects and EOL; mode,
     * priority, ARS, the address masks and CHK_SZ stay whatever the channel
     * registers hold.
     *
     * Unlike ``transfer_single_start()``, this one always has a completion: ARS
     * is documented as meaningless and ignored with external descriptors (§3.3),
     * so ``check_completion()`` is guaranteed to answer DONE or ERROR
     * eventually. Two end-to-end operations differing only in completion
     * contract is why neither subsumes the other -- and the difference was never
     * in the wait.
     *
     * Requires ``caps.ed``. Unlike the other capability-gated operations this
     * reports rather than returning quietly, because it has a completion
     * contract: a silent return would leave the caller waiting for a chain that
     * was never armed.
     *
     * :param head: head of the descriptor chain; must be reachable from
     *              interface 0
     */
    pure virtual task transfer_list_start(input addr_handle_t head);

    /**
     * Program a channel and arm it, returning with the transfer running.
     *
     * *§3.2 group 1.* The non-blocking half of ``transfer_single()``, present on
     * every profile. Completes when the channel is programmed and armed -- NOT
     * when the transfer has moved anything. Waits for nothing.
     *
     * Program, arm, return. The caller then polls ``check_completion()`` until
     * it answers something other than PENDING, or calls ``transfer_single()``,
     * which is exactly this plus the wait. All of the device knowledge is here;
     * the end-to-end layer adds only the loop. That is why a SystemVerilog
     * regression that never calls this directly still tests it.
     *
     * **Two callers' obligations this signature does not encode.**
     *
     * ``mode == WB_DMA_HW_HANDSHAKE``: the transfer cannot complete on its own.
     * Something must be calling ``request_chunk()`` on the matching
     * ``wb_dma_hs_c`` concurrently (§2.2). Splitting arm from wait does not help
     * here -- the missing thing is a second initiator, not a second thread.
     *
     * ``cfg.auto_restart``: the transfer has NO completion event. CSR bit 11
     * sets DONE only once ARS is clear, so nothing this function starts will
     * ever make ``check_completion()`` answer DONE. Someone must clear ARS
     * (``set_auto_restart(0)``) or abort the channel (``stop_channel_start()``).
     * In the end-to-end layer that is a thread that never returns; here it is a
     * loop that never exits, which is a firmware hang rather than a stalled PSS
     * action. Same defect, less visible.
     *
     * Claims :pss:field:`inflight` FIRST, before touching a register, so a start
     * that would be the second on a live channel is reported without having
     * corrupted the configuration of the first.
     *
     * :param cfg: what to program before arming
     */
    pure virtual task transfer_single_start(input wb_dma_ch_cfg_s cfg);

    /**
     * Wait until the device may have progressed.
     *
     * The wait PRIMITIVE: the one function in this model whose body differs
     * between execution targets, and the only thing
     * ``wb_dma_cfg_pkg::HAS_EVENT_WAIT`` gates.
     *
     * **Contract: return when the device MAY have progressed.** Not "when it
     * has" -- this reports nothing and decides nothing. Every caller is a loop
     * that re-reads CHn_CSR afterwards and tests its own condition, so a
     * spurious return costs one register read and a late return costs latency.
     * Neither is a defect.
     *
     * This is the seam that lets the OPERATION SURFACE be profile-independent.
     * The two ways to wait have different requirements:
     *
     * ``wake.get()``
     *     Suspend until someone posts. Needs an event source (``notify_irq()``,
     *     hence configured interrupt routing) and a runtime that can suspend a
     *     caller. Costs nothing while waiting.
     *
     * ``yield``
     *     Spin. Needs NOTHING -- every target can spin, including a bare-metal
     *     single-threaded one. Costs the bus a read per iteration and, on a
     *     threaded target, whatever the scheduler charges.
     *
     * Only the first is a capability, so that is what the flag asks about and
     * this is where the answer is consumed. Every operation above it is written
     * once and compiles on both. See ``docs/op-model-c-embedded-design.md``
     * §5.4 and ``docs/target-cfg-contract.md``.
     *
     * .. warning::
     *    ``yield`` is a hint to the SCHEDULER, not to the device, and a backend
     *    spends it however its target charges for waiting. It must NOT be
     *    implemented as a wait on this device's interrupt: that would
     *    reintroduce the routing prerequisite this branch exists to avoid, and
     *    would deadlock the one caller that has no interrupt to wait for. The
     *    contract is stated in full in ``docs/op-model-export-design.md`` §4.4.
     */
    pure virtual task wait_hint();
  endclass

  // ----- Programming API: wb_dma_c -----
  /**
   * The MMIO operation model for the WISHBONE DMA/Bridge core (§3,
   * ``dma_mmio_c`` in the operation-model document).
   *
   * This component holds the engine-GLOBAL operations -- PAUSE, interrupt
   * routing, descriptor authoring. Everything per-channel is on
   * :pss:comp:`wb_dma_ch_c`, an array of which it owns.
   *
   * Scope (§1): everything the processor reaches by load/store. The per-channel
   * hardware handshake's participant is the PERIPHERAL, so its model sits with
   * the environment (``tests/pss/wb_dma_hs_c.pss``). The WISHBONE masters are
   * device-driven and out of scope; so is descriptor FETCHING, though descriptor
   * AUTHORING is here, because the processor initiates it.
   *
   * Deliberately absent:
   *
   * * **bulk buffer access** -- the test writer already has a path to memory
   *   (``read32``/``write32``); filling a source region and checking a
   *   destination region are not operations of this model.
   * * **bus-error injection** -- it belongs to whatever component can drive
   *   ``err_i``. A DMA-error-reaction test is a composition of two operation
   *   models, not a wider version of this one (§5.1).
   * * **bridge_access** -- the pass-through path is reachable only with a target
   *   on the far interface; omitted by review decision.
   */
  interface class wb_dma_c_if;

    /**
     * Route a set of channels to one of the two aggregate interrupt outputs.
     *
     * *§3.2 group 2, configuration.* Completes when INT_MSK_A/B has been
     * updated; waits for nothing.
     *
     * The two banks are independent aggregate outputs, and a channel may be
     * routed to both. ``channel_mask`` stays a bit vector rather than becoming
     * a channel list because it genuinely is one: bit N routes channel N.
     *
     * **A hard prerequisite for every end-to-end operation, enforced by
     * deadlock** on the event-wait profile. Completion IS the interrupt, so a
     * test that routes nothing raises no interrupt, nothing calls
     * ``notify_irq()``, and the first wait blocks forever. Routing at least one
     * channel in a bank keeps the whole test alive, because ``notify_irq()``
     * posts to every channel blind. That is intended: a hang is a more honest
     * result than a green test whose completion path was never exercised.
     *
     * :param bank:         which aggregate output to program
     * :param channel_mask: bit N routes channel N
     */
    pure virtual task configure_interrupt_routing(input wb_dma_int_bank_e bank, input bit [30:0] channel_mask);

    pure virtual task notify_irq();

    /**
     * Pause or un-pause the whole engine, and wait until it has taken effect.
     *
     * *§3.2 group 2, configuration.* Global, not per-channel.
     *
     * Completes when a readback of ``CSR.PAUSE`` matches the requested value.
     * The engine only pauses after the CURRENT transfer completes, so the write
     * and the state change are NOT simultaneous -- which is the entire reason
     * this is an operation rather than a register write, and the clearest small
     * illustration of the blocking rule: the operation is not done when the
     * store retires.
     *
     * It waits for that readback, and is the one wait in this model with no
     * interrupt behind it -- in a real driver, a retry or timer loop rather than
     * an ISR wake. The global CSR is not read-to-clear, so unlike the channel
     * CSR this poll is genuinely side-effect-free and may run any number of
     * times.
     *
     * :param pause: 1 to pause, 0 to resume
     */
    pure virtual task pause_engine(input bit pause);

    /**
     * Read back how much of a descriptor's transfer actually moved.
     *
     * *§3.2 group 3, configuration.* Completes when DESC_CSR has been loaded
     * back from memory and decoded; waits for nothing.
     *
     * A device-specific decode, not a memory service -- the same rationale that
     * keeps ``write_descriptor()`` in this model. Only meaningful when SZ_WB is
     * set in the channel CSR and the descriptor was cut short by
     * ``skip_to_next_descriptor()``. This is how software learns how much of a
     * variable-length payload actually moved, which is the whole point of §3.9.
     *
     * .. note::
     *    Open question (§6.1): §3.9 says the remaining BYTES are written back,
     *    into a field Table 1 defines as a 12-bit WORD count. One of the two is
     *    wrong. This returns the raw field and lets the caller decide.
     *
     * :param desc_ptr: the descriptor whose control word is read back
     */
    pure virtual task read_descriptor_residual(output bit [11:0] status, input addr_handle_t desc_ptr);

    /**
     * Write one external descriptor into memory and link it to its predecessor.
     *
     * *§3.2 group 3, configuration.* Completes when the descriptor is in memory
     * at ``at``, terminated (DESC_NEXT zero), and ``prev`` -- if there is one --
     * points at it. Waits for nothing. Returns a handle to the slot immediately
     * after ``at``, i.e. the natural place for the next descriptor, so a caller
     * can build a list in place one link at a time.
     *
     * This is DEVICE KNOWLEDGE written through a memory path, not a path to
     * memory: the next-pointer linkage and the EOL rule are the operation, the
     * layout is declared by :pss:struct:`wb_dma_desc_s`, and ``write32`` is
     * merely how it lands. That is what makes it an operation where a generic
     * ``write_buffer()`` would not be.
     *
     * ``at`` must be reachable from interface 0: descriptors are fetched from
     * IF0 regardless of which interface the DATA moves on (§3.3).
     *
     * :param at:   where this descriptor goes
     * :param prev: the descriptor to link from; null/zero means "head of list"
     * :param desc: the descriptor contents; the caller's copy is not modified
     */
    pure virtual task write_descriptor(output addr_handle_t status, input addr_handle_t at, input addr_handle_t prev, input wb_dma_desc_s desc);

    pure virtual function wb_dma_ch_c_if ch(int index);
    pure virtual function int ch_size();
  endclass

  // ----- Import API (root: wb_dma_c) -----
  interface class wb_dma_c_import_if extends pss_mem_if;
    // Blocking: return when the device may have progressed.
    // MUST NOT wait on an interrupt alone -- see the yield contract.
    pure virtual task yield_();
  endclass

  // ----- Implementation: wb_dma_ch_c -----
  /**
   * The per-channel MMIO operation model (§3).
   *
   * Every operation the processor initiates against ONE DMA channel lives here.
   * The engine-global operations live on :pss:comp:`wb_dma_c`, which owns an
   * array of these.
   *
   * **Why per-channel components rather than a `chan` parameter.** The completion
   * condition is a channel register, so making the channel an instance rather
   * than an index keeps every access in the operation code index-free
   * (``regs.csr.read()``), which is both clearer and safer than indexing a
   * register array with a runtime value. It also matches the review decision that
   * a waking thread reads its own channel's status register (§3.1.1). The cost is
   * that each channel binds its own top-level register group.
   *
   * **Two layers, and every target gets both.**
   *
   * ``core``
   *     ``configure_channel``, ``set_auto_restart``, ``set_software_pointer``,
   *     ``transfer_single_start``, ``transfer_list_start``,
   *     ``stop_channel_start``, ``check_completion``. Arm-and-return plus a
   *     single-read poll; nothing here ever waits. The low-level driver API.
   *
   * ``end-to-end``
   *     ``wait_completion``, ``transfer_single``, ``transfer_list``,
   *     ``stop_channel``. Each is a ``*_start()`` followed by
   *     ``repeat { probe_status; wait_hint }``.
   *
   * What varies between profiles is one function body -- ``wait_hint()``, which
   * either suspends on :pss:field:`wake` or spins with ``yield``. Nothing else
   * reads ``HAS_EVENT_WAIT`` except ``notify_irq()``, the event producer.
   *
   * The end-to-end layer adds no device knowledge, only the loop. That is what
   * makes the core trustworthy without a second regression: every SystemVerilog
   * run drives the core through the end-to-end wrappers.
   */
  class wb_dma_ch_c implements wb_dma_ch_c_if;
    protected wb_dma_c_import_if m_imp;
    protected wb_dma_ch_regs_c m_regs;
    // Which channel this is, in ``dma_req_i``/``dma_ack_o`` and INT_SRC bit
    // numbering.
    //
    // Integrator-facing identity: no operation here reads it, because each
    // channel reaches its own registers through :pss:field:`regs` rather than
    // by index. It is what an environment correlates a channel against.
    protected int m_chan;
    // Build-time capabilities.
    //
    // An absent capability makes the corresponding control bit silently ignored
    // by hardware, so operations consult this rather than assuming everything
    // is present.
    protected wb_dma_ch_caps_s m_caps;
    channel_c #(bit, 1) inflight;
    channel_c #(bit, 1) wake;

    function new(wb_dma_c_import_if bus, int id, addr_handle_t bank);
      m_imp = bus;
      inflight = new();
      wake = new();
      m_caps.present = 1;
      m_caps.ars = 1;
      m_caps.ed = 1;
      m_caps.cbuf = 1;
      m_chan = id;
      m_regs = new(m_imp, bank);
    endfunction

    /**
     * Block until the operation running on this channel reaches a terminal state.
     *
     * *§3.1.* Not an operation in its own right: it is the ONE place in this tree
     * that waits for a completion, and therefore the whole of what the end-to-end
     * operations add over their ``*_start()`` halves. Present on every profile --
     * these functions do not need a scheduler, they need a way to wait, and that
     * choice is made once, in ``wait_hint()``.
     *
     * Waiting is realised as ``repeat { probe_status; wait_hint }``, where
     * ``probe_status()`` is the same single CSR read ``check_completion()`` uses.
     * Nothing is edge-triggered: the condition is re-read from the device on every
     * iteration, waking threads test their own conditions, and a spurious wake is
     * harmless. That is what makes the loop correct whether ``wait_hint()``
     * suspends on an interrupt or merely spins -- the two differ in what a lap
     * costs, not in what the loop concludes. **The wake is a hint; CHn_CSR is the
     * event.**
     *
     * That sharing is the argument for the whole start/wait split. The
     * non-blocking core is not a second implementation to be kept in step with
     * this one -- it is the body of this one, hoisted. A SystemVerilog regression
     * that only ever calls ``transfer_single()`` still executes every register
     * access a firmware caller will make, in the same order, so the two paths
     * cannot drift. That is why there is no second regression for the firmware
     * profile.
     *
     * **The side-effect problem (§3.1.1).** ``probe_status()`` runs an unbounded
     * number of times and it consumes state: reading CHn_CSR clears ERR and the
     * three interrupt-source bits. It is safe because the value is captured by the
     * same read that observes it, the loop exits holding it, and AT MOST ONE
     * OPERATION PER CHANNEL AT A TIME makes the polling thread the sole consumer.
     * ``stop_channel()`` is the one deliberate exception.
     *
     * **The guard is released here** because an operation is over when its
     * completion has been reported, which is this return. Releasing here rather
     * than in each caller keeps the claim and the release one fact in two places
     * instead of one in three.
     *
     * A stale ``wake`` token costs one read, exactly, and only on the event-wait
     * profile: the loop probes BEFORE it ever waits, and ``wake``'s depth of 1
     * caps the leftover at one, so the worst case is probe, wait-immediate, probe,
     * wait-blocks. There is deliberately no drain step at entry -- it would cost
     * the same read it saves.
     *
     * .. warning::
     *    On the event-wait profile the routing prerequisite is load-bearing. A
     *    test that never called ``configure_interrupt_routing()`` raises no
     *    interrupt, so nothing calls ``notify_irq()``, so this blocks forever.
     *    Blind posting softens it -- any ONE routed channel's interrupt wakes
     *    every waiter -- so a partially routed test still makes progress and a
     *    test that routes nothing deadlocks. That is intended: a hang is a more
     *    honest result than a green test whose completion path was never real. If
     *    you are debugging a hang here, check INT_MSK_A/B before you look at the
     *    DMA. A polling profile has no such exposure, because ``wait_hint()``
     *    spins -- the routing requirement belongs to the wait primitive, not to
     *    this operation.
     */
    virtual task wait_completion(output wb_dma_status_e status);
      bit tok;
      forever begin
        probe_status(status);
        if (status != 2) begin
          break;
        end
        wait_hint();
      end
      // The operation is over: drop the claim its *_start() took. The result is
      // discarded because there is one case where the token is legitimately
      // absent -- a *_start() that reported a double-start and returned without
      // arming, whose caller is already in error.
      void'(inflight.try_get(tok));
      status = status;
      return;
    endtask

    /**
     * Run one transfer to completion and report how it ended.
     *
     * *§3.2 group 1, end-to-end.* Completes when the channel's DONE (or ERR)
     * interrupt has been observed and the CHn_CSR read has returned the status and
     * cleared the source. Waits for channel DONE or ERR -- this is the core driver
     * FSM: submit, RUNNING, completion.
     *
     * The body is the two halves, named. All of the device knowledge -- what to
     * program, in what order, which write arms the channel -- is in
     * ``transfer_single_start()``; all of the waiting is in ``wait_completion()``.
     * This function contributes the composition and the return type.
     *
     * .. warning::
     *    Two callers' obligations this signature does not encode, both stated in
     *    full on ``transfer_single_start()``. With
     *    ``mode == WB_DMA_HW_HANDSHAKE`` this call cannot complete on its own:
     *    something must be calling ``request_chunk()`` on the matching
     *    ``wb_dma_hs_c`` concurrently (§2.2). With ``cfg.auto_restart`` this call
     *    is DELIBERATELY NON-TERMINATING: another thread must clear ARS or abort
     *    the channel. It is a blocking read on a stream that ends when someone
     *    closes it, so an ARS transfer must never be the only operation a scenario
     *    waits on.
     *
     * :param cfg: what to program before arming
     */
    virtual task transfer_single(output wb_dma_status_e status, input wb_dma_ch_cfg_s cfg);
      transfer_single_start(cfg);
      wait_completion(status);
      return;
    endtask

    /**
     * Run a descriptor chain to completion and report how it ended.
     *
     * *§3.2 group 3, end-to-end.* Completes when a descriptor with EOL set has
     * been processed -- the engine stops, sets DONE in CHn_CSR, and raises the
     * channel interrupt. Waits for EOL DONE, plus optional intermediate wakes:
     * RUNNING has internal structure here, being per-descriptor progress inside
     * one outstanding request.
     *
     * The four-step arming procedure of §3.3 lives in ``transfer_list_start()``,
     * along with the note about which configuration a descriptor does NOT carry
     * and must therefore come from a prior ``configure_channel()``.
     *
     * Unlike ``transfer_single()`` this completion is unconditional: ARS is
     * documented as meaningless and ignored with external descriptors (§3.3). Two
     * end-to-end operations differing only in completion contract is why neither
     * subsumes the other -- and the difference is entirely in the arming half, not
     * in the wait, which is why both share one ``wait_completion()``.
     *
     * :param head: head of the descriptor chain, as returned when the list was
     *              built; must be reachable from interface 0
     */
    virtual task transfer_list(output wb_dma_status_e status, input addr_handle_t head);
      transfer_list_start(head);
      wait_completion(status);
      return;
    endtask

    /**
     * Abort whatever is running on this channel and wait for the abort to land.
     *
     * *§3.2 group 1, end-to-end.* Completes when STOP has been written, the
     * channel has aborted, ERR is set, and the error interrupt (if enabled) has
     * been raised. Waits for channel ERR -- an abort path that completes the SAME
     * outstanding request from a second entry point.
     *
     * An abort is reported as an ERROR, not as a clean stop. Note the consequence
     * for the scenario layer: the aborted ``transfer_single()`` also returns, with
     * ``WB_DMA_ERROR``. Two end-to-end operations complete off one event.
     *
     * **It has its own loop rather than calling** ``wait_completion()``. By
     * definition it aborts a transfer that is still running, so it violates the
     * one-operation-per-channel rule that makes the polling read safe.
     * ``stop_channel_start()`` claims no token, so this function holds none -- and
     * ``wait_completion()`` ends by RELEASING one, which would take the aborted
     * transfer's. Hence the loop below: identical to ``wait_completion()``'s
     * except that it does not touch the guard. The duplication is five lines and
     * it is the honest shape; a "do not release" flag would hide the one place in
     * this model where two operations legitimately share a channel.
     *
     * See ``stop_channel_start()`` for what that sharing costs -- which read
     * consumes the ERR is not determined by this model -- and for open item §6.5.
     */
    virtual task stop_channel(output wb_dma_status_e status);
      stop_channel_start();
      // wait_completion()'s loop, minus the guard release. See above.
      forever begin
        probe_status(status);
        if (status != 2) begin
          break;
        end
        wait_hint();
      end
      status = status;
      return;
    endtask

    /**
     * Poll whether the operation running on this channel has finished.
     *
     * The non-blocking half of every end-to-end operation, present on every
     * profile -- this is what firmware polls. Completes immediately: one
     * register read, one answer. It never suspends and never spins; the caller
     * supplies the loop.
     *
     * **The contract is narrower than it looks.**
     *
     * 1. An operation must have been STARTED on this channel, by one of
     *    ``transfer_single_start()`` or ``transfer_list_start()``.
     * 2. Once this returns anything other than ``WB_DMA_PENDING``, the operation
     *    is over. DO NOT CALL AGAIN until the next ``*_start()``.
     *
     * Both rules exist because reading CHn_CSR is destructive: ERR and the three
     * interrupt-source bits are read-to-clear, so this call CONSUMES the
     * completion it reports. A second call after DONE does not re-report DONE --
     * it reads a channel whose status has already been taken and answers PENDING
     * forever. That failure is invisible from the device side, because a stale
     * read and a live one look identical.
     *
     * **How the guard works.** :pss:field:`inflight` holds one token for the
     * life of an operation. This takes it, reads, and puts it back only if the
     * answer was PENDING:
     *
     * ``try_get`` fails
     *     Rule 1 or rule 2 has been broken. Report it.
     * ``WB_DMA_PENDING``
     *     Restore the token; the operation continues.
     * ``WB_DMA_DONE`` / ``WB_DMA_ERROR``
     *     Leave it taken; the operation is over.
     *
     * Take-and-restore rather than a peek because ``channel_c`` has no peek
     * (§21.9.1 offers get/put/try_get/try_put and nothing else). It is safe
     * under the one-operation-per-channel rule that already governs this model:
     * the polling thread is the only one entitled to that token.
     *
     * .. note::
     *    "Report it" is weaker than it should be. This stdlib has no runtime
     *    ``error()``, so a violation is a message at ``NONE`` verbosity -- the
     *    loudest thing available, and still only a message. A runtime that wants
     *    it fatal should bind the model's message sink to one; the text is
     *    deliberately distinctive so it can be matched. Returning
     *    ``WB_DMA_ERROR`` was considered and rejected: it would make a
     *    PROGRAMMING error indistinguishable from a DEVICE error. It answers
     *    PENDING instead, because the state needed for an honest answer was
     *    consumed by whoever broke the rule.
     */
    virtual task check_completion(output wb_dma_status_e status);
      bit tok;
      if (!(inflight.try_get(tok))) begin
        $display("wb_dma: check_completion() with no operation in progress on this channel -- either no *_start() was called, or a previous completion was already consumed");
        status = WB_DMA_PENDING;
        return;
      end
      probe_status(status);
      if (status == 2) begin
        // Still running: hand the token back. try_put cannot fail -- this
        // is the only holder, and it was just emptied.
        void'(inflight.try_put(tok));
      end
      status = status;
      return;
    endtask

    /**
     * Program a channel's registers from a config, without arming it.
     *
     * *§3.2 group 1, configuration.* Completes when CHn_SZ / A0 / AM0 / A1 /
     * AM1 and the RW bits of CHn_CSR reflect ``cfg``; the channel is NOT
     * enabled. Waits for nothing -- straight-line stores, no driver state,
     * callable from any context including with a lock held.
     *
     * Kept alongside ``transfer_single()``, which takes the same config and
     * subsumes this for the common case, for exactly one reason:
     * ``transfer_list()`` needs CHK_SZ programmed BEFORE the chain is armed
     * (§3.3), and a descriptor carries no chunk size.
     *
     * The CSR is written whole rather than read-modify-written, because at this
     * point nothing is running on the channel and a read would consume the
     * read-to-clear status bits for no reason.
     *
     * :param cfg: what to program; capability-gated fields are skipped when the
     *             channel was built without the capability
     */
    virtual task configure_channel(input wb_dma_ch_cfg_s cfg);
      wb_dma_sz_s sz;
      wb_dma_csr_s csr;
      m_regs.adr0.write_val(cfg.src);
      m_regs.am0.write_val(cfg.src_mask);
      m_regs.adr1.write_val(cfg.dst);
      m_regs.am1.write_val(cfg.dst_mask);
      sz.tot_sz = cfg.tot_sz;
      sz.chk_sz = cfg.chk_sz;
      m_regs.sz.write(sz);
      // CH_EN is what arms the channel, so it must not ride along with the
      // configuration write.
      csr.ch_en = 0;
      csr.src_sel = 1'(cfg.src_if);
      csr.dst_sel = 1'(cfg.dst_if);
      csr.inc_src = cfg.inc_src;
      csr.inc_dst = cfg.inc_dst;
      csr.mode = 1'(cfg.mode);
      csr.prio = cfg.prio;
      csr.sz_wb = cfg.sz_wb;
      // Capability-gated. Hardware silently ignores these on a channel built
      // without the capability, so decline rather than pretend they took.
      if (m_caps.ars) begin
        csr.ars = cfg.auto_restart;
        csr.rest_en = cfg.hw_restart_en;
      end
      csr.ine_done = cfg.int_on_done;
      csr.ine_err = cfg.int_on_err;
      csr.ine_chk_done = cfg.int_on_chunk;
      m_regs.csr.write(csr);
    endtask

    /**
     * Decode one read of CHn_CSR into a status. The unguarded primitive both
     * layers are built from.
     *
     * Not an operation, and not the API: no in-progress guard, no blocking, no
     * loop. It exists because the guard and the decode are separable concerns
     * and exactly one caller needs the decode without the guard.
     *
     * ``check_completion()``
     *     Guard plus this. The non-blocking API; firmware calls it.
     *
     * ``wait_completion()``
     *     This, in a loop, under a wake. The guard would be wrong inside a loop
     *     -- it is claimed once by the ``*_start()`` and released once by the
     *     operation that started it, not taken and put back on every poll.
     *
     * ``stop_channel()``
     *     This, in a loop, holding no token. Stop is the documented exemption
     *     from the one-operation-per-channel rule, so it has none to release.
     *
     * ERR is tested before DONE because the two are not exclusive: an aborted
     * transfer can retire with both set, and a stop that lands on an
     * already-completed channel certainly does. Reporting ERROR is the
     * conservative reading -- a scenario that expected DONE learns something
     * went wrong, where the reverse order would hide it.
     *
     * .. warning::
     *    Callers outside this component should use ``check_completion()``. PSS
     *    has no visibility control, so this cannot be enforced -- but reaching
     *    past the guard opts out of the only detector for the read-to-clear
     *    hazard, and the read is a side effect every time.
     */
    virtual task probe_status(output wb_dma_status_e status);
      wb_dma_csr_s csr;
      m_regs.csr.read(csr);
      if (csr.err == 1) begin
        status = WB_DMA_ERROR;
        return;
      end
      if (csr.done == 1) begin
        status = WB_DMA_DONE;
        return;
      end
      status = WB_DMA_PENDING;
      return;
    endtask

    /**
     * Set or clear the channel's auto-restart bit.
     *
     * *§3.2 group 1, configuration.* Completes when ARS has been updated; waits
     * for nothing.
     *
     * Distinct from ``configure_channel()`` because clearing ARS mid-flight is
     * the documented way to terminate an auto-restarting channel (§3.2.1),
     * invoked on its own against a live channel from a parallel scenario branch.
     * Rewriting the whole register bank to do that would be wrong.
     *
     * It is therefore the TERMINATING EVENT for an auto-restarting
     * ``transfer_single()``: once ARS is clear, the in-flight iteration retires
     * and DONE asserts.
     *
     * .. warning::
     *    A read-modify-write against a live channel, so it shares the hazard
     *    described on ``stop_channel_start()``: the read consumes any pending
     *    read-to-clear status. Enabling ARS before arming is unaffected;
     *    disabling it mid-flight is the exposed case.
     *
     * :param enable: 1 to auto-restart on completion, 0 to stop after the
     *                current iteration
     */
    virtual task set_auto_restart(input bit enable);
      // Silently ignored by hardware without ARS, so decline rather than
      // pretend.
      if (!(m_caps.ars)) begin
        return;
      end
      m_regs.csr.write_val_masked(64, (32'(enable) & 1) << 6);
    endtask

    /**
     * Publish how far a software reader has drained a FIFO in memory.
     *
     * *§3.2 group 1, configuration.* Completes when CHn_SWPTR has been updated
     * -- a channel stalled on the old pointer may resume as a side effect.
     * Waits for nothing.
     *
     * The consumer side of a FIFO in memory (§3.5): the DMA stalls rather than
     * overrun the software reader, and publishing a new pointer un-stalls it. So
     * this is invoked repeatedly during a live transfer, always concurrent with
     * a ``transfer_single()``.
     *
     * Note what that implies about scope: the FIFO's DATA is read on the test
     * writer's own memory path. This operation only publishes how far that
     * reader has got.
     *
     * Requires ``caps.cbuf``, and only means anything with a circular-buffer
     * address mask programmed on the same channel.
     *
     * :param ptr:    the new software pointer
     * :param enable: whether the pointer is honoured at all
     */
    virtual task set_software_pointer(input bit [30:0] ptr, input bit enable);
      wb_dma_swptr_s sw;
      if (!(m_caps.cbuf)) begin
        return;
      end
      // A whole-register write, not a read-modify-write: both fields are
      // supplied and this register carries no status to preserve. That also
      // keeps it clear of the CSR read-to-clear hazard, which matters because
      // this runs against a live channel.
      sw.ptr = ptr;
      sw.en = enable;
      m_regs.swptr.write(sw);
    endtask

    /**
     * Write STOP to abort whatever is running on this channel, and return.
     *
     * *§3.2 group 1.* The non-blocking half of ``stop_channel()``, present on
     * every profile. Completes when STOP has been written -- the abort itself
     * has not necessarily happened yet. Waits for nothing.
     *
     * An abort is reported as an ERROR, not as a clean stop: the device sets ERR
     * on a STOP write (§3.2.2). That is carried into the contract verbatim.
     *
     * **This claims no** :pss:field:`inflight` **token, deliberately.** By
     * definition it aborts a transfer that is still running, so the channel it
     * targets is already holding one. Claiming would report the one case the
     * model explicitly permits as a violation. Stop is the documented exemption
     * from the one-operation-per-channel rule, and the exemption is now visible
     * in the code rather than only in a comment.
     *
     * **Two consequences a firmware caller must know.**
     *
     * The ``write_field`` below IS a read-modify-write: the LRM defines the
     * field-wise write as one (§21.14.1), so the CHn_CSR read is there even
     * though the call no longer spells it out, and it still clears ERR and the
     * interrupt sources. That read happens BEFORE STOP is written, so it can
     * only consume status that was already there -- the abort's own ERR is set
     * afterwards and is still seen by the aborted transfer's poll. What it can
     * lose is a completion that landed in the instant before the abort.
     *
     * Who reports the abort is NOT determined by this model. The aborted
     * transfer polls the same CSR, and whichever read lands first consumes the
     * ERR. On the non-blocking profile the loser's ``check_completion()``
     * answers PENDING forever -- a firmware hang rather than an action that does
     * not retire.
     *
     * There is no ``check_completion()`` pairing for stop: it holds no token, so
     * it has nothing to poll with. A caller aborts, then keeps polling the
     * TRANSFER it aborted, which is the operation that owns the completion.
     *
     * .. note::
     *    Open question (§6.5): is write-1-to-STOP acknowledged before or after
     *    the current WISHBONE cycle retires? That decides whether an abort can
     *    be considered delivered on return, which matters post-silicon.
     */
    virtual task stop_channel_start();
      m_regs.csr.write_val_masked(512, 512);
    endtask

    /**
     * Point a channel at a descriptor list and arm it, returning with the chain
     * running.
     *
     * *§3.2 group 3.* The non-blocking half of ``transfer_list()``, present on
     * every profile. Completes when the channel points at the list, external
     * descriptors are enabled, and the channel is armed. Waits for nothing.
     *
     * §3.3's four-step arming procedure IS this function's body, except step 2
     * (chunk size), which must come from a prior ``configure_channel()`` because
     * it outlives any single descriptor. A descriptor carries only src, dst,
     * tot_sz, the increment flags, the interface selects and EOL; mode,
     * priority, ARS, the address masks and CHK_SZ stay whatever the channel
     * registers hold.
     *
     * Unlike ``transfer_single_start()``, this one always has a completion: ARS
     * is documented as meaningless and ignored with external descriptors (§3.3),
     * so ``check_completion()`` is guaranteed to answer DONE or ERROR
     * eventually. Two end-to-end operations differing only in completion
     * contract is why neither subsumes the other -- and the difference was never
     * in the wait.
     *
     * Requires ``caps.ed``. Unlike the other capability-gated operations this
     * reports rather than returning quietly, because it has a completion
     * contract: a silent return would leave the caller waiting for a chain that
     * was never armed.
     *
     * :param head: head of the descriptor chain; must be reachable from
     *              interface 0
     */
    virtual task transfer_list_start(input addr_handle_t head);
      // Checked before claiming, so a declined start leaves no token behind.
      if (!(m_caps.ed)) begin
        $display("wb_dma: transfer_list_start() on a channel built without external-descriptor support (caps.ed)");
        return;
      end
      if (!(inflight.try_put(1))) begin
        $display("wb_dma: transfer_list_start() on a channel that already has an operation in progress");
        return;
      end
      // Step 1: point the channel at the head of the list. The DMA fetches
      // descriptors from interface 0 regardless of which interface the data
      // moves on, so `head` must be IF0-reachable.
      m_regs.desc.write_val(32'(head));
      // Steps 3 and 4, in that order and as TWO WRITES, deliberately: the
      // device requires them separate, and write_fields({"use_ed","ch_en"},
      // {1,1}) would coalesce them into one bus read-modify-write -- that is
      // what the plural form is for. Each of these is still a
      // read-modify-write in its own right (§21.14.1).
      m_regs.csr.write_val_masked(128, 128);
      m_regs.csr.write_val_masked(1, 1);
    endtask

    /**
     * Program a channel and arm it, returning with the transfer running.
     *
     * *§3.2 group 1.* The non-blocking half of ``transfer_single()``, present on
     * every profile. Completes when the channel is programmed and armed -- NOT
     * when the transfer has moved anything. Waits for nothing.
     *
     * Program, arm, return. The caller then polls ``check_completion()`` until
     * it answers something other than PENDING, or calls ``transfer_single()``,
     * which is exactly this plus the wait. All of the device knowledge is here;
     * the end-to-end layer adds only the loop. That is why a SystemVerilog
     * regression that never calls this directly still tests it.
     *
     * **Two callers' obligations this signature does not encode.**
     *
     * ``mode == WB_DMA_HW_HANDSHAKE``: the transfer cannot complete on its own.
     * Something must be calling ``request_chunk()`` on the matching
     * ``wb_dma_hs_c`` concurrently (§2.2). Splitting arm from wait does not help
     * here -- the missing thing is a second initiator, not a second thread.
     *
     * ``cfg.auto_restart``: the transfer has NO completion event. CSR bit 11
     * sets DONE only once ARS is clear, so nothing this function starts will
     * ever make ``check_completion()`` answer DONE. Someone must clear ARS
     * (``set_auto_restart(0)``) or abort the channel (``stop_channel_start()``).
     * In the end-to-end layer that is a thread that never returns; here it is a
     * loop that never exits, which is a firmware hang rather than a stalled PSS
     * action. Same defect, less visible.
     *
     * Claims :pss:field:`inflight` FIRST, before touching a register, so a start
     * that would be the second on a live channel is reported without having
     * corrupted the configuration of the first.
     *
     * :param cfg: what to program before arming
     */
    virtual task transfer_single_start(input wb_dma_ch_cfg_s cfg);
      if (!(inflight.try_put(1))) begin
        $display("wb_dma: transfer_single_start() on a channel that already has an operation in progress");
        return;
      end
      configure_channel(cfg);
      // Arm. write_field is a read-modify-write (§21.14.1), so the
      // configuration just written survives; the read clears the read-to-clear
      // status bits, harmless here because the channel has not started yet.
      m_regs.csr.write_val_masked(1, 1);
    endtask

    /**
     * Wait until the device may have progressed.
     *
     * The wait PRIMITIVE: the one function in this model whose body differs
     * between execution targets, and the only thing
     * ``wb_dma_cfg_pkg::HAS_EVENT_WAIT`` gates.
     *
     * **Contract: return when the device MAY have progressed.** Not "when it
     * has" -- this reports nothing and decides nothing. Every caller is a loop
     * that re-reads CHn_CSR afterwards and tests its own condition, so a
     * spurious return costs one register read and a late return costs latency.
     * Neither is a defect.
     *
     * This is the seam that lets the OPERATION SURFACE be profile-independent.
     * The two ways to wait have different requirements:
     *
     * ``wake.get()``
     *     Suspend until someone posts. Needs an event source (``notify_irq()``,
     *     hence configured interrupt routing) and a runtime that can suspend a
     *     caller. Costs nothing while waiting.
     *
     * ``yield``
     *     Spin. Needs NOTHING -- every target can spin, including a bare-metal
     *     single-threaded one. Costs the bus a read per iteration and, on a
     *     threaded target, whatever the scheduler charges.
     *
     * Only the first is a capability, so that is what the flag asks about and
     * this is where the answer is consumed. Every operation above it is written
     * once and compiles on both. See ``docs/op-model-c-embedded-design.md``
     * §5.4 and ``docs/target-cfg-contract.md``.
     *
     * .. warning::
     *    ``yield`` is a hint to the SCHEDULER, not to the device, and a backend
     *    spends it however its target charges for waiting. It must NOT be
     *    implemented as a wait on this device's interrupt: that would
     *    reintroduce the routing prerequisite this branch exists to avoid, and
     *    would deadlock the one caller that has no interrupt to wait for. The
     *    contract is stated in full in ``docs/op-model-export-design.md`` §4.4.
     */
    virtual task wait_hint();
      // The token carries no information and is discarded: notify_irq()
      // posts to EVERY channel regardless of which one raised the
      // interrupt, and with CHUNK_DONE enabled the interrupt also fires on
      // events that complete nothing, so most wakes are for someone else.
      // That is precisely why every caller is a wake-and-recheck loop
      // rather than a single suspend.
      //
      // A target exec blocked on a channel operation does not stall other
      // execs on the same executor (§20.8).
      begin
        bit pssc_discard;
        wake.get(pssc_discard);
      end
    endtask

  endclass

  // ----- Component handle/factory: wb_dma_c -----
  /**
   * The MMIO operation model for the WISHBONE DMA/Bridge core (§3,
   * ``dma_mmio_c`` in the operation-model document).
   *
   * This component holds the engine-GLOBAL operations -- PAUSE, interrupt
   * routing, descriptor authoring. Everything per-channel is on
   * :pss:comp:`wb_dma_ch_c`, an array of which it owns.
   *
   * Scope (§1): everything the processor reaches by load/store. The per-channel
   * hardware handshake's participant is the PERIPHERAL, so its model sits with
   * the environment (``tests/pss/wb_dma_hs_c.pss``). The WISHBONE masters are
   * device-driven and out of scope; so is descriptor FETCHING, though descriptor
   * AUTHORING is here, because the processor initiates it.
   *
   * Deliberately absent:
   *
   * * **bulk buffer access** -- the test writer already has a path to memory
   *   (``read32``/``write32``); filling a source region and checking a
   *   destination region are not operations of this model.
   * * **bus-error injection** -- it belongs to whatever component can drive
   *   ``err_i``. A DMA-error-reaction test is a composition of two operation
   *   models, not a wider version of this one (§5.1).
   * * **bridge_access** -- the pass-through path is reachable only with a target
   *   on the far interface; omitted by review decision.
   */
  class wb_dma_c #(type IMP_T = wb_dma_c_import_if) implements wb_dma_c_if, wb_dma_c_import_if;
    protected IMP_T m_imp;
    protected wb_dma_regs_c m_regs;
    // How many channels this instance actually uses.
    //
    // Integrator-facing: operations should be issued only to
    // ``ch[0..num_ch-1]``. Nothing in this model enforces that -- the register
    // structure is sized at ``WB_DMA_MAX_CH`` regardless, so a stray
    // access reaches a bank the RTL may not implement.
    protected int m_num_ch;
    // Build-time ``pri_sel``: how many priority levels the part discriminates.
    //
    // Integrator-facing, and likewise unenforced. Legal values are 1, 4 and 8;
    // a ``wb_dma_ch_cfg_s.prio`` above this is not an error, it simply does not
    // discriminate.
    protected int m_pri_levels;
    protected wb_dma_ch_c m_ch[4];

    function new(IMP_T imp, addr_handle_t base);
      m_imp = imp;
      m_num_ch = 4;
      m_pri_levels = 4;
      m_regs = new(this, base);
      for (int i = 0; i < 4; i++) begin
        m_ch[i] = new(this, i, (base + (64'h20 + 64'h20 * i)));
      end
    endfunction

    /**
     * Route a set of channels to one of the two aggregate interrupt outputs.
     *
     * *§3.2 group 2, configuration.* Completes when INT_MSK_A/B has been
     * updated; waits for nothing.
     *
     * The two banks are independent aggregate outputs, and a channel may be
     * routed to both. ``channel_mask`` stays a bit vector rather than becoming
     * a channel list because it genuinely is one: bit N routes channel N.
     *
     * **A hard prerequisite for every end-to-end operation, enforced by
     * deadlock** on the event-wait profile. Completion IS the interrupt, so a
     * test that routes nothing raises no interrupt, nothing calls
     * ``notify_irq()``, and the first wait blocks forever. Routing at least one
     * channel in a bank keeps the whole test alive, because ``notify_irq()``
     * posts to every channel blind. That is intended: a hang is a more honest
     * result than a green test whose completion path was never exercised.
     *
     * :param bank:         which aggregate output to program
     * :param channel_mask: bit N routes channel N
     */
    virtual task configure_interrupt_routing(input wb_dma_int_bank_e bank, input bit [30:0] channel_mask);
      wb_dma_intmsk_s vec;
      vec.ch = channel_mask;
      case (bank)
        0: begin
          m_regs.int_msk_a.write(vec);
        end
        1: begin
          m_regs.int_msk_b.write(vec);
        end
      endcase
    endtask

    virtual task notify_irq();
      foreach (m_ch[i]) begin
        void'(m_ch[i].wake.try_put(1));
      end
    endtask

    /**
     * Pause or un-pause the whole engine, and wait until it has taken effect.
     *
     * *§3.2 group 2, configuration.* Global, not per-channel.
     *
     * Completes when a readback of ``CSR.PAUSE`` matches the requested value.
     * The engine only pauses after the CURRENT transfer completes, so the write
     * and the state change are NOT simultaneous -- which is the entire reason
     * this is an operation rather than a register write, and the clearest small
     * illustration of the blocking rule: the operation is not done when the
     * store retires.
     *
     * It waits for that readback, and is the one wait in this model with no
     * interrupt behind it -- in a real driver, a retry or timer loop rather than
     * an ISR wake. The global CSR is not read-to-clear, so unlike the channel
     * CSR this poll is genuinely side-effect-free and may run any number of
     * times.
     *
     * :param pause: 1 to pause, 0 to resume
     */
    virtual task pause_engine(input bit pause);
      wb_dma_gcsr_s gcsr;
      gcsr.pause = pause;
      m_regs.csr.write(gcsr);
      forever begin
        m_regs.csr.read(gcsr);
        if (gcsr.pause == pause) begin
          break;
        end
        m_imp.yield_();
      end
    endtask

    /**
     * Read back how much of a descriptor's transfer actually moved.
     *
     * *§3.2 group 3, configuration.* Completes when DESC_CSR has been loaded
     * back from memory and decoded; waits for nothing.
     *
     * A device-specific decode, not a memory service -- the same rationale that
     * keeps ``write_descriptor()`` in this model. Only meaningful when SZ_WB is
     * set in the channel CSR and the descriptor was cut short by
     * ``skip_to_next_descriptor()``. This is how software learns how much of a
     * variable-length payload actually moved, which is the whole point of §3.9.
     *
     * .. note::
     *    Open question (§6.1): §3.9 says the remaining BYTES are written back,
     *    into a field Table 1 defines as a 12-bit WORD count. One of the two is
     *    wrong. This returns the raw field and lets the caller decide.
     *
     * :param desc_ptr: the descriptor whose control word is read back
     */
    virtual task read_descriptor_residual(output bit [11:0] status, input addr_handle_t desc_ptr);
      bit [31:0] desc_csr;
      read32(desc_ptr, desc_csr);
      status = 12'(desc_csr);
      return;
    endtask

    /**
     * Write one external descriptor into memory and link it to its predecessor.
     *
     * *§3.2 group 3, configuration.* Completes when the descriptor is in memory
     * at ``at``, terminated (DESC_NEXT zero), and ``prev`` -- if there is one --
     * points at it. Waits for nothing. Returns a handle to the slot immediately
     * after ``at``, i.e. the natural place for the next descriptor, so a caller
     * can build a list in place one link at a time.
     *
     * This is DEVICE KNOWLEDGE written through a memory path, not a path to
     * memory: the next-pointer linkage and the EOL rule are the operation, the
     * layout is declared by :pss:struct:`wb_dma_desc_s`, and ``write32`` is
     * merely how it lands. That is what makes it an operation where a generic
     * ``write_buffer()`` would not be.
     *
     * ``at`` must be reachable from interface 0: descriptors are fetched from
     * IF0 regardless of which interface the DATA moves on (§3.3).
     *
     * :param at:   where this descriptor goes
     * :param prev: the descriptor to link from; null/zero means "head of list"
     * :param desc: the descriptor contents; the caller's copy is not modified
     */
    virtual task write_descriptor(output addr_handle_t status, input addr_handle_t at, input addr_handle_t prev, input wb_dma_desc_s desc);
      wb_dma_desc_s d;
      bit [31:0] csr_word;
      // Deep copy: `desc` is the caller's struct (aggregates pass by handle)
      // and we terminate this link ourselves.
      d = desc;
      d.next = 0;
      // This block is one call -- write_struct(at, d) -- once read_struct /
      // write_struct land; they are commented out of the front end's
      // addr_reg_pkg ("TODO: generic type"). wb_dma_desc_s already declares
      // the packed layout, so nothing here adds information.
      csr_word = 32'(d.csr.tot_sz);
      csr_word |= 32'(d.csr.dst_sel) << 16;
      csr_word |= 32'(d.csr.src_sel) << 17;
      csr_word |= 32'(d.csr.inc_dst) << 18;
      csr_word |= 32'(d.csr.inc_src) << 19;
      csr_word |= 32'(d.csr.eol) << 20;
      write32(at, csr_word);
      write32((at + 4), d.adr0);
      write32((at + 8), d.adr1);
      write32((at + 12), d.next);
      // Extend the list. The check is on the resolved address rather than a
      // handle comparison, because an address handle is opaque and not
      // usefully comparable.
      if (prev != 0) begin
        write32((prev + 12), 32'(at));
      end
      status = (at + 16);
      return;
    endtask

    virtual function wb_dma_ch_c_if ch(int index);
      return m_ch[index];
    endfunction
    virtual function int ch_size();
      return 4;
    endfunction

    virtual task yield_(); m_imp.yield_(); endtask
    virtual task write8(addr_handle_t addr, bit [7:0] data); m_imp.write8(addr, data); endtask
    virtual task read8(addr_handle_t addr, output bit [7:0] data); m_imp.read8(addr, data); endtask
    virtual task write16(addr_handle_t addr, bit [15:0] data); m_imp.write16(addr, data); endtask
    virtual task read16(addr_handle_t addr, output bit [15:0] data); m_imp.read16(addr, data); endtask
    virtual task write32(addr_handle_t addr, bit [31:0] data); m_imp.write32(addr, data); endtask
    virtual task read32(addr_handle_t addr, output bit [31:0] data); m_imp.read32(addr, data); endtask
    virtual task write64(addr_handle_t addr, bit [63:0] data); m_imp.write64(addr, data); endtask
    virtual task read64(addr_handle_t addr, output bit [63:0] data); m_imp.read64(addr, data); endtask
    static function wb_dma_c_if create(IMP_T imp, addr_handle_t base);
      wb_dma_c #(IMP_T) self = new(imp, base);
      return self;
    endfunction
  endclass

endpackage
