"""Programming API for `wb_dma_c`, generated by pssc 0.1.0 (op-model-py).

DO NOT EDIT. Regenerate from the PSS model instead.

The bus is a PROTOCOL, not a base class: pass any object with
`read32(addr)` / `write32(addr, data)` and whatever other widths
this model's registers use. `pssc_rt.py`, copied beside this file,
documents it and ships a `MemoryBus` to bring the model up on.

    from wb_dma import WbDma
    from pssc_rt import MemoryBus

    dut = WbDma(bus, base)
"""


# This model declares channels, so it needs the shipped depth-1
# channel. Everything else in this module stands alone.
from pssc_rt import Chan1


# ----- Data types used by the export API. -----
# wb_dma_int_bank_e
WB_DMA_INT_A = 0
WB_DMA_INT_B = 1

# wb_dma_status_e
WB_DMA_DONE = 0
WB_DMA_ERROR = 1
WB_DMA_PENDING = 2

# wb_dma_if_e
WB_DMA_IF0 = 0
WB_DMA_IF1 = 1

# wb_dma_mode_e
WB_DMA_SOFTWARE = 0
WB_DMA_HW_HANDSHAKE = 1

class _Struct(object):
    """Base of every plain (non-register) struct the API mentions.

    A subclass declares `FIELDS` -- names in declaration order -- and the
    matching `__slots__`. Fields default to 0 and may be set positionally or by
    keyword, so a caller writes `wb_dma_ch_cfg_s(prio=2)` and gets defined
    values for everything else.
    """

    __slots__ = ()

    FIELDS = ()

    def __init__(self, *args, **kwargs):
        if len(args) > len(self.FIELDS):
            raise TypeError("%s takes at most %d positional arguments" % (
                type(self).__name__, len(self.FIELDS)))
        for name in self.FIELDS:
            setattr(self, name, 0)
        for name, value in zip(self.FIELDS, args):
            setattr(self, name, value)
        for name, value in kwargs.items():
            if name not in self.FIELDS:
                raise TypeError("%s has no field %r; it has: %s" % (
                    type(self).__name__, name, ", ".join(self.FIELDS)))
            setattr(self, name, value)

    def __eq__(self, other):
        return type(other) is type(self) and all(
            getattr(other, n) == getattr(self, n) for n in self.FIELDS)

    def __ne__(self, other):
        return not self.__eq__(other)

    def __repr__(self):
        return "%s(%s)" % (type(self).__name__, ", ".join(
            "%s=%r" % (n, getattr(self, n)) for n in self.FIELDS))
class wb_dma_desc_csr_s(_Struct):
    """The control word of one external (linked-list) descriptor
    (§3.3 Figure 6 / Table 1).

    A packed struct whose declaration order IS the bit numbering,
    LITTLE_ENDIAN -- this is the MEMORY LAYOUT, not a decoded view, so
    ``write_descriptor()`` places fields rather than composing them.

    The interface selects are plain bits rather than
    :pss:enum:`wb_dma_if_e` because a packed struct may only hold an enum
    that has a base type, and the front end does not parse enum base types.
    0 = IF0, 1 = IF1.

    :group: Structures
    """

    __slots__ = (
        "tot_sz", "reserved0", "dst_sel", "src_sel", "inc_dst", "inc_src",
        "eol", "reserved1",
    )
    FIELDS = (
        "tot_sz", "reserved0", "dst_sel", "src_sel", "inc_dst", "inc_src",
        "eol", "reserved1",
    )

class wb_dma_desc_s(_Struct):
    """One external (linked-list) descriptor, as it sits in memory.

    A descriptor carries a strict SUBSET of the channel CSR: mode, priority,
    ARS, the address masks and CHK_SZ are not in it and stay whatever the
    channel registers hold. That is why ``transfer_list()`` depends on a
    prior ``configure_channel()``.

    :group: Structures
    """

    __slots__ = ("csr", "adr0", "adr1", "next")
    FIELDS = ("csr", "adr0", "adr1", "next")

class wb_dma_ch_caps_s(_Struct):
    """Build-time per-channel capabilities (RTL ``chN_conf``).

    Modelled because they change WHICH OPERATIONS ARE LEGAL on a channel: an
    absent capability makes the corresponding control bit SILENTLY IGNORED by
    hardware rather than raising an error (App. A), so a test that programs
    ARS on a channel built without it gets no error and no auto-restart.

    Set on ``wb_dma_ch_c.caps`` from an init exec, and read by the operations
    to decide what they will attempt.

    :group: Structures
    """

    __slots__ = ("present", "ars", "ed", "cbuf")
    FIELDS = ("present", "ars", "ed", "cbuf")

class wb_dma_ch_cfg_s(_Struct):
    """Everything ``configure_channel()`` programs into a channel's register
    bank (§3.2, ``chan_cfg_s``).

    Fields that land directly on a CSR bit are declared ``bit`` rather than
    ``bool`` so the operation code can assign them into the register-value
    struct without a conversion; the trailing comment names the bit.

    Deliberately NOT in here: anything the DMA drives itself, and anything
    belonging to the test writer's own memory path. Filling the source region
    and checking the destination region are plain memory accesses, not part
    of the transfer's configuration.

    :group: Structures
    """

    __slots__ = (
        "src", "dst", "src_mask", "dst_mask", "tot_sz", "chk_sz", "src_if",
        "dst_if", "inc_src", "inc_dst", "mode", "prio", "auto_restart",
        "hw_restart_en", "sz_wb", "int_on_done", "int_on_err", "int_on_chunk",
    )
    FIELDS = (
        "src", "dst", "src_mask", "dst_mask", "tot_sz", "chk_sz", "src_if",
        "dst_if", "inc_src", "inc_dst", "mode", "prio", "auto_restart",
        "hw_restart_en", "sz_wb", "int_on_done", "int_on_err", "int_on_chunk",
    )


class _RegValue(object):
    """Base of every register value class: a bit layout, packed and unpacked.

    A subclass declares `LAYOUT` -- `(name, lsb, width)` in declaration order,
    LSB first -- and `BITS`. Everything else is here.

    Fields are plain attributes, so a value is built and edited the way the PSS
    body does it (`csr.CH_EN = 1`) and `__slots__` turns a misspelled field name
    into an AttributeError instead of a silently ignored assignment.
    """

    __slots__ = ()

    LAYOUT = ()
    BITS = 0

    def __init__(self, **fields):
        for name, _, _ in self.LAYOUT:
            setattr(self, name, 0)
        for name, value in fields.items():
            if name not in self.__slots__:
                raise TypeError("%s has no field %r; it has: %s" % (
                    type(self).__name__, name,
                    ", ".join(n for n, _, _ in self.LAYOUT)))
            setattr(self, name, value)

    @classmethod
    def unpack(cls, raw):
        """The value a raw register word represents."""
        v = cls()
        for name, lsb, width in cls.LAYOUT:
            setattr(v, name, (raw >> lsb) & ((1 << width) - 1))
        return v

    def pack(self):
        """The raw register word this value represents.

        Each field is masked to its own width, so an out-of-range assignment
        corrupts that field rather than its neighbours.
        """
        raw = 0
        for name, lsb, width in self.LAYOUT:
            raw |= (int(getattr(self, name)) & ((1 << width) - 1)) << lsb
        return raw

    def __eq__(self, other):
        return type(other) is type(self) and other.pack() == self.pack()

    def __ne__(self, other):
        return not self.__eq__(other)

    def __repr__(self):
        return "%s(%s)" % (type(self).__name__, ", ".join(
            "%s=%d" % (n, getattr(self, n))
            for n, _, _ in self.LAYOUT if getattr(self, n)))


class wb_dma_csr_s(_RegValue):
    """wb_dma_regs.bank[].csr"""

    __slots__ = (
        "ch_en", "dst_sel", "src_sel", "inc_dst", "inc_src", "mode", "ars",
        "use_ed", "sz_wb", "stop", "busy", "done", "err", "prio", "rest_en",
        "ine_err", "ine_done", "ine_chk_done", "int_err", "int_done",
        "int_chk_done", "rsvd_23",
    )
    BITS = 32
    LAYOUT = (
        ("ch_en", 0, 1),   # [0] sw=rw hw=r reset=0x0
        ("dst_sel", 1, 1),   # [1] sw=rw hw=r reset=0x0
        ("src_sel", 2, 1),   # [2] sw=rw hw=r reset=0x0
        ("inc_dst", 3, 1),   # [3] sw=rw hw=r reset=0x0
        ("inc_src", 4, 1),   # [4] sw=rw hw=r reset=0x0
        ("mode", 5, 1),   # [5] sw=rw hw=r reset=0x0
        ("ars", 6, 1),   # [6] sw=rw hw=r reset=0x0
        ("use_ed", 7, 1),   # [7] sw=rw hw=r reset=0x0
        ("sz_wb", 8, 1),   # [8] sw=rw hw=r reset=0x0
        ("stop", 9, 1),   # [9] sw=w hw=r reset=0x0
        ("busy", 10, 1),   # [10] sw=r hw=w
        ("done", 11, 1),   # [11] sw=r hw=w
        ("err", 12, 1),   # [12] sw=r hw=w
        ("prio", 13, 3),   # [15:13] sw=rw hw=r reset=0x0
        ("rest_en", 16, 1),   # [16] sw=rw hw=r reset=0x0
        ("ine_err", 17, 1),   # [17] sw=rw hw=r reset=0x0
        ("ine_done", 18, 1),   # [18] sw=rw hw=r reset=0x0
        ("ine_chk_done", 19, 1),   # [19] sw=rw hw=r reset=0x0
        ("int_err", 20, 1),   # [20] sw=r hw=w reset=0x0 dropped: onread=rclr, intr, enable
        ("int_done", 21, 1),   # [21] sw=r hw=w reset=0x0 dropped: onread=rclr, intr, enable
        ("int_chk_done", 22, 1),   # [22] sw=r hw=w reset=0x0 dropped: onread=rclr, intr, enable
        ("rsvd_23", 23, 9),   # [31:23] reserved
    )


class wb_dma_sz_s(_RegValue):
    """wb_dma_regs.bank[].sz"""

    __slots__ = ("tot_sz", "rsvd_12", "chk_sz", "rsvd_25")
    BITS = 32
    LAYOUT = (
        ("tot_sz", 0, 12),   # [11:0] sw=rw hw=r
        ("rsvd_12", 12, 4),   # [15:12] reserved
        ("chk_sz", 16, 9),   # [24:16] sw=rw hw=r
        ("rsvd_25", 25, 7),   # [31:25] reserved
    )


class wb_dma_addr_s(_RegValue):
    """wb_dma_regs.bank[].adr0 (+1 more)"""

    __slots__ = ("addr")
    BITS = 32
    LAYOUT = (
        ("addr", 0, 32),   # [31:0] sw=rw hw=r
    )


class wb_dma_amask_s(_RegValue):
    """wb_dma_regs.bank[].am0 (+1 more)"""

    __slots__ = ("mask")
    BITS = 32
    LAYOUT = (
        ("mask", 0, 32),   # [31:0] sw=rw hw=r reset=0xfffffffc
    )


class wb_dma_descptr_s(_RegValue):
    """wb_dma_regs.bank[].desc"""

    __slots__ = ("ptr")
    BITS = 32
    LAYOUT = (
        ("ptr", 0, 32),   # [31:0] sw=rw hw=rw
    )


class wb_dma_swptr_s(_RegValue):
    """wb_dma_regs.bank[].swptr"""

    __slots__ = ("ptr", "en")
    BITS = 32
    LAYOUT = (
        ("ptr", 0, 31),   # [30:0] sw=rw hw=r reset=0x0
        ("en", 31, 1),   # [31] sw=rw hw=r reset=0x0
    )


class wb_dma_gcsr_s(_RegValue):
    """wb_dma_regs.csr"""

    __slots__ = ("pause", "rsvd_1")
    BITS = 32
    LAYOUT = (
        ("pause", 0, 1),   # [0] sw=rw hw=r reset=0x0
        ("rsvd_1", 1, 31),   # [31:1] reserved
    )


class wb_dma_intmsk_s(_RegValue):
    """wb_dma_regs.int_msk_a (+1 more)"""

    __slots__ = ("ch", "rsvd_31")
    BITS = 32
    LAYOUT = (
        ("ch", 0, 31),   # [30:0] sw=rw hw=r reset=0x0
        ("rsvd_31", 31, 1),   # [31] reserved
    )


class wb_dma_intsrc_s(_RegValue):
    """wb_dma_regs.int_src_a (+1 more)"""

    __slots__ = ("ch", "rsvd_31")
    BITS = 32
    LAYOUT = (
        ("ch", 0, 31),   # [30:0] sw=r hw=w reset=0x0
        ("rsvd_31", 31, 1),   # [31] reserved
    )


class WbDmaCh(object):
    """The per-channel MMIO operation model (§3).

    Every operation the processor initiates against ONE DMA channel lives here.
    The engine-global operations live on :pss:comp:`wb_dma_c`, which owns an
    array of these.

    **Why per-channel components rather than a `chan` parameter.** The completion
    condition is a channel register, so making the channel an instance rather
    than an index keeps every access in the operation code index-free
    (``regs.csr.read()``), which is both clearer and safer than indexing a
    register array with a runtime value. It also matches the review decision that
    a waking thread reads its own channel's status register (§3.1.1). The cost is
    that each channel binds its own top-level register group.

    **Two layers, and every target gets both.**

    ``core``
        ``configure_channel``, ``set_auto_restart``, ``set_software_pointer``,
        ``transfer_single_start``, ``transfer_list_start``,
        ``stop_channel_start``, ``check_completion``. Arm-and-return plus a
        single-read poll; nothing here ever waits. The low-level driver API.

    ``end-to-end``
        ``wait_completion``, ``transfer_single``, ``transfer_list``,
        ``stop_channel``. Each is a ``*_start()`` followed by
        ``repeat { probe_status; wait_hint }``.

    What varies between profiles is one function body -- ``wait_hint()``, which
    either suspends on :pss:field:`wake` or spins with ``yield``. Nothing else
    reads ``HAS_EVENT_WAIT`` except ``notify_irq()``, the event producer.

    The end-to-end layer adds no device knowledge, only the loop. That is what
    makes the core trustworthy without a second regression: every SystemVerilog
    run drives the core through the end-to-end wrappers.
    """

    def __init__(self, bus, id, bank):
        self._bus = bus
        self._base = bank
        self.inflight = Chan1()
        self.wake = Chan1()
        self.chan = 0
        self.caps = wb_dma_ch_caps_s(present=True, ars=True, ed=True, cbuf=True)
        self.chan = id
        self._base = bank

    # ----- Register accessors, offsets folded. -----
    def regs_csr_addr(self):
        """Address of `regs.csr`."""
        return self._base + 0x0
    def regs_csr_read_val(self):
        return self._bus.read32(self.regs_csr_addr())
    def regs_csr_write_val(self, value):
        self._bus.write32(self.regs_csr_addr(), value)
    def regs_csr_read(self):
        return wb_dma_csr_s.unpack(self.regs_csr_read_val())
    def regs_csr_write(self, value):
        self.regs_csr_write_val(value.pack())
    def regs_csr_write_val_masked(self, mask, val):
        cur = self.regs_csr_read_val()
        self.regs_csr_write_val((cur & ~mask) | (val & mask))
    def regs_sz_addr(self):
        """Address of `regs.sz`."""
        return self._base + 0x4
    def regs_sz_read_val(self):
        return self._bus.read32(self.regs_sz_addr())
    def regs_sz_write_val(self, value):
        self._bus.write32(self.regs_sz_addr(), value)
    def regs_sz_read(self):
        return wb_dma_sz_s.unpack(self.regs_sz_read_val())
    def regs_sz_write(self, value):
        self.regs_sz_write_val(value.pack())
    def regs_sz_write_val_masked(self, mask, val):
        cur = self.regs_sz_read_val()
        self.regs_sz_write_val((cur & ~mask) | (val & mask))
    def regs_adr0_addr(self):
        """Address of `regs.adr0`."""
        return self._base + 0x8
    def regs_adr0_read_val(self):
        return self._bus.read32(self.regs_adr0_addr())
    def regs_adr0_write_val(self, value):
        self._bus.write32(self.regs_adr0_addr(), value)
    def regs_adr0_read(self):
        return wb_dma_addr_s.unpack(self.regs_adr0_read_val())
    def regs_adr0_write(self, value):
        self.regs_adr0_write_val(value.pack())
    def regs_adr0_write_val_masked(self, mask, val):
        cur = self.regs_adr0_read_val()
        self.regs_adr0_write_val((cur & ~mask) | (val & mask))
    def regs_am0_addr(self):
        """Address of `regs.am0`."""
        return self._base + 0xc
    def regs_am0_read_val(self):
        return self._bus.read32(self.regs_am0_addr())
    def regs_am0_write_val(self, value):
        self._bus.write32(self.regs_am0_addr(), value)
    def regs_am0_read(self):
        return wb_dma_amask_s.unpack(self.regs_am0_read_val())
    def regs_am0_write(self, value):
        self.regs_am0_write_val(value.pack())
    def regs_am0_write_val_masked(self, mask, val):
        cur = self.regs_am0_read_val()
        self.regs_am0_write_val((cur & ~mask) | (val & mask))
    def regs_adr1_addr(self):
        """Address of `regs.adr1`."""
        return self._base + 0x10
    def regs_adr1_read_val(self):
        return self._bus.read32(self.regs_adr1_addr())
    def regs_adr1_write_val(self, value):
        self._bus.write32(self.regs_adr1_addr(), value)
    def regs_adr1_read(self):
        return wb_dma_addr_s.unpack(self.regs_adr1_read_val())
    def regs_adr1_write(self, value):
        self.regs_adr1_write_val(value.pack())
    def regs_adr1_write_val_masked(self, mask, val):
        cur = self.regs_adr1_read_val()
        self.regs_adr1_write_val((cur & ~mask) | (val & mask))
    def regs_am1_addr(self):
        """Address of `regs.am1`."""
        return self._base + 0x14
    def regs_am1_read_val(self):
        return self._bus.read32(self.regs_am1_addr())
    def regs_am1_write_val(self, value):
        self._bus.write32(self.regs_am1_addr(), value)
    def regs_am1_read(self):
        return wb_dma_amask_s.unpack(self.regs_am1_read_val())
    def regs_am1_write(self, value):
        self.regs_am1_write_val(value.pack())
    def regs_am1_write_val_masked(self, mask, val):
        cur = self.regs_am1_read_val()
        self.regs_am1_write_val((cur & ~mask) | (val & mask))
    def regs_desc_addr(self):
        """Address of `regs.desc`."""
        return self._base + 0x18
    def regs_desc_read_val(self):
        return self._bus.read32(self.regs_desc_addr())
    def regs_desc_write_val(self, value):
        self._bus.write32(self.regs_desc_addr(), value)
    def regs_desc_read(self):
        return wb_dma_descptr_s.unpack(self.regs_desc_read_val())
    def regs_desc_write(self, value):
        self.regs_desc_write_val(value.pack())
    def regs_desc_write_val_masked(self, mask, val):
        cur = self.regs_desc_read_val()
        self.regs_desc_write_val((cur & ~mask) | (val & mask))
    def regs_swptr_addr(self):
        """Address of `regs.swptr`."""
        return self._base + 0x1c
    def regs_swptr_read_val(self):
        return self._bus.read32(self.regs_swptr_addr())
    def regs_swptr_write_val(self, value):
        self._bus.write32(self.regs_swptr_addr(), value)
    def regs_swptr_read(self):
        return wb_dma_swptr_s.unpack(self.regs_swptr_read_val())
    def regs_swptr_write(self, value):
        self.regs_swptr_write_val(value.pack())
    def regs_swptr_write_val_masked(self, mask, val):
        cur = self.regs_swptr_read_val()
        self.regs_swptr_write_val((cur & ~mask) | (val & mask))

    def wait_completion(self):
        """Block until the operation running on this channel reaches a terminal state.

        *§3.1.* Not an operation in its own right: it is the ONE place in this tree
        that waits for a completion, and therefore the whole of what the end-to-end
        operations add over their ``*_start()`` halves. Present on every profile --
        these functions do not need a scheduler, they need a way to wait, and that
        choice is made once, in ``wait_hint()``.

        Waiting is realised as ``repeat { probe_status; wait_hint }``, where
        ``probe_status()`` is the same single CSR read ``check_completion()`` uses.
        Nothing is edge-triggered: the condition is re-read from the device on every
        iteration, waking threads test their own conditions, and a spurious wake is
        harmless. That is what makes the loop correct whether ``wait_hint()``
        suspends on an interrupt or merely spins -- the two differ in what a lap
        costs, not in what the loop concludes. **The wake is a hint; CHn_CSR is the
        event.**

        That sharing is the argument for the whole start/wait split. The
        non-blocking core is not a second implementation to be kept in step with
        this one -- it is the body of this one, hoisted. A SystemVerilog regression
        that only ever calls ``transfer_single()`` still executes every register
        access a firmware caller will make, in the same order, so the two paths
        cannot drift. That is why there is no second regression for the firmware
        profile.

        **The side-effect problem (§3.1.1).** ``probe_status()`` runs an unbounded
        number of times and it consumes state: reading CHn_CSR clears ERR and the
        three interrupt-source bits. It is safe because the value is captured by the
        same read that observes it, the loop exits holding it, and AT MOST ONE
        OPERATION PER CHANNEL AT A TIME makes the polling thread the sole consumer.
        ``stop_channel()`` is the one deliberate exception.

        **The guard is released here** because an operation is over when its
        completion has been reported, which is this return. Releasing here rather
        than in each caller keeps the claim and the release one fact in two places
        instead of one in three.

        A stale ``wake`` token costs one read, exactly, and only on the event-wait
        profile: the loop probes BEFORE it ever waits, and ``wake``'s depth of 1
        caps the leftover at one, so the worst case is probe, wait-immediate, probe,
        wait-blocks. There is deliberately no drain step at entry -- it would cost
        the same read it saves.

        .. warning::
           On the event-wait profile the routing prerequisite is load-bearing. A
           test that never called ``configure_interrupt_routing()`` raises no
           interrupt, so nothing calls ``notify_irq()``, so this blocks forever.
           Blind posting softens it -- any ONE routed channel's interrupt wakes
           every waiter -- so a partially routed test still makes progress and a
           test that routes nothing deadlocks. That is intended: a hang is a more
           honest result than a green test whose completion path was never real. If
           you are debugging a hang here, check INT_MSK_A/B before you look at the
           DMA. A polling profile has no such exposure, because ``wait_hint()``
           spins -- the routing requirement belongs to the wait primitive, not to
           this operation.
        """
        status = 0
        tok = [0]   # PSS local, held in a cell: channel try_get output
        while True:
            status = self.probe_status()
            if status != 2:
                break
            self.wait_hint()
        # The operation is over: drop the claim its *_start() took. The result is
        # discarded because there is one case where the token is legitimately
        # absent -- a *_start() that reported a double-start and returned without
        # arming, whose caller is already in error.
        self.inflight.try_get(tok)
        return status

    def transfer_single(self, cfg):
        """Run one transfer to completion and report how it ended.

        *§3.2 group 1, end-to-end.* Completes when the channel's DONE (or ERR)
        interrupt has been observed and the CHn_CSR read has returned the status and
        cleared the source. Waits for channel DONE or ERR -- this is the core driver
        FSM: submit, RUNNING, completion.

        The body is the two halves, named. All of the device knowledge -- what to
        program, in what order, which write arms the channel -- is in
        ``transfer_single_start()``; all of the waiting is in ``wait_completion()``.
        This function contributes the composition and the return type.

        .. warning::
           Two callers' obligations this signature does not encode, both stated in
           full on ``transfer_single_start()``. With
           ``mode == WB_DMA_HW_HANDSHAKE`` this call cannot complete on its own:
           something must be calling ``request_chunk()`` on the matching
           ``wb_dma_hs_c`` concurrently (§2.2). With ``cfg.auto_restart`` this call
           is DELIBERATELY NON-TERMINATING: another thread must clear ARS or abort
           the channel. It is a blocking read on a stream that ends when someone
           closes it, so an ARS transfer must never be the only operation a scenario
           waits on.

        :param cfg: what to program before arming
        """
        self.transfer_single_start(cfg)
        return self.wait_completion()

    def transfer_list(self, head):
        """Run a descriptor chain to completion and report how it ended.

        *§3.2 group 3, end-to-end.* Completes when a descriptor with EOL set has
        been processed -- the engine stops, sets DONE in CHn_CSR, and raises the
        channel interrupt. Waits for EOL DONE, plus optional intermediate wakes:
        RUNNING has internal structure here, being per-descriptor progress inside
        one outstanding request.

        The four-step arming procedure of §3.3 lives in ``transfer_list_start()``,
        along with the note about which configuration a descriptor does NOT carry
        and must therefore come from a prior ``configure_channel()``.

        Unlike ``transfer_single()`` this completion is unconditional: ARS is
        documented as meaningless and ignored with external descriptors (§3.3). Two
        end-to-end operations differing only in completion contract is why neither
        subsumes the other -- and the difference is entirely in the arming half, not
        in the wait, which is why both share one ``wait_completion()``.

        :param head: head of the descriptor chain, as returned when the list was
                     built; must be reachable from interface 0
        """
        self.transfer_list_start(head)
        return self.wait_completion()

    def stop_channel(self):
        """Abort whatever is running on this channel and wait for the abort to land.

        *§3.2 group 1, end-to-end.* Completes when STOP has been written, the
        channel has aborted, ERR is set, and the error interrupt (if enabled) has
        been raised. Waits for channel ERR -- an abort path that completes the SAME
        outstanding request from a second entry point.

        An abort is reported as an ERROR, not as a clean stop. Note the consequence
        for the scenario layer: the aborted ``transfer_single()`` also returns, with
        ``WB_DMA_ERROR``. Two end-to-end operations complete off one event.

        **It has its own loop rather than calling** ``wait_completion()``. By
        definition it aborts a transfer that is still running, so it violates the
        one-operation-per-channel rule that makes the polling read safe.
        ``stop_channel_start()`` claims no token, so this function holds none -- and
        ``wait_completion()`` ends by RELEASING one, which would take the aborted
        transfer's. Hence the loop below: identical to ``wait_completion()``'s
        except that it does not touch the guard. The duplication is five lines and
        it is the honest shape; a "do not release" flag would hide the one place in
        this model where two operations legitimately share a channel.

        See ``stop_channel_start()`` for what that sharing costs -- which read
        consumes the ERR is not determined by this model -- and for open item §6.5.
        """
        status = 0
        self.stop_channel_start()
        # wait_completion()'s loop, minus the guard release. See above.
        while True:
            status = self.probe_status()
            if status != 2:
                break
            self.wait_hint()
        return status

    def check_completion(self):
        """Poll whether the operation running on this channel has finished.

        The non-blocking half of every end-to-end operation, present on every
        profile -- this is what firmware polls. Completes immediately: one
        register read, one answer. It never suspends and never spins; the caller
        supplies the loop.

        **The contract is narrower than it looks.**

        1. An operation must have been STARTED on this channel, by one of
           ``transfer_single_start()`` or ``transfer_list_start()``.
        2. Once this returns anything other than ``WB_DMA_PENDING``, the operation
           is over. DO NOT CALL AGAIN until the next ``*_start()``.

        Both rules exist because reading CHn_CSR is destructive: ERR and the three
        interrupt-source bits are read-to-clear, so this call CONSUMES the
        completion it reports. A second call after DONE does not re-report DONE --
        it reads a channel whose status has already been taken and answers PENDING
        forever. That failure is invisible from the device side, because a stale
        read and a live one look identical.

        **How the guard works.** :pss:field:`inflight` holds one token for the
        life of an operation. This takes it, reads, and puts it back only if the
        answer was PENDING:

        ``try_get`` fails
            Rule 1 or rule 2 has been broken. Report it.
        ``WB_DMA_PENDING``
            Restore the token; the operation continues.
        ``WB_DMA_DONE`` / ``WB_DMA_ERROR``
            Leave it taken; the operation is over.

        Take-and-restore rather than a peek because ``channel_c`` has no peek
        (§21.9.1 offers get/put/try_get/try_put and nothing else). It is safe
        under the one-operation-per-channel rule that already governs this model:
        the polling thread is the only one entitled to that token.

        .. note::
           "Report it" is weaker than it should be. This stdlib has no runtime
           ``error()``, so a violation is a message at ``NONE`` verbosity -- the
           loudest thing available, and still only a message. A runtime that wants
           it fatal should bind the model's message sink to one; the text is
           deliberately distinctive so it can be matched. Returning
           ``WB_DMA_ERROR`` was considered and rejected: it would make a
           PROGRAMMING error indistinguishable from a DEVICE error. It answers
           PENDING instead, because the state needed for an honest answer was
           consumed by whoever broke the rule.
        """
        status = 0
        tok = [0]   # PSS local, held in a cell: channel try_get output
        if not (self.inflight.try_get(tok)):
            self._bus.message('wb_dma: check_completion() with no operation in progress on this channel -- either no *_start() was called, or a previous completion was already consumed')
            return 2
        status = self.probe_status()
        if status == 2:
            # Still running: hand the token back. try_put cannot fail -- this
            # is the only holder, and it was just emptied.
            self.inflight.try_put(tok[0])
        return status

    def configure_channel(self, cfg):
        """Program a channel's registers from a config, without arming it.

        *§3.2 group 1, configuration.* Completes when CHn_SZ / A0 / AM0 / A1 /
        AM1 and the RW bits of CHn_CSR reflect ``cfg``; the channel is NOT
        enabled. Waits for nothing -- straight-line stores, no driver state,
        callable from any context including with a lock held.

        Kept alongside ``transfer_single()``, which takes the same config and
        subsumes this for the common case, for exactly one reason:
        ``transfer_list()`` needs CHK_SZ programmed BEFORE the chain is armed
        (§3.3), and a descriptor carries no chunk size.

        The CSR is written whole rather than read-modify-written, because at this
        point nothing is running on the channel and a read would consume the
        read-to-clear status bits for no reason.

        :param cfg: what to program; capability-gated fields are skipped when the
                    channel was built without the capability
        """
        sz = wb_dma_sz_s()
        csr = wb_dma_csr_s()
        self.regs_adr0_write_val(cfg.src)
        self.regs_am0_write_val(cfg.src_mask)
        self.regs_adr1_write_val(cfg.dst)
        self.regs_am1_write_val(cfg.dst_mask)
        sz.tot_sz = cfg.tot_sz
        sz.chk_sz = cfg.chk_sz
        self.regs_sz_write(sz)
        # CH_EN is what arms the channel, so it must not ride along with the
        # configuration write.
        csr.ch_en = 0
        csr.src_sel = ((cfg.src_if) & 0x1)
        csr.dst_sel = ((cfg.dst_if) & 0x1)
        csr.inc_src = cfg.inc_src
        csr.inc_dst = cfg.inc_dst
        csr.mode = ((cfg.mode) & 0x1)
        csr.prio = cfg.prio
        csr.sz_wb = cfg.sz_wb
        # Capability-gated. Hardware silently ignores these on a channel built
        # without the capability, so decline rather than pretend they took.
        if self.caps.ars:
            csr.ars = cfg.auto_restart
            csr.rest_en = cfg.hw_restart_en
        csr.ine_done = cfg.int_on_done
        csr.ine_err = cfg.int_on_err
        csr.ine_chk_done = cfg.int_on_chunk
        self.regs_csr_write(csr)

    def probe_status(self):
        """Decode one read of CHn_CSR into a status. The unguarded primitive both
        layers are built from.

        Not an operation, and not the API: no in-progress guard, no blocking, no
        loop. It exists because the guard and the decode are separable concerns
        and exactly one caller needs the decode without the guard.

        ``check_completion()``
            Guard plus this. The non-blocking API; firmware calls it.

        ``wait_completion()``
            This, in a loop, under a wake. The guard would be wrong inside a loop
            -- it is claimed once by the ``*_start()`` and released once by the
            operation that started it, not taken and put back on every poll.

        ``stop_channel()``
            This, in a loop, holding no token. Stop is the documented exemption
            from the one-operation-per-channel rule, so it has none to release.

        ERR is tested before DONE because the two are not exclusive: an aborted
        transfer can retire with both set, and a stop that lands on an
        already-completed channel certainly does. Reporting ERROR is the
        conservative reading -- a scenario that expected DONE learns something
        went wrong, where the reverse order would hide it.

        .. warning::
           Callers outside this component should use ``check_completion()``. PSS
           has no visibility control, so this cannot be enforced -- but reaching
           past the guard opts out of the only detector for the read-to-clear
           hazard, and the read is a side effect every time.
        """
        csr = wb_dma_csr_s()
        csr = self.regs_csr_read()
        if csr.err == 1:
            return 1
        if csr.done == 1:
            return 0
        return 2

    def set_auto_restart(self, enable):
        """Set or clear the channel's auto-restart bit.

        *§3.2 group 1, configuration.* Completes when ARS has been updated; waits
        for nothing.

        Distinct from ``configure_channel()`` because clearing ARS mid-flight is
        the documented way to terminate an auto-restarting channel (§3.2.1),
        invoked on its own against a live channel from a parallel scenario branch.
        Rewriting the whole register bank to do that would be wrong.

        It is therefore the TERMINATING EVENT for an auto-restarting
        ``transfer_single()``: once ARS is clear, the in-flight iteration retires
        and DONE asserts.

        .. warning::
           A read-modify-write against a live channel, so it shares the hazard
           described on ``stop_channel_start()``: the read consumes any pending
           read-to-clear status. Enabling ARS before arming is unaffected;
           disabling it mid-flight is the exposed case.

        :param enable: 1 to auto-restart on completion, 0 to stop after the
                       current iteration
        """
        # Silently ignored by hardware without ARS, so decline rather than
        # pretend.
        if not (self.caps.ars):
            return
        self.regs_csr_write_val_masked(64, (((enable) & 0xffffffff) & 1) << 6)

    def set_software_pointer(self, ptr, enable):
        """Publish how far a software reader has drained a FIFO in memory.

        *§3.2 group 1, configuration.* Completes when CHn_SWPTR has been updated
        -- a channel stalled on the old pointer may resume as a side effect.
        Waits for nothing.

        The consumer side of a FIFO in memory (§3.5): the DMA stalls rather than
        overrun the software reader, and publishing a new pointer un-stalls it. So
        this is invoked repeatedly during a live transfer, always concurrent with
        a ``transfer_single()``.

        Note what that implies about scope: the FIFO's DATA is read on the test
        writer's own memory path. This operation only publishes how far that
        reader has got.

        Requires ``caps.cbuf``, and only means anything with a circular-buffer
        address mask programmed on the same channel.

        :param ptr:    the new software pointer
        :param enable: whether the pointer is honoured at all
        """
        sw = wb_dma_swptr_s()
        if not (self.caps.cbuf):
            return
        # A whole-register write, not a read-modify-write: both fields are
        # supplied and this register carries no status to preserve. That also
        # keeps it clear of the CSR read-to-clear hazard, which matters because
        # this runs against a live channel.
        sw.ptr = ptr
        sw.en = enable
        self.regs_swptr_write(sw)

    def stop_channel_start(self):
        """Write STOP to abort whatever is running on this channel, and return.

        *§3.2 group 1.* The non-blocking half of ``stop_channel()``, present on
        every profile. Completes when STOP has been written -- the abort itself
        has not necessarily happened yet. Waits for nothing.

        An abort is reported as an ERROR, not as a clean stop: the device sets ERR
        on a STOP write (§3.2.2). That is carried into the contract verbatim.

        **This claims no** :pss:field:`inflight` **token, deliberately.** By
        definition it aborts a transfer that is still running, so the channel it
        targets is already holding one. Claiming would report the one case the
        model explicitly permits as a violation. Stop is the documented exemption
        from the one-operation-per-channel rule, and the exemption is now visible
        in the code rather than only in a comment.

        **Two consequences a firmware caller must know.**

        The ``write_field`` below IS a read-modify-write: the LRM defines the
        field-wise write as one (§21.14.1), so the CHn_CSR read is there even
        though the call no longer spells it out, and it still clears ERR and the
        interrupt sources. That read happens BEFORE STOP is written, so it can
        only consume status that was already there -- the abort's own ERR is set
        afterwards and is still seen by the aborted transfer's poll. What it can
        lose is a completion that landed in the instant before the abort.

        Who reports the abort is NOT determined by this model. The aborted
        transfer polls the same CSR, and whichever read lands first consumes the
        ERR. On the non-blocking profile the loser's ``check_completion()``
        answers PENDING forever -- a firmware hang rather than an action that does
        not retire.

        There is no ``check_completion()`` pairing for stop: it holds no token, so
        it has nothing to poll with. A caller aborts, then keeps polling the
        TRANSFER it aborted, which is the operation that owns the completion.

        .. note::
           Open question (§6.5): is write-1-to-STOP acknowledged before or after
           the current WISHBONE cycle retires? That decides whether an abort can
           be considered delivered on return, which matters post-silicon.
        """
        self.regs_csr_write_val_masked(512, 512)

    def transfer_list_start(self, head):
        """Point a channel at a descriptor list and arm it, returning with the chain
        running.

        *§3.2 group 3.* The non-blocking half of ``transfer_list()``, present on
        every profile. Completes when the channel points at the list, external
        descriptors are enabled, and the channel is armed. Waits for nothing.

        §3.3's four-step arming procedure IS this function's body, except step 2
        (chunk size), which must come from a prior ``configure_channel()`` because
        it outlives any single descriptor. A descriptor carries only src, dst,
        tot_sz, the increment flags, the interface selects and EOL; mode,
        priority, ARS, the address masks and CHK_SZ stay whatever the channel
        registers hold.

        Unlike ``transfer_single_start()``, this one always has a completion: ARS
        is documented as meaningless and ignored with external descriptors (§3.3),
        so ``check_completion()`` is guaranteed to answer DONE or ERROR
        eventually. Two end-to-end operations differing only in completion
        contract is why neither subsumes the other -- and the difference was never
        in the wait.

        Requires ``caps.ed``. Unlike the other capability-gated operations this
        reports rather than returning quietly, because it has a completion
        contract: a silent return would leave the caller waiting for a chain that
        was never armed.

        :param head: head of the descriptor chain; must be reachable from
                     interface 0
        """
        # Checked before claiming, so a declined start leaves no token behind.
        if not (self.caps.ed):
            self._bus.message('wb_dma: transfer_list_start() on a channel built without external-descriptor support (caps.ed)')
            return
        if not (self.inflight.try_put(1)):
            self._bus.message('wb_dma: transfer_list_start() on a channel that already has an operation in progress')
            return
        # Step 1: point the channel at the head of the list. The DMA fetches
        # descriptors from interface 0 regardless of which interface the data
        # moves on, so `head` must be IF0-reachable.
        self.regs_desc_write_val(((head) & 0xffffffff))
        # Steps 3 and 4, in that order and as TWO WRITES, deliberately: the
        # device requires them separate, and write_fields({"use_ed","ch_en"},
        # {1,1}) would coalesce them into one bus read-modify-write -- that is
        # what the plural form is for. Each of these is still a
        # read-modify-write in its own right (§21.14.1).
        self.regs_csr_write_val_masked(128, 128)
        self.regs_csr_write_val_masked(1, 1)

    def transfer_single_start(self, cfg):
        """Program a channel and arm it, returning with the transfer running.

        *§3.2 group 1.* The non-blocking half of ``transfer_single()``, present on
        every profile. Completes when the channel is programmed and armed -- NOT
        when the transfer has moved anything. Waits for nothing.

        Program, arm, return. The caller then polls ``check_completion()`` until
        it answers something other than PENDING, or calls ``transfer_single()``,
        which is exactly this plus the wait. All of the device knowledge is here;
        the end-to-end layer adds only the loop. That is why a SystemVerilog
        regression that never calls this directly still tests it.

        **Two callers' obligations this signature does not encode.**

        ``mode == WB_DMA_HW_HANDSHAKE``: the transfer cannot complete on its own.
        Something must be calling ``request_chunk()`` on the matching
        ``wb_dma_hs_c`` concurrently (§2.2). Splitting arm from wait does not help
        here -- the missing thing is a second initiator, not a second thread.

        ``cfg.auto_restart``: the transfer has NO completion event. CSR bit 11
        sets DONE only once ARS is clear, so nothing this function starts will
        ever make ``check_completion()`` answer DONE. Someone must clear ARS
        (``set_auto_restart(0)``) or abort the channel (``stop_channel_start()``).
        In the end-to-end layer that is a thread that never returns; here it is a
        loop that never exits, which is a firmware hang rather than a stalled PSS
        action. Same defect, less visible.

        Claims :pss:field:`inflight` FIRST, before touching a register, so a start
        that would be the second on a live channel is reported without having
        corrupted the configuration of the first.

        :param cfg: what to program before arming
        """
        if not (self.inflight.try_put(1)):
            self._bus.message('wb_dma: transfer_single_start() on a channel that already has an operation in progress')
            return
        self.configure_channel(cfg)
        # Arm. write_field is a read-modify-write (§21.14.1), so the
        # configuration just written survives; the read clears the read-to-clear
        # status bits, harmless here because the channel has not started yet.
        self.regs_csr_write_val_masked(1, 1)

    def wait_hint(self):
        """Wait until the device may have progressed.

        The wait PRIMITIVE: the one function in this model whose body differs
        between execution targets, and the only thing
        ``wb_dma_cfg_pkg::HAS_EVENT_WAIT`` gates.

        **Contract: return when the device MAY have progressed.** Not "when it
        has" -- this reports nothing and decides nothing. Every caller is a loop
        that re-reads CHn_CSR afterwards and tests its own condition, so a
        spurious return costs one register read and a late return costs latency.
        Neither is a defect.

        This is the seam that lets the OPERATION SURFACE be profile-independent.
        The two ways to wait have different requirements:

        ``wake.get()``
            Suspend until someone posts. Needs an event source (``notify_irq()``,
            hence configured interrupt routing) and a runtime that can suspend a
            caller. Costs nothing while waiting.

        ``yield``
            Spin. Needs NOTHING -- every target can spin, including a bare-metal
            single-threaded one. Costs the bus a read per iteration and, on a
            threaded target, whatever the scheduler charges.

        Only the first is a capability, so that is what the flag asks about and
        this is where the answer is consumed. Every operation above it is written
        once and compiles on both. See ``docs/op-model-c-embedded-design.md``
        §5.4 and ``docs/target-cfg-contract.md``.

        .. warning::
           ``yield`` is a hint to the SCHEDULER, not to the device, and a backend
           spends it however its target charges for waiting. It must NOT be
           implemented as a wait on this device's interrupt: that would
           reintroduce the routing prerequisite this branch exists to avoid, and
           would deadlock the one caller that has no interrupt to wait for. The
           contract is stated in full in ``docs/op-model-export-design.md`` §4.4.
        """
        # No event to wait on, so spin. The caller re-reads CHn_CSR on every
        # iteration; this only decides what the gap between reads costs, and
        # the target decides that.
        # yield: nothing to yield to on this target
        pass


class WbDma(object):
    """The MMIO operation model for the WISHBONE DMA/Bridge core (§3,
    ``dma_mmio_c`` in the operation-model document).

    This component holds the engine-GLOBAL operations -- PAUSE, interrupt
    routing, descriptor authoring. Everything per-channel is on
    :pss:comp:`wb_dma_ch_c`, an array of which it owns.

    Scope (§1): everything the processor reaches by load/store. The per-channel
    hardware handshake's participant is the PERIPHERAL, so its model sits with
    the environment (``tests/pss/wb_dma_hs_c.pss``). The WISHBONE masters are
    device-driven and out of scope; so is descriptor FETCHING, though descriptor
    AUTHORING is here, because the processor initiates it.

    Deliberately absent:

    * **bulk buffer access** -- the test writer already has a path to memory
      (``read32``/``write32``); filling a source region and checking a
      destination region are not operations of this model.
    * **bus-error injection** -- it belongs to whatever component can drive
      ``err_i``. A DMA-error-reaction test is a composition of two operation
      models, not a wider version of this one (§5.1).
    * **bridge_access** -- the pass-through path is reachable only with a target
      on the far interface; omitted by review decision.
    """

    def __init__(self, bus, base):
        self._bus = bus
        self._base = base
        self.num_ch = 4
        self.pri_levels = 4
        self.ch = [None] * 4
        self._base = base
        for i in range(4):
            self.ch[i] = WbDmaCh(self._bus, i, (base + (0x20 + 0x20 * i)))

    # ----- Register accessors, offsets folded. -----
    def regs_csr_addr(self):
        """Address of `regs.csr`."""
        return self._base + 0x0
    def regs_csr_read_val(self):
        return self._bus.read32(self.regs_csr_addr())
    def regs_csr_write_val(self, value):
        self._bus.write32(self.regs_csr_addr(), value)
    def regs_csr_read(self):
        return wb_dma_gcsr_s.unpack(self.regs_csr_read_val())
    def regs_csr_write(self, value):
        self.regs_csr_write_val(value.pack())
    def regs_csr_write_val_masked(self, mask, val):
        cur = self.regs_csr_read_val()
        self.regs_csr_write_val((cur & ~mask) | (val & mask))
    def regs_int_msk_a_addr(self):
        """Address of `regs.int_msk_a`."""
        return self._base + 0x4
    def regs_int_msk_a_read_val(self):
        return self._bus.read32(self.regs_int_msk_a_addr())
    def regs_int_msk_a_write_val(self, value):
        self._bus.write32(self.regs_int_msk_a_addr(), value)
    def regs_int_msk_a_read(self):
        return wb_dma_intmsk_s.unpack(self.regs_int_msk_a_read_val())
    def regs_int_msk_a_write(self, value):
        self.regs_int_msk_a_write_val(value.pack())
    def regs_int_msk_a_write_val_masked(self, mask, val):
        cur = self.regs_int_msk_a_read_val()
        self.regs_int_msk_a_write_val((cur & ~mask) | (val & mask))
    def regs_int_msk_b_addr(self):
        """Address of `regs.int_msk_b`."""
        return self._base + 0x8
    def regs_int_msk_b_read_val(self):
        return self._bus.read32(self.regs_int_msk_b_addr())
    def regs_int_msk_b_write_val(self, value):
        self._bus.write32(self.regs_int_msk_b_addr(), value)
    def regs_int_msk_b_read(self):
        return wb_dma_intmsk_s.unpack(self.regs_int_msk_b_read_val())
    def regs_int_msk_b_write(self, value):
        self.regs_int_msk_b_write_val(value.pack())
    def regs_int_msk_b_write_val_masked(self, mask, val):
        cur = self.regs_int_msk_b_read_val()
        self.regs_int_msk_b_write_val((cur & ~mask) | (val & mask))
    def regs_int_src_a_addr(self):
        """Address of `regs.int_src_a`."""
        return self._base + 0xc
    def regs_int_src_a_read_val(self):
        return self._bus.read32(self.regs_int_src_a_addr())
    def regs_int_src_a_read(self):
        return wb_dma_intsrc_s.unpack(self.regs_int_src_a_read_val())
    def regs_int_src_b_addr(self):
        """Address of `regs.int_src_b`."""
        return self._base + 0x10
    def regs_int_src_b_read_val(self):
        return self._bus.read32(self.regs_int_src_b_addr())
    def regs_int_src_b_read(self):
        return wb_dma_intsrc_s.unpack(self.regs_int_src_b_read_val())
    def regs_bank_csr_addr(self, i0):
        """Address of `regs.bank.csr`."""
        return self._base + 0x20 + i0 * 0x20
    def regs_bank_csr_read_val(self, i0):
        return self._bus.read32(self.regs_bank_csr_addr(i0))
    def regs_bank_csr_write_val(self, i0, value):
        self._bus.write32(self.regs_bank_csr_addr(i0), value)
    def regs_bank_csr_read(self, i0):
        return wb_dma_csr_s.unpack(self.regs_bank_csr_read_val(i0))
    def regs_bank_csr_write(self, i0, value):
        self.regs_bank_csr_write_val(i0, value.pack())
    def regs_bank_csr_write_val_masked(self, i0, mask, val):
        cur = self.regs_bank_csr_read_val(i0)
        self.regs_bank_csr_write_val(i0, (cur & ~mask) | (val & mask))
    def regs_bank_sz_addr(self, i0):
        """Address of `regs.bank.sz`."""
        return self._base + 0x24 + i0 * 0x20
    def regs_bank_sz_read_val(self, i0):
        return self._bus.read32(self.regs_bank_sz_addr(i0))
    def regs_bank_sz_write_val(self, i0, value):
        self._bus.write32(self.regs_bank_sz_addr(i0), value)
    def regs_bank_sz_read(self, i0):
        return wb_dma_sz_s.unpack(self.regs_bank_sz_read_val(i0))
    def regs_bank_sz_write(self, i0, value):
        self.regs_bank_sz_write_val(i0, value.pack())
    def regs_bank_sz_write_val_masked(self, i0, mask, val):
        cur = self.regs_bank_sz_read_val(i0)
        self.regs_bank_sz_write_val(i0, (cur & ~mask) | (val & mask))
    def regs_bank_adr0_addr(self, i0):
        """Address of `regs.bank.adr0`."""
        return self._base + 0x28 + i0 * 0x20
    def regs_bank_adr0_read_val(self, i0):
        return self._bus.read32(self.regs_bank_adr0_addr(i0))
    def regs_bank_adr0_write_val(self, i0, value):
        self._bus.write32(self.regs_bank_adr0_addr(i0), value)
    def regs_bank_adr0_read(self, i0):
        return wb_dma_addr_s.unpack(self.regs_bank_adr0_read_val(i0))
    def regs_bank_adr0_write(self, i0, value):
        self.regs_bank_adr0_write_val(i0, value.pack())
    def regs_bank_adr0_write_val_masked(self, i0, mask, val):
        cur = self.regs_bank_adr0_read_val(i0)
        self.regs_bank_adr0_write_val(i0, (cur & ~mask) | (val & mask))
    def regs_bank_am0_addr(self, i0):
        """Address of `regs.bank.am0`."""
        return self._base + 0x2c + i0 * 0x20
    def regs_bank_am0_read_val(self, i0):
        return self._bus.read32(self.regs_bank_am0_addr(i0))
    def regs_bank_am0_write_val(self, i0, value):
        self._bus.write32(self.regs_bank_am0_addr(i0), value)
    def regs_bank_am0_read(self, i0):
        return wb_dma_amask_s.unpack(self.regs_bank_am0_read_val(i0))
    def regs_bank_am0_write(self, i0, value):
        self.regs_bank_am0_write_val(i0, value.pack())
    def regs_bank_am0_write_val_masked(self, i0, mask, val):
        cur = self.regs_bank_am0_read_val(i0)
        self.regs_bank_am0_write_val(i0, (cur & ~mask) | (val & mask))
    def regs_bank_adr1_addr(self, i0):
        """Address of `regs.bank.adr1`."""
        return self._base + 0x30 + i0 * 0x20
    def regs_bank_adr1_read_val(self, i0):
        return self._bus.read32(self.regs_bank_adr1_addr(i0))
    def regs_bank_adr1_write_val(self, i0, value):
        self._bus.write32(self.regs_bank_adr1_addr(i0), value)
    def regs_bank_adr1_read(self, i0):
        return wb_dma_addr_s.unpack(self.regs_bank_adr1_read_val(i0))
    def regs_bank_adr1_write(self, i0, value):
        self.regs_bank_adr1_write_val(i0, value.pack())
    def regs_bank_adr1_write_val_masked(self, i0, mask, val):
        cur = self.regs_bank_adr1_read_val(i0)
        self.regs_bank_adr1_write_val(i0, (cur & ~mask) | (val & mask))
    def regs_bank_am1_addr(self, i0):
        """Address of `regs.bank.am1`."""
        return self._base + 0x34 + i0 * 0x20
    def regs_bank_am1_read_val(self, i0):
        return self._bus.read32(self.regs_bank_am1_addr(i0))
    def regs_bank_am1_write_val(self, i0, value):
        self._bus.write32(self.regs_bank_am1_addr(i0), value)
    def regs_bank_am1_read(self, i0):
        return wb_dma_amask_s.unpack(self.regs_bank_am1_read_val(i0))
    def regs_bank_am1_write(self, i0, value):
        self.regs_bank_am1_write_val(i0, value.pack())
    def regs_bank_am1_write_val_masked(self, i0, mask, val):
        cur = self.regs_bank_am1_read_val(i0)
        self.regs_bank_am1_write_val(i0, (cur & ~mask) | (val & mask))
    def regs_bank_desc_addr(self, i0):
        """Address of `regs.bank.desc`."""
        return self._base + 0x38 + i0 * 0x20
    def regs_bank_desc_read_val(self, i0):
        return self._bus.read32(self.regs_bank_desc_addr(i0))
    def regs_bank_desc_write_val(self, i0, value):
        self._bus.write32(self.regs_bank_desc_addr(i0), value)
    def regs_bank_desc_read(self, i0):
        return wb_dma_descptr_s.unpack(self.regs_bank_desc_read_val(i0))
    def regs_bank_desc_write(self, i0, value):
        self.regs_bank_desc_write_val(i0, value.pack())
    def regs_bank_desc_write_val_masked(self, i0, mask, val):
        cur = self.regs_bank_desc_read_val(i0)
        self.regs_bank_desc_write_val(i0, (cur & ~mask) | (val & mask))
    def regs_bank_swptr_addr(self, i0):
        """Address of `regs.bank.swptr`."""
        return self._base + 0x3c + i0 * 0x20
    def regs_bank_swptr_read_val(self, i0):
        return self._bus.read32(self.regs_bank_swptr_addr(i0))
    def regs_bank_swptr_write_val(self, i0, value):
        self._bus.write32(self.regs_bank_swptr_addr(i0), value)
    def regs_bank_swptr_read(self, i0):
        return wb_dma_swptr_s.unpack(self.regs_bank_swptr_read_val(i0))
    def regs_bank_swptr_write(self, i0, value):
        self.regs_bank_swptr_write_val(i0, value.pack())
    def regs_bank_swptr_write_val_masked(self, i0, mask, val):
        cur = self.regs_bank_swptr_read_val(i0)
        self.regs_bank_swptr_write_val(i0, (cur & ~mask) | (val & mask))

    # ----- Sub-component access. -----
    def ch_size(self):
        return 4
    def ch_at(self, i):
        return self.ch[i]

    def configure_interrupt_routing(self, bank, channel_mask):
        """Route a set of channels to one of the two aggregate interrupt outputs.

        *§3.2 group 2, configuration.* Completes when INT_MSK_A/B has been
        updated; waits for nothing.

        The two banks are independent aggregate outputs, and a channel may be
        routed to both. ``channel_mask`` stays a bit vector rather than becoming
        a channel list because it genuinely is one: bit N routes channel N.

        **A hard prerequisite for every end-to-end operation, enforced by
        deadlock** on the event-wait profile. Completion IS the interrupt, so a
        test that routes nothing raises no interrupt, nothing calls
        ``notify_irq()``, and the first wait blocks forever. Routing at least one
        channel in a bank keeps the whole test alive, because ``notify_irq()``
        posts to every channel blind. That is intended: a hang is a more honest
        result than a green test whose completion path was never exercised.

        :param bank:         which aggregate output to program
        :param channel_mask: bit N routes channel N
        """
        vec = wb_dma_intmsk_s()
        vec.ch = channel_mask
        _subject = bank
        if _subject == 0:
            self.regs_int_msk_a_write(vec)
        elif _subject == 1:
            self.regs_int_msk_b_write(vec)
        else:
            raise ValueError('configure_interrupt_routing: unmatched match subject' + " (%r)" % (_subject,))

    def pause_engine(self, pause):
        """Pause or un-pause the whole engine, and wait until it has taken effect.

        *§3.2 group 2, configuration.* Global, not per-channel.

        Completes when a readback of ``CSR.PAUSE`` matches the requested value.
        The engine only pauses after the CURRENT transfer completes, so the write
        and the state change are NOT simultaneous -- which is the entire reason
        this is an operation rather than a register write, and the clearest small
        illustration of the blocking rule: the operation is not done when the
        store retires.

        It waits for that readback, and is the one wait in this model with no
        interrupt behind it -- in a real driver, a retry or timer loop rather than
        an ISR wake. The global CSR is not read-to-clear, so unlike the channel
        CSR this poll is genuinely side-effect-free and may run any number of
        times.

        :param pause: 1 to pause, 0 to resume
        """
        gcsr = wb_dma_gcsr_s()
        gcsr.pause = pause
        self.regs_csr_write(gcsr)
        while True:
            gcsr = self.regs_csr_read()
            if gcsr.pause == pause:
                break
            # yield: nothing to yield to on this target

    def read_descriptor_residual(self, desc_ptr):
        """Read back how much of a descriptor's transfer actually moved.

        *§3.2 group 3, configuration.* Completes when DESC_CSR has been loaded
        back from memory and decoded; waits for nothing.

        A device-specific decode, not a memory service -- the same rationale that
        keeps ``write_descriptor()`` in this model. Only meaningful when SZ_WB is
        set in the channel CSR and the descriptor was cut short by
        ``skip_to_next_descriptor()``. This is how software learns how much of a
        variable-length payload actually moved, which is the whole point of §3.9.

        .. note::
           Open question (§6.1): §3.9 says the remaining BYTES are written back,
           into a field Table 1 defines as a 12-bit WORD count. One of the two is
           wrong. This returns the raw field and lets the caller decide.

        :param desc_ptr: the descriptor whose control word is read back
        """
        desc_csr = 0
        desc_csr = self._bus.read32(desc_ptr)
        return ((desc_csr) & 0xfff)

    def write_descriptor(self, at, prev, desc):
        """Write one external descriptor into memory and link it to its predecessor.

        *§3.2 group 3, configuration.* Completes when the descriptor is in memory
        at ``at``, terminated (DESC_NEXT zero), and ``prev`` -- if there is one --
        points at it. Waits for nothing. Returns a handle to the slot immediately
        after ``at``, i.e. the natural place for the next descriptor, so a caller
        can build a list in place one link at a time.

        This is DEVICE KNOWLEDGE written through a memory path, not a path to
        memory: the next-pointer linkage and the EOL rule are the operation, the
        layout is declared by :pss:struct:`wb_dma_desc_s`, and ``write32`` is
        merely how it lands. That is what makes it an operation where a generic
        ``write_buffer()`` would not be.

        ``at`` must be reachable from interface 0: descriptors are fetched from
        IF0 regardless of which interface the DATA moves on (§3.3).

        :param at:   where this descriptor goes
        :param prev: the descriptor to link from; null/zero means "head of list"
        :param desc: the descriptor contents; the caller's copy is not modified
        """
        d = wb_dma_desc_s()
        csr_word = 0
        # Deep copy: `desc` is the caller's struct (aggregates pass by handle)
        # and we terminate this link ourselves.
        d = desc
        d.next = 0
        # This block is one call -- write_struct(at, d) -- once read_struct /
        # write_struct land; they are commented out of the front end's
        # addr_reg_pkg ("TODO: generic type"). wb_dma_desc_s already declares
        # the packed layout, so nothing here adds information.
        csr_word = ((d.csr.tot_sz) & 0xffffffff)
        csr_word |= ((d.csr.dst_sel) & 0xffffffff) << 16
        csr_word |= ((d.csr.src_sel) & 0xffffffff) << 17
        csr_word |= ((d.csr.inc_dst) & 0xffffffff) << 18
        csr_word |= ((d.csr.inc_src) & 0xffffffff) << 19
        csr_word |= ((d.csr.eol) & 0xffffffff) << 20
        self._bus.write32(at, csr_word)
        self._bus.write32((at + 4), d.adr0)
        self._bus.write32((at + 8), d.adr1)
        self._bus.write32((at + 12), d.next)
        # Extend the list. The check is on the resolved address rather than a
        # handle comparison, because an address handle is opaque and not
        # usefully comparable.
        if prev != 0:
            self._bus.write32((prev + 12), ((at) & 0xffffffff))
        return (at + 16)
