
class Factory(object):
    """Provides access to objects used in parsing and linking PSS code"""
    def getAstFactory(self) -> 'Factory': ...
    def getDebugMgr(self): ...
    def loadStandardLibrary(self, 
            ast_builder : 'AstBuilder',
            glbl_scope : 'ast.GlobalScope'): ...

    @staticmethod
    def inst() -> 'Factory': ...
