"""Tests for the golden-snapshot harness itself.

The harness is what later phases lean on when they claim to preserve output
byte for byte, so the harness needs its own gate: a snapshot mechanism that
silently passes is worse than no snapshot at all, because it is *believed*.

Each test here corresponds to one property the plan asks for (P0.T1): version
normalisation, order sensitivity, and that a corrupted expectation is caught.
"""
import pytest

from . import golden_util as gu


pytestmark = pytest.mark.golden


# -- normalisation ----------------------------------------------------------

def test_version_is_normalised_out():
    a = "/* Generated by pssc 0.1.0 (c-progseq) -- do not edit. */"
    b = "/* Generated by pssc 9.9.9.dev1 (c-progseq) -- do not edit. */"
    assert gu._normalise(a) == gu._normalise(b)
    assert "<VERSION>" in gu._normalise(a)


def test_normalisation_does_not_swallow_the_rest_of_the_banner():
    """A blunter regex (whole line) would hide the target name and the flags,
    which is exactly the kind of drift a snapshot is for."""
    line = ("/* Generated by pssc 0.1.0 (c-progseq) -- do not edit. */")
    assert "(c-progseq) -- do not edit." in gu._normalise(line)


def test_normalisation_leaves_ordinary_text_alone():
    text = "uint32_t v = pssc_r32(pssc_bus(s), 0x100);"
    assert gu._normalise(text) == text


# -- manifest ---------------------------------------------------------------

def test_manifest_records_copied_core_headers_as_pointers(tmp_path):
    """A file copied verbatim out of `share/` is stored as a pointer, not as a
    second copy -- see golden_util's module docstring."""
    src = gu.SHARE_ROOT / "c" / "pssc_mem.h"
    dst = tmp_path / "pssc_mem.h"
    dst.write_bytes(src.read_bytes())
    gen = tmp_path / "wb_dma.h"
    gen.write_text("/* generated */\n")

    manifest = gu.build_manifest([gen, dst], tmp_path)
    assert manifest == ["wb_dma.h", "pssc_mem.h -> share/c/pssc_mem.h"]


def test_manifest_stops_calling_a_modified_core_header_a_copy(tmp_path):
    """The pointer means 'these bytes arrived unmodified'. A target that starts
    rewriting the seam header while copying it must show up as a new file to
    snapshot, not as a pointer that no longer holds."""
    dst = tmp_path / "pssc_mem.h"
    dst.write_text((gu.SHARE_ROOT / "c" / "pssc_mem.h").read_text() + "\n/* patched */\n")
    assert gu.build_manifest([dst], tmp_path) == ["pssc_mem.h"]


# -- checking ---------------------------------------------------------------

@pytest.fixture(scope="module")
def frozen(tmp_path_factory):
    """A real generation of the smallest config, kept for the checks below."""
    cfg = gu.CONFIG_BY_NAME["cpp-virtual"]
    out = tmp_path_factory.mktemp("golden_selftest")
    return cfg, gu.run_config(cfg, out), out


def test_a_fresh_generation_matches_its_snapshot(frozen):
    cfg, paths, out = frozen
    gu.check_golden(cfg, paths, out)


def test_one_corrupted_byte_fails_with_a_readable_diff(frozen, tmp_path):
    cfg, paths, out = frozen
    victim = next(p for p in paths if p.name.endswith(".hpp"))
    text = victim.read_text()
    victim.write_text(text.replace("uint32_t", "uint31_t", 1))
    try:
        with pytest.raises(gu.GoldenMismatch) as exc:
            gu.check_golden(cfg, paths, out)
    finally:
        victim.write_text(text)
    msg = str(exc.value)
    assert victim.name in msg
    assert "uint31_t" in msg                    # the diff names the actual change
    assert "regen_golden.py" in msg             # and says what to do about it


def test_reordering_the_output_list_fails(frozen):
    """Content-only comparison would pass here. The order is the compilation
    order a build system consumes."""
    cfg, paths, out = frozen
    assert len(paths) > 1, "config needs >1 file to test ordering"
    with pytest.raises(gu.GoldenMismatch) as exc:
        gu.check_golden(cfg, list(reversed(paths)), out)
    assert "ORDER" in str(exc.value)


def test_a_missing_snapshot_says_how_to_create_it(frozen):
    cfg = gu.Config("no-such-config", "op-model-cpp")
    _, paths, out = frozen
    with pytest.raises(gu.GoldenMismatch) as exc:
        gu.check_golden(cfg, paths, out)
    assert "regen_golden.py no-such-config" in str(exc.value)


# -- the regeneration guard -------------------------------------------------

def test_regeneration_is_gated_on_the_environment(monkeypatch):
    monkeypatch.delenv("PSSC_GOLDEN_REGEN", raising=False)
    assert not gu.regen_allowed()
    monkeypatch.setenv("PSSC_GOLDEN_REGEN", "1")
    assert gu.regen_allowed()


def test_regen_script_refuses_without_the_env_var(monkeypatch, capsys):
    import scripts.regen_golden as regen
    monkeypatch.delenv("PSSC_GOLDEN_REGEN", raising=False)
    assert regen.main([]) == 2
    assert "PSSC_GOLDEN_REGEN=1" in capsys.readouterr().err
