/* pssc_mem.h -- core memory-access seam, IP-independent. Hand-written once.
 *
 * Generated by pssc (c-progseq). This header declares the address type and is
 * included by exactly one link-style seam header (pssc_mem_direct.h,
 * pssc_mem_vtable.h, or pssc_mem_mmio.h), which defines the `static inline`
 * access primitives pssc_w8/16/32/64 and pssc_r8/16/32/64.
 *
 * Every generated register accessor and operation body calls those primitives
 * and is byte-identical across the three link styles; only the seam selected at
 * generation time differs. See design/pss-c-cpp-progseq-gen-design.md (§3.2).
 */
#ifndef PSSC_MEM_H
#define PSSC_MEM_H

#include <stdint.h>

/* PSS addr_handle_t -> 64-bit byte address. */
typedef uint64_t pssc_addr_t;

#endif /* PSSC_MEM_H */
