/* Generated by pssc <VERSION> -- WEAK STUBS. Link this ONLY until the
 * platform side exists.
 *
 * `pssc_message` is stubbed because DOING NOTHING IS A CORRECT IMPLEMENTATION
 * of it: a driver that logs nothing still drives the device correctly. That is
 * the entire test for whether something belongs in this file, and nothing else
 * in the seam passes it.
 *
 * NOT STUBBED, and never will be:
 *
 *   * the memory primitives (pssc_r32/pssc_w32/...). A bus access that silently
 *     succeeds is a driver that reports the device is fine because it never
 *     talked to it -- the single worst failure this generator could produce.
 *     An unresolved symbol at link is the correct outcome.
 *   * model-declared imports (`import target/solve function`). Same rule: an
 *     empty `plat_delay_us` is a delay that does not delay, and the poll loop
 *     above it becomes a spin that can never be right. What each one must do
 *     is stated by the model, not guessable here.
 *
 * WEAK, so a real definition anywhere else in the link wins with no build
 * change and no warning. Under a toolchain with no weak-symbol support this
 * file defines a strong symbol -- so remove it from the link rather than
 * expecting it to be overridden.
 */
#include <stdarg.h>

#if defined(__GNUC__) || defined(__clang__)
#  define PSSC_WEAK __attribute__((weak))
#else
#  define PSSC_WEAK
#endif

PSSC_WEAK void pssc_message(const char *fmt, ...) { (void)fmt; }
