/* Generated by pssc <VERSION> (c-progseq) -- do not edit. */
/* Root component: wb_dma_c; link-style: vtable. */
/* ABI-affecting settings: addr-bits=64, lifecycle=malloc, reg-style=accessors, mem-access=from-link-style, struct-args=value */
/* A caller built with different values above is NOT compatible with this header. */
/* Register value layouts assume little-endian bitfield allocation (gcc/clang, x86/ARM, LP64/LLP64). */
/* Component structs are COMPLETE types: their layout is part of this header's ABI. */
/* Rebuild all callers when the model changes. */
/* NOT ISR-SAFE: the channel members below are read-modify-written without a critical */
/* section, so no function in this header may be called from an interrupt handler */
/* concurrently with foreground code. Define PSSC_CHAN_ENTER/PSSC_CHAN_EXIT (pssc_chan.h) */
/* to lift that restriction. */
#ifndef WB_DMA_H
#define WB_DMA_H

#include <stdint.h>
#include <stdbool.h>
#include "pssc_mem_vtable.h"
#include "pssc_env.h"
#include "pssc_chan.h"

/* ----- Data types used by the export API. ----- */
typedef enum {
    WB_DMA_INT_A = 0,
    WB_DMA_INT_B = 1
} wb_dma_int_bank_t;

typedef enum {
    WB_DMA_DONE = 0,
    WB_DMA_ERROR = 1,
    WB_DMA_PENDING = 2
} wb_dma_status_t;

typedef enum {
    WB_DMA_IF0 = 0,
    WB_DMA_IF1 = 1
} wb_dma_if_t;

typedef enum {
    WB_DMA_SOFTWARE = 0,
    WB_DMA_HW_HANDSHAKE = 1
} wb_dma_mode_t;

typedef struct {
    uint16_t tot_sz;
    uint8_t reserved0;
    uint8_t dst_sel;
    uint8_t src_sel;
    uint8_t inc_dst;
    uint8_t inc_src;
    uint8_t eol;
    uint16_t reserved1;
} wb_dma_desc_csr_t;

typedef struct {
    wb_dma_desc_csr_t csr;
    uint32_t adr0;
    uint32_t adr1;
    uint32_t next;
} wb_dma_desc_t;

typedef struct {
    uint8_t present;
    uint8_t ars;
    uint8_t ed;
    uint8_t cbuf;
} wb_dma_ch_caps_t;

typedef struct {
    uint32_t src;
    uint32_t dst;
    uint32_t src_mask;
    uint32_t dst_mask;
    uint16_t tot_sz;
    uint16_t chk_sz;
    wb_dma_if_t src_if;
    wb_dma_if_t dst_if;
    uint8_t inc_src;
    uint8_t inc_dst;
    wb_dma_mode_t mode;
    uint8_t prio;
    uint8_t auto_restart;
    uint8_t hw_restart_en;
    uint8_t sz_wb;
    uint8_t int_on_done;
    uint8_t int_on_err;
    uint8_t int_on_chunk;
} wb_dma_ch_cfg_t;

/* ----- Register value layouts. ----- */
typedef struct { uint32_t raw; } wb_dma_csr_t;
static inline uint32_t wb_dma_csr_t_ch_en_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 0) & 0x1u); }
static inline void wb_dma_csr_t_ch_en_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 0)) | ((uint32_t)(x & 0x1u) << 0); }
static inline uint32_t wb_dma_csr_t_dst_sel_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 1) & 0x1u); }
static inline void wb_dma_csr_t_dst_sel_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 1)) | ((uint32_t)(x & 0x1u) << 1); }
static inline uint32_t wb_dma_csr_t_src_sel_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 2) & 0x1u); }
static inline void wb_dma_csr_t_src_sel_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 2)) | ((uint32_t)(x & 0x1u) << 2); }
static inline uint32_t wb_dma_csr_t_inc_dst_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 3) & 0x1u); }
static inline void wb_dma_csr_t_inc_dst_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 3)) | ((uint32_t)(x & 0x1u) << 3); }
static inline uint32_t wb_dma_csr_t_inc_src_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 4) & 0x1u); }
static inline void wb_dma_csr_t_inc_src_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 4)) | ((uint32_t)(x & 0x1u) << 4); }
static inline uint32_t wb_dma_csr_t_mode_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 5) & 0x1u); }
static inline void wb_dma_csr_t_mode_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 5)) | ((uint32_t)(x & 0x1u) << 5); }
static inline uint32_t wb_dma_csr_t_ars_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 6) & 0x1u); }
static inline void wb_dma_csr_t_ars_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 6)) | ((uint32_t)(x & 0x1u) << 6); }
static inline uint32_t wb_dma_csr_t_use_ed_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 7) & 0x1u); }
static inline void wb_dma_csr_t_use_ed_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 7)) | ((uint32_t)(x & 0x1u) << 7); }
static inline uint32_t wb_dma_csr_t_sz_wb_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 8) & 0x1u); }
static inline void wb_dma_csr_t_sz_wb_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 8)) | ((uint32_t)(x & 0x1u) << 8); }
static inline uint32_t wb_dma_csr_t_stop_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 9) & 0x1u); }
static inline void wb_dma_csr_t_stop_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 9)) | ((uint32_t)(x & 0x1u) << 9); }
static inline uint32_t wb_dma_csr_t_busy_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 10) & 0x1u); }
static inline void wb_dma_csr_t_busy_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 10)) | ((uint32_t)(x & 0x1u) << 10); }
static inline uint32_t wb_dma_csr_t_done_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 11) & 0x1u); }
static inline void wb_dma_csr_t_done_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 11)) | ((uint32_t)(x & 0x1u) << 11); }
static inline uint32_t wb_dma_csr_t_err_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 12) & 0x1u); }
static inline void wb_dma_csr_t_err_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 12)) | ((uint32_t)(x & 0x1u) << 12); }
static inline uint32_t wb_dma_csr_t_prio_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 13) & 0x7u); }
static inline void wb_dma_csr_t_prio_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x7u << 13)) | ((uint32_t)(x & 0x7u) << 13); }
static inline uint32_t wb_dma_csr_t_rest_en_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 16) & 0x1u); }
static inline void wb_dma_csr_t_rest_en_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 16)) | ((uint32_t)(x & 0x1u) << 16); }
static inline uint32_t wb_dma_csr_t_ine_err_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 17) & 0x1u); }
static inline void wb_dma_csr_t_ine_err_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 17)) | ((uint32_t)(x & 0x1u) << 17); }
static inline uint32_t wb_dma_csr_t_ine_done_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 18) & 0x1u); }
static inline void wb_dma_csr_t_ine_done_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 18)) | ((uint32_t)(x & 0x1u) << 18); }
static inline uint32_t wb_dma_csr_t_ine_chk_done_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 19) & 0x1u); }
static inline void wb_dma_csr_t_ine_chk_done_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 19)) | ((uint32_t)(x & 0x1u) << 19); }
static inline uint32_t wb_dma_csr_t_int_err_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 20) & 0x1u); }
static inline void wb_dma_csr_t_int_err_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 20)) | ((uint32_t)(x & 0x1u) << 20); }
static inline uint32_t wb_dma_csr_t_int_done_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 21) & 0x1u); }
static inline void wb_dma_csr_t_int_done_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 21)) | ((uint32_t)(x & 0x1u) << 21); }
static inline uint32_t wb_dma_csr_t_int_chk_done_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 22) & 0x1u); }
static inline void wb_dma_csr_t_int_chk_done_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 22)) | ((uint32_t)(x & 0x1u) << 22); }
static inline uint32_t wb_dma_csr_t_rsvd_23_get(wb_dma_csr_t v) { return (uint32_t)((v.raw >> 23) & 0x1ffu); }
static inline void wb_dma_csr_t_rsvd_23_set(wb_dma_csr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1ffu << 23)) | ((uint32_t)(x & 0x1ffu) << 23); }
typedef struct { uint32_t raw; } wb_dma_sz_t;
static inline uint32_t wb_dma_sz_t_tot_sz_get(wb_dma_sz_t v) { return (uint32_t)((v.raw >> 0) & 0xfffu); }
static inline void wb_dma_sz_t_tot_sz_set(wb_dma_sz_t *v, uint32_t x) { v->raw = (v->raw & ~(0xfffu << 0)) | ((uint32_t)(x & 0xfffu) << 0); }
static inline uint32_t wb_dma_sz_t_rsvd_12_get(wb_dma_sz_t v) { return (uint32_t)((v.raw >> 12) & 0xfu); }
static inline void wb_dma_sz_t_rsvd_12_set(wb_dma_sz_t *v, uint32_t x) { v->raw = (v->raw & ~(0xfu << 12)) | ((uint32_t)(x & 0xfu) << 12); }
static inline uint32_t wb_dma_sz_t_chk_sz_get(wb_dma_sz_t v) { return (uint32_t)((v.raw >> 16) & 0x1ffu); }
static inline void wb_dma_sz_t_chk_sz_set(wb_dma_sz_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1ffu << 16)) | ((uint32_t)(x & 0x1ffu) << 16); }
static inline uint32_t wb_dma_sz_t_rsvd_25_get(wb_dma_sz_t v) { return (uint32_t)((v.raw >> 25) & 0x7fu); }
static inline void wb_dma_sz_t_rsvd_25_set(wb_dma_sz_t *v, uint32_t x) { v->raw = (v->raw & ~(0x7fu << 25)) | ((uint32_t)(x & 0x7fu) << 25); }
typedef struct { uint32_t raw; } wb_dma_addr_t;
static inline uint32_t wb_dma_addr_t_addr_get(wb_dma_addr_t v) { return (uint32_t)((v.raw >> 0) & 0xffffffffu); }
static inline void wb_dma_addr_t_addr_set(wb_dma_addr_t *v, uint32_t x) { v->raw = (v->raw & ~(0xffffffffu << 0)) | ((uint32_t)(x & 0xffffffffu) << 0); }
typedef struct { uint32_t raw; } wb_dma_amask_t;
static inline uint32_t wb_dma_amask_t_mask_get(wb_dma_amask_t v) { return (uint32_t)((v.raw >> 0) & 0xffffffffu); }
static inline void wb_dma_amask_t_mask_set(wb_dma_amask_t *v, uint32_t x) { v->raw = (v->raw & ~(0xffffffffu << 0)) | ((uint32_t)(x & 0xffffffffu) << 0); }
typedef struct { uint32_t raw; } wb_dma_descptr_t;
static inline uint32_t wb_dma_descptr_t_ptr_get(wb_dma_descptr_t v) { return (uint32_t)((v.raw >> 0) & 0xffffffffu); }
static inline void wb_dma_descptr_t_ptr_set(wb_dma_descptr_t *v, uint32_t x) { v->raw = (v->raw & ~(0xffffffffu << 0)) | ((uint32_t)(x & 0xffffffffu) << 0); }
typedef struct { uint32_t raw; } wb_dma_swptr_t;
static inline uint32_t wb_dma_swptr_t_ptr_get(wb_dma_swptr_t v) { return (uint32_t)((v.raw >> 0) & 0x7fffffffu); }
static inline void wb_dma_swptr_t_ptr_set(wb_dma_swptr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x7fffffffu << 0)) | ((uint32_t)(x & 0x7fffffffu) << 0); }
static inline uint32_t wb_dma_swptr_t_en_get(wb_dma_swptr_t v) { return (uint32_t)((v.raw >> 31) & 0x1u); }
static inline void wb_dma_swptr_t_en_set(wb_dma_swptr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 31)) | ((uint32_t)(x & 0x1u) << 31); }
typedef struct { uint32_t raw; } wb_dma_gcsr_t;
static inline uint32_t wb_dma_gcsr_t_pause_get(wb_dma_gcsr_t v) { return (uint32_t)((v.raw >> 0) & 0x1u); }
static inline void wb_dma_gcsr_t_pause_set(wb_dma_gcsr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 0)) | ((uint32_t)(x & 0x1u) << 0); }
static inline uint32_t wb_dma_gcsr_t_rsvd_1_get(wb_dma_gcsr_t v) { return (uint32_t)((v.raw >> 1) & 0x7fffffffu); }
static inline void wb_dma_gcsr_t_rsvd_1_set(wb_dma_gcsr_t *v, uint32_t x) { v->raw = (v->raw & ~(0x7fffffffu << 1)) | ((uint32_t)(x & 0x7fffffffu) << 1); }
typedef struct { uint32_t raw; } wb_dma_intmsk_t;
static inline uint32_t wb_dma_intmsk_t_ch_get(wb_dma_intmsk_t v) { return (uint32_t)((v.raw >> 0) & 0x7fffffffu); }
static inline void wb_dma_intmsk_t_ch_set(wb_dma_intmsk_t *v, uint32_t x) { v->raw = (v->raw & ~(0x7fffffffu << 0)) | ((uint32_t)(x & 0x7fffffffu) << 0); }
static inline uint32_t wb_dma_intmsk_t_rsvd_31_get(wb_dma_intmsk_t v) { return (uint32_t)((v.raw >> 31) & 0x1u); }
static inline void wb_dma_intmsk_t_rsvd_31_set(wb_dma_intmsk_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 31)) | ((uint32_t)(x & 0x1u) << 31); }
typedef struct { uint32_t raw; } wb_dma_intsrc_t;
static inline uint32_t wb_dma_intsrc_t_ch_get(wb_dma_intsrc_t v) { return (uint32_t)((v.raw >> 0) & 0x7fffffffu); }
static inline void wb_dma_intsrc_t_ch_set(wb_dma_intsrc_t *v, uint32_t x) { v->raw = (v->raw & ~(0x7fffffffu << 0)) | ((uint32_t)(x & 0x7fffffffu) << 0); }
static inline uint32_t wb_dma_intsrc_t_rsvd_31_get(wb_dma_intsrc_t v) { return (uint32_t)((v.raw >> 31) & 0x1u); }
static inline void wb_dma_intsrc_t_rsvd_31_set(wb_dma_intsrc_t *v, uint32_t x) { v->raw = (v->raw & ~(0x1u << 31)) | ((uint32_t)(x & 0x1u) << 31); }

/* ----- Component handles. ----- */
/*
 * The per-channel MMIO operation model (§3).
 *
 * Every operation the processor initiates against ONE DMA channel lives here.
 * The engine-global operations live on :pss:comp:`wb_dma_c`, which owns an
 * array of these.
 *
 * **Why per-channel components rather than a `chan` parameter.** The completion
 * condition is a channel register, so making the channel an instance rather
 * than an index keeps every access in the operation code index-free
 * (``regs.csr.read()``), which is both clearer and safer than indexing a
 * register array with a runtime value. It also matches the review decision that
 * a waking thread reads its own channel's status register (§3.1.1). The cost is
 * that each channel binds its own top-level register group.
 *
 * **Two layers, and every target gets both.**
 *
 * ``core``
 *     ``configure_channel``, ``set_auto_restart``, ``set_software_pointer``,
 *     ``transfer_single_start``, ``transfer_list_start``,
 *     ``stop_channel_start``, ``check_completion``. Arm-and-return plus a
 *     single-read poll; nothing here ever waits. The low-level driver API.
 *
 * ``end-to-end``
 *     ``wait_completion``, ``transfer_single``, ``transfer_list``,
 *     ``stop_channel``. Each is a ``*_start()`` followed by
 *     ``repeat { probe_status; wait_hint }``.
 *
 * What varies between profiles is one function body -- ``wait_hint()``, which
 * either suspends on :pss:field:`wake` or spins with ``yield``. Nothing else
 * reads ``HAS_EVENT_WAIT`` except ``notify_irq()``, the event producer.
 *
 * The end-to-end layer adds no device knowledge, only the loop. That is what
 * makes the core trustworthy without a second regression: every SystemVerilog
 * run drives the core through the end-to-end wrappers.
 */
typedef struct wb_dma_ch_s {
    const pssc_mem_if *bus;
    pssc_addr_t base;
    /*
     * Which channel this is, in ``dma_req_i``/``dma_ack_o`` and INT_SRC bit
     * numbering.
     *
     * Integrator-facing identity: no operation here reads it, because each
     * channel reaches its own registers through :pss:field:`regs` rather than
     * by index. It is what an environment correlates a channel against.
     */
    int chan;
    /*
     * Build-time capabilities.
     *
     * An absent capability makes the corresponding control bit silently ignored
     * by hardware, so operations consult this rather than assuming everything
     * is present.
     */
    wb_dma_ch_caps_t caps;
    pssc_chan1_t inflight;
    pssc_chan1_t wake;
} wb_dma_ch_t;

/*
 * The MMIO operation model for the WISHBONE DMA/Bridge core (§3,
 * ``dma_mmio_c`` in the operation-model document).
 *
 * This component holds the engine-GLOBAL operations -- PAUSE, interrupt
 * routing, descriptor authoring. Everything per-channel is on
 * :pss:comp:`wb_dma_ch_c`, an array of which it owns.
 *
 * Scope (§1): everything the processor reaches by load/store. The per-channel
 * hardware handshake's participant is the PERIPHERAL, so its model sits with
 * the environment (``tests/pss/wb_dma_hs_c.pss``). The WISHBONE masters are
 * device-driven and out of scope; so is descriptor FETCHING, though descriptor
 * AUTHORING is here, because the processor initiates it.
 *
 * Deliberately absent:
 *
 * * **bulk buffer access** -- the test writer already has a path to memory
 *   (``read32``/``write32``); filling a source region and checking a
 *   destination region are not operations of this model.
 * * **bus-error injection** -- it belongs to whatever component can drive
 *   ``err_i``. A DMA-error-reaction test is a composition of two operation
 *   models, not a wider version of this one (§5.1).
 * * **bridge_access** -- the pass-through path is reachable only with a target
 *   on the far interface; omitted by review decision.
 */
typedef struct wb_dma_s {
    const pssc_mem_if *bus;
    pssc_addr_t base;
    /*
     * How many channels this instance actually uses.
     *
     * Integrator-facing: operations should be issued only to
     * ``ch[0..num_ch-1]``. Nothing in this model enforces that -- the register
     * structure is sized at ``WB_DMA_MAX_CH`` regardless, so a stray
     * access reaches a bank the RTL may not implement.
     */
    int num_ch;
    /*
     * Build-time ``pri_sel``: how many priority levels the part discriminates.
     *
     * Integrator-facing, and likewise unenforced. Legal values are 1, 4 and 8;
     * a ``wb_dma_ch_cfg_s.prio`` above this is not an error, it simply does not
     * discriminate.
     */
    int pri_levels;
    wb_dma_ch_t ch[4];
} wb_dma_t;

/* pssc_bus(s): the seam's first argument -- the ONLY line varying by style. */
#define pssc_bus(s) ((s)->bus)

/* ----- Sub-component access. ----- */
#define WB_DMA_CH_COUNT 4u
static inline wb_dma_ch_t *wb_dma_ch(wb_dma_t *s, unsigned i) { return &s->ch[i]; }

/* ----- Baked inline register accessors. ----- */
static inline pssc_addr_t wb_dma_regs_csr_addr(const wb_dma_t *s) { return s->base + 0x0u; }
static inline wb_dma_gcsr_t wb_dma_regs_csr_read(wb_dma_t *s) { wb_dma_gcsr_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_csr_addr(s)); return v; }
static inline void wb_dma_regs_csr_write(wb_dma_t *s, wb_dma_gcsr_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_csr_addr(s), v.raw); }
static inline uint32_t wb_dma_regs_csr_read_val(wb_dma_t *s) { return pssc_r32(pssc_bus(s), wb_dma_regs_csr_addr(s)); }
static inline void wb_dma_regs_csr_write_val(wb_dma_t *s, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_csr_addr(s), v); }
static inline void wb_dma_regs_csr_write_masked(wb_dma_t *s, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_regs_csr_read_val(s); wb_dma_regs_csr_write_val(s, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_regs_int_msk_a_addr(const wb_dma_t *s) { return s->base + 0x4u; }
static inline wb_dma_intmsk_t wb_dma_regs_int_msk_a_read(wb_dma_t *s) { wb_dma_intmsk_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_int_msk_a_addr(s)); return v; }
static inline void wb_dma_regs_int_msk_a_write(wb_dma_t *s, wb_dma_intmsk_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_int_msk_a_addr(s), v.raw); }
static inline uint32_t wb_dma_regs_int_msk_a_read_val(wb_dma_t *s) { return pssc_r32(pssc_bus(s), wb_dma_regs_int_msk_a_addr(s)); }
static inline void wb_dma_regs_int_msk_a_write_val(wb_dma_t *s, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_int_msk_a_addr(s), v); }
static inline void wb_dma_regs_int_msk_a_write_masked(wb_dma_t *s, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_regs_int_msk_a_read_val(s); wb_dma_regs_int_msk_a_write_val(s, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_regs_int_msk_b_addr(const wb_dma_t *s) { return s->base + 0x8u; }
static inline wb_dma_intmsk_t wb_dma_regs_int_msk_b_read(wb_dma_t *s) { wb_dma_intmsk_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_int_msk_b_addr(s)); return v; }
static inline void wb_dma_regs_int_msk_b_write(wb_dma_t *s, wb_dma_intmsk_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_int_msk_b_addr(s), v.raw); }
static inline uint32_t wb_dma_regs_int_msk_b_read_val(wb_dma_t *s) { return pssc_r32(pssc_bus(s), wb_dma_regs_int_msk_b_addr(s)); }
static inline void wb_dma_regs_int_msk_b_write_val(wb_dma_t *s, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_int_msk_b_addr(s), v); }
static inline void wb_dma_regs_int_msk_b_write_masked(wb_dma_t *s, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_regs_int_msk_b_read_val(s); wb_dma_regs_int_msk_b_write_val(s, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_regs_int_src_a_addr(const wb_dma_t *s) { return s->base + 0xcu; }
static inline wb_dma_intsrc_t wb_dma_regs_int_src_a_read(wb_dma_t *s) { wb_dma_intsrc_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_int_src_a_addr(s)); return v; }
static inline uint32_t wb_dma_regs_int_src_a_read_val(wb_dma_t *s) { return pssc_r32(pssc_bus(s), wb_dma_regs_int_src_a_addr(s)); }
static inline pssc_addr_t wb_dma_regs_int_src_b_addr(const wb_dma_t *s) { return s->base + 0x10u; }
static inline wb_dma_intsrc_t wb_dma_regs_int_src_b_read(wb_dma_t *s) { wb_dma_intsrc_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_int_src_b_addr(s)); return v; }
static inline uint32_t wb_dma_regs_int_src_b_read_val(wb_dma_t *s) { return pssc_r32(pssc_bus(s), wb_dma_regs_int_src_b_addr(s)); }
static inline pssc_addr_t wb_dma_regs_bank_csr_addr(const wb_dma_t *s, int i0) { return s->base + 0x20u + (pssc_addr_t)i0 * 0x20u; }
static inline wb_dma_csr_t wb_dma_regs_bank_csr_read(wb_dma_t *s, int i0) { wb_dma_csr_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_bank_csr_addr(s, i0)); return v; }
static inline void wb_dma_regs_bank_csr_write(wb_dma_t *s, int i0, wb_dma_csr_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_csr_addr(s, i0), v.raw); }
static inline uint32_t wb_dma_regs_bank_csr_read_val(wb_dma_t *s, int i0) { return pssc_r32(pssc_bus(s), wb_dma_regs_bank_csr_addr(s, i0)); }
static inline void wb_dma_regs_bank_csr_write_val(wb_dma_t *s, int i0, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_csr_addr(s, i0), v); }
static inline void wb_dma_regs_bank_csr_write_masked(wb_dma_t *s, int i0, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_regs_bank_csr_read_val(s, i0); wb_dma_regs_bank_csr_write_val(s, i0, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_regs_bank_sz_addr(const wb_dma_t *s, int i0) { return s->base + 0x24u + (pssc_addr_t)i0 * 0x20u; }
static inline wb_dma_sz_t wb_dma_regs_bank_sz_read(wb_dma_t *s, int i0) { wb_dma_sz_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_bank_sz_addr(s, i0)); return v; }
static inline void wb_dma_regs_bank_sz_write(wb_dma_t *s, int i0, wb_dma_sz_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_sz_addr(s, i0), v.raw); }
static inline uint32_t wb_dma_regs_bank_sz_read_val(wb_dma_t *s, int i0) { return pssc_r32(pssc_bus(s), wb_dma_regs_bank_sz_addr(s, i0)); }
static inline void wb_dma_regs_bank_sz_write_val(wb_dma_t *s, int i0, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_sz_addr(s, i0), v); }
static inline void wb_dma_regs_bank_sz_write_masked(wb_dma_t *s, int i0, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_regs_bank_sz_read_val(s, i0); wb_dma_regs_bank_sz_write_val(s, i0, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_regs_bank_adr0_addr(const wb_dma_t *s, int i0) { return s->base + 0x28u + (pssc_addr_t)i0 * 0x20u; }
static inline wb_dma_addr_t wb_dma_regs_bank_adr0_read(wb_dma_t *s, int i0) { wb_dma_addr_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_bank_adr0_addr(s, i0)); return v; }
static inline void wb_dma_regs_bank_adr0_write(wb_dma_t *s, int i0, wb_dma_addr_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_adr0_addr(s, i0), v.raw); }
static inline uint32_t wb_dma_regs_bank_adr0_read_val(wb_dma_t *s, int i0) { return pssc_r32(pssc_bus(s), wb_dma_regs_bank_adr0_addr(s, i0)); }
static inline void wb_dma_regs_bank_adr0_write_val(wb_dma_t *s, int i0, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_adr0_addr(s, i0), v); }
static inline void wb_dma_regs_bank_adr0_write_masked(wb_dma_t *s, int i0, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_regs_bank_adr0_read_val(s, i0); wb_dma_regs_bank_adr0_write_val(s, i0, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_regs_bank_am0_addr(const wb_dma_t *s, int i0) { return s->base + 0x2cu + (pssc_addr_t)i0 * 0x20u; }
static inline wb_dma_amask_t wb_dma_regs_bank_am0_read(wb_dma_t *s, int i0) { wb_dma_amask_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_bank_am0_addr(s, i0)); return v; }
static inline void wb_dma_regs_bank_am0_write(wb_dma_t *s, int i0, wb_dma_amask_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_am0_addr(s, i0), v.raw); }
static inline uint32_t wb_dma_regs_bank_am0_read_val(wb_dma_t *s, int i0) { return pssc_r32(pssc_bus(s), wb_dma_regs_bank_am0_addr(s, i0)); }
static inline void wb_dma_regs_bank_am0_write_val(wb_dma_t *s, int i0, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_am0_addr(s, i0), v); }
static inline void wb_dma_regs_bank_am0_write_masked(wb_dma_t *s, int i0, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_regs_bank_am0_read_val(s, i0); wb_dma_regs_bank_am0_write_val(s, i0, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_regs_bank_adr1_addr(const wb_dma_t *s, int i0) { return s->base + 0x30u + (pssc_addr_t)i0 * 0x20u; }
static inline wb_dma_addr_t wb_dma_regs_bank_adr1_read(wb_dma_t *s, int i0) { wb_dma_addr_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_bank_adr1_addr(s, i0)); return v; }
static inline void wb_dma_regs_bank_adr1_write(wb_dma_t *s, int i0, wb_dma_addr_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_adr1_addr(s, i0), v.raw); }
static inline uint32_t wb_dma_regs_bank_adr1_read_val(wb_dma_t *s, int i0) { return pssc_r32(pssc_bus(s), wb_dma_regs_bank_adr1_addr(s, i0)); }
static inline void wb_dma_regs_bank_adr1_write_val(wb_dma_t *s, int i0, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_adr1_addr(s, i0), v); }
static inline void wb_dma_regs_bank_adr1_write_masked(wb_dma_t *s, int i0, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_regs_bank_adr1_read_val(s, i0); wb_dma_regs_bank_adr1_write_val(s, i0, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_regs_bank_am1_addr(const wb_dma_t *s, int i0) { return s->base + 0x34u + (pssc_addr_t)i0 * 0x20u; }
static inline wb_dma_amask_t wb_dma_regs_bank_am1_read(wb_dma_t *s, int i0) { wb_dma_amask_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_bank_am1_addr(s, i0)); return v; }
static inline void wb_dma_regs_bank_am1_write(wb_dma_t *s, int i0, wb_dma_amask_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_am1_addr(s, i0), v.raw); }
static inline uint32_t wb_dma_regs_bank_am1_read_val(wb_dma_t *s, int i0) { return pssc_r32(pssc_bus(s), wb_dma_regs_bank_am1_addr(s, i0)); }
static inline void wb_dma_regs_bank_am1_write_val(wb_dma_t *s, int i0, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_am1_addr(s, i0), v); }
static inline void wb_dma_regs_bank_am1_write_masked(wb_dma_t *s, int i0, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_regs_bank_am1_read_val(s, i0); wb_dma_regs_bank_am1_write_val(s, i0, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_regs_bank_desc_addr(const wb_dma_t *s, int i0) { return s->base + 0x38u + (pssc_addr_t)i0 * 0x20u; }
static inline wb_dma_descptr_t wb_dma_regs_bank_desc_read(wb_dma_t *s, int i0) { wb_dma_descptr_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_bank_desc_addr(s, i0)); return v; }
static inline void wb_dma_regs_bank_desc_write(wb_dma_t *s, int i0, wb_dma_descptr_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_desc_addr(s, i0), v.raw); }
static inline uint32_t wb_dma_regs_bank_desc_read_val(wb_dma_t *s, int i0) { return pssc_r32(pssc_bus(s), wb_dma_regs_bank_desc_addr(s, i0)); }
static inline void wb_dma_regs_bank_desc_write_val(wb_dma_t *s, int i0, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_desc_addr(s, i0), v); }
static inline void wb_dma_regs_bank_desc_write_masked(wb_dma_t *s, int i0, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_regs_bank_desc_read_val(s, i0); wb_dma_regs_bank_desc_write_val(s, i0, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_regs_bank_swptr_addr(const wb_dma_t *s, int i0) { return s->base + 0x3cu + (pssc_addr_t)i0 * 0x20u; }
static inline wb_dma_swptr_t wb_dma_regs_bank_swptr_read(wb_dma_t *s, int i0) { wb_dma_swptr_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_regs_bank_swptr_addr(s, i0)); return v; }
static inline void wb_dma_regs_bank_swptr_write(wb_dma_t *s, int i0, wb_dma_swptr_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_swptr_addr(s, i0), v.raw); }
static inline uint32_t wb_dma_regs_bank_swptr_read_val(wb_dma_t *s, int i0) { return pssc_r32(pssc_bus(s), wb_dma_regs_bank_swptr_addr(s, i0)); }
static inline void wb_dma_regs_bank_swptr_write_val(wb_dma_t *s, int i0, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_regs_bank_swptr_addr(s, i0), v); }
static inline void wb_dma_regs_bank_swptr_write_masked(wb_dma_t *s, int i0, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_regs_bank_swptr_read_val(s, i0); wb_dma_regs_bank_swptr_write_val(s, i0, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_ch_regs_csr_addr(const wb_dma_ch_t *s) { return s->base + 0x0u; }
static inline wb_dma_csr_t wb_dma_ch_regs_csr_read(wb_dma_ch_t *s) { wb_dma_csr_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_ch_regs_csr_addr(s)); return v; }
static inline void wb_dma_ch_regs_csr_write(wb_dma_ch_t *s, wb_dma_csr_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_csr_addr(s), v.raw); }
static inline uint32_t wb_dma_ch_regs_csr_read_val(wb_dma_ch_t *s) { return pssc_r32(pssc_bus(s), wb_dma_ch_regs_csr_addr(s)); }
static inline void wb_dma_ch_regs_csr_write_val(wb_dma_ch_t *s, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_csr_addr(s), v); }
static inline void wb_dma_ch_regs_csr_write_masked(wb_dma_ch_t *s, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_ch_regs_csr_read_val(s); wb_dma_ch_regs_csr_write_val(s, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_ch_regs_sz_addr(const wb_dma_ch_t *s) { return s->base + 0x4u; }
static inline wb_dma_sz_t wb_dma_ch_regs_sz_read(wb_dma_ch_t *s) { wb_dma_sz_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_ch_regs_sz_addr(s)); return v; }
static inline void wb_dma_ch_regs_sz_write(wb_dma_ch_t *s, wb_dma_sz_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_sz_addr(s), v.raw); }
static inline uint32_t wb_dma_ch_regs_sz_read_val(wb_dma_ch_t *s) { return pssc_r32(pssc_bus(s), wb_dma_ch_regs_sz_addr(s)); }
static inline void wb_dma_ch_regs_sz_write_val(wb_dma_ch_t *s, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_sz_addr(s), v); }
static inline void wb_dma_ch_regs_sz_write_masked(wb_dma_ch_t *s, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_ch_regs_sz_read_val(s); wb_dma_ch_regs_sz_write_val(s, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_ch_regs_adr0_addr(const wb_dma_ch_t *s) { return s->base + 0x8u; }
static inline wb_dma_addr_t wb_dma_ch_regs_adr0_read(wb_dma_ch_t *s) { wb_dma_addr_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_ch_regs_adr0_addr(s)); return v; }
static inline void wb_dma_ch_regs_adr0_write(wb_dma_ch_t *s, wb_dma_addr_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_adr0_addr(s), v.raw); }
static inline uint32_t wb_dma_ch_regs_adr0_read_val(wb_dma_ch_t *s) { return pssc_r32(pssc_bus(s), wb_dma_ch_regs_adr0_addr(s)); }
static inline void wb_dma_ch_regs_adr0_write_val(wb_dma_ch_t *s, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_adr0_addr(s), v); }
static inline void wb_dma_ch_regs_adr0_write_masked(wb_dma_ch_t *s, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_ch_regs_adr0_read_val(s); wb_dma_ch_regs_adr0_write_val(s, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_ch_regs_am0_addr(const wb_dma_ch_t *s) { return s->base + 0xcu; }
static inline wb_dma_amask_t wb_dma_ch_regs_am0_read(wb_dma_ch_t *s) { wb_dma_amask_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_ch_regs_am0_addr(s)); return v; }
static inline void wb_dma_ch_regs_am0_write(wb_dma_ch_t *s, wb_dma_amask_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_am0_addr(s), v.raw); }
static inline uint32_t wb_dma_ch_regs_am0_read_val(wb_dma_ch_t *s) { return pssc_r32(pssc_bus(s), wb_dma_ch_regs_am0_addr(s)); }
static inline void wb_dma_ch_regs_am0_write_val(wb_dma_ch_t *s, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_am0_addr(s), v); }
static inline void wb_dma_ch_regs_am0_write_masked(wb_dma_ch_t *s, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_ch_regs_am0_read_val(s); wb_dma_ch_regs_am0_write_val(s, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_ch_regs_adr1_addr(const wb_dma_ch_t *s) { return s->base + 0x10u; }
static inline wb_dma_addr_t wb_dma_ch_regs_adr1_read(wb_dma_ch_t *s) { wb_dma_addr_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_ch_regs_adr1_addr(s)); return v; }
static inline void wb_dma_ch_regs_adr1_write(wb_dma_ch_t *s, wb_dma_addr_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_adr1_addr(s), v.raw); }
static inline uint32_t wb_dma_ch_regs_adr1_read_val(wb_dma_ch_t *s) { return pssc_r32(pssc_bus(s), wb_dma_ch_regs_adr1_addr(s)); }
static inline void wb_dma_ch_regs_adr1_write_val(wb_dma_ch_t *s, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_adr1_addr(s), v); }
static inline void wb_dma_ch_regs_adr1_write_masked(wb_dma_ch_t *s, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_ch_regs_adr1_read_val(s); wb_dma_ch_regs_adr1_write_val(s, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_ch_regs_am1_addr(const wb_dma_ch_t *s) { return s->base + 0x14u; }
static inline wb_dma_amask_t wb_dma_ch_regs_am1_read(wb_dma_ch_t *s) { wb_dma_amask_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_ch_regs_am1_addr(s)); return v; }
static inline void wb_dma_ch_regs_am1_write(wb_dma_ch_t *s, wb_dma_amask_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_am1_addr(s), v.raw); }
static inline uint32_t wb_dma_ch_regs_am1_read_val(wb_dma_ch_t *s) { return pssc_r32(pssc_bus(s), wb_dma_ch_regs_am1_addr(s)); }
static inline void wb_dma_ch_regs_am1_write_val(wb_dma_ch_t *s, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_am1_addr(s), v); }
static inline void wb_dma_ch_regs_am1_write_masked(wb_dma_ch_t *s, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_ch_regs_am1_read_val(s); wb_dma_ch_regs_am1_write_val(s, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_ch_regs_desc_addr(const wb_dma_ch_t *s) { return s->base + 0x18u; }
static inline wb_dma_descptr_t wb_dma_ch_regs_desc_read(wb_dma_ch_t *s) { wb_dma_descptr_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_ch_regs_desc_addr(s)); return v; }
static inline void wb_dma_ch_regs_desc_write(wb_dma_ch_t *s, wb_dma_descptr_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_desc_addr(s), v.raw); }
static inline uint32_t wb_dma_ch_regs_desc_read_val(wb_dma_ch_t *s) { return pssc_r32(pssc_bus(s), wb_dma_ch_regs_desc_addr(s)); }
static inline void wb_dma_ch_regs_desc_write_val(wb_dma_ch_t *s, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_desc_addr(s), v); }
static inline void wb_dma_ch_regs_desc_write_masked(wb_dma_ch_t *s, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_ch_regs_desc_read_val(s); wb_dma_ch_regs_desc_write_val(s, (cur & ~mask) | (val & mask)); }
static inline pssc_addr_t wb_dma_ch_regs_swptr_addr(const wb_dma_ch_t *s) { return s->base + 0x1cu; }
static inline wb_dma_swptr_t wb_dma_ch_regs_swptr_read(wb_dma_ch_t *s) { wb_dma_swptr_t v; v.raw = pssc_r32(pssc_bus(s), wb_dma_ch_regs_swptr_addr(s)); return v; }
static inline void wb_dma_ch_regs_swptr_write(wb_dma_ch_t *s, wb_dma_swptr_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_swptr_addr(s), v.raw); }
static inline uint32_t wb_dma_ch_regs_swptr_read_val(wb_dma_ch_t *s) { return pssc_r32(pssc_bus(s), wb_dma_ch_regs_swptr_addr(s)); }
static inline void wb_dma_ch_regs_swptr_write_val(wb_dma_ch_t *s, uint32_t v) { pssc_w32(pssc_bus(s), wb_dma_ch_regs_swptr_addr(s), v); }
static inline void wb_dma_ch_regs_swptr_write_masked(wb_dma_ch_t *s, uint32_t mask, uint32_t val) { uint32_t cur = wb_dma_ch_regs_swptr_read_val(s); wb_dma_ch_regs_swptr_write_val(s, (cur & ~mask) | (val & mask)); }

/* ----- Export API + lifecycle. ----- */
void wb_dma_init(wb_dma_t *self, const pssc_mem_if *bus, pssc_addr_t base);
wb_dma_t *wb_dma_create(const pssc_mem_if *bus, pssc_addr_t base);
void wb_dma_destroy(wb_dma_t *self);

/*
 * Route a set of channels to one of the two aggregate interrupt outputs.
 *
 * *§3.2 group 2, configuration.* Completes when INT_MSK_A/B has been
 * updated; waits for nothing.
 *
 * The two banks are independent aggregate outputs, and a channel may be
 * routed to both. ``channel_mask`` stays a bit vector rather than becoming
 * a channel list because it genuinely is one: bit N routes channel N.
 *
 * **A hard prerequisite for every end-to-end operation, enforced by
 * deadlock** on the event-wait profile. Completion IS the interrupt, so a
 * test that routes nothing raises no interrupt, nothing calls
 * ``notify_irq()``, and the first wait blocks forever. Routing at least one
 * channel in a bank keeps the whole test alive, because ``notify_irq()``
 * posts to every channel blind. That is intended: a hang is a more honest
 * result than a green test whose completion path was never exercised.
 *
 * :param bank:         which aggregate output to program
 * :param channel_mask: bit N routes channel N
 */
void wb_dma_configure_interrupt_routing(wb_dma_t *s, wb_dma_int_bank_t bank, uint32_t channel_mask);

/*
 * Pause or un-pause the whole engine, and wait until it has taken effect.
 *
 * *§3.2 group 2, configuration.* Global, not per-channel.
 *
 * Completes when a readback of ``CSR.PAUSE`` matches the requested value.
 * The engine only pauses after the CURRENT transfer completes, so the write
 * and the state change are NOT simultaneous -- which is the entire reason
 * this is an operation rather than a register write, and the clearest small
 * illustration of the blocking rule: the operation is not done when the
 * store retires.
 *
 * It waits for that readback, and is the one wait in this model with no
 * interrupt behind it -- in a real driver, a retry or timer loop rather than
 * an ISR wake. The global CSR is not read-to-clear, so unlike the channel
 * CSR this poll is genuinely side-effect-free and may run any number of
 * times.
 *
 * :param pause: 1 to pause, 0 to resume
 */
void wb_dma_pause_engine(wb_dma_t *s, uint8_t pause);

/*
 * Read back how much of a descriptor's transfer actually moved.
 *
 * *§3.2 group 3, configuration.* Completes when DESC_CSR has been loaded
 * back from memory and decoded; waits for nothing.
 *
 * A device-specific decode, not a memory service -- the same rationale that
 * keeps ``write_descriptor()`` in this model. Only meaningful when SZ_WB is
 * set in the channel CSR and the descriptor was cut short by
 * ``skip_to_next_descriptor()``. This is how software learns how much of a
 * variable-length payload actually moved, which is the whole point of §3.9.
 *
 * .. note::
 *    Open question (§6.1): §3.9 says the remaining BYTES are written back,
 *    into a field Table 1 defines as a 12-bit WORD count. One of the two is
 *    wrong. This returns the raw field and lets the caller decide.
 *
 * :param desc_ptr: the descriptor whose control word is read back
 */
uint16_t wb_dma_read_descriptor_residual(wb_dma_t *s, pssc_addr_t desc_ptr);

/*
 * Write one external descriptor into memory and link it to its predecessor.
 *
 * *§3.2 group 3, configuration.* Completes when the descriptor is in memory
 * at ``at``, terminated (DESC_NEXT zero), and ``prev`` -- if there is one --
 * points at it. Waits for nothing. Returns a handle to the slot immediately
 * after ``at``, i.e. the natural place for the next descriptor, so a caller
 * can build a list in place one link at a time.
 *
 * This is DEVICE KNOWLEDGE written through a memory path, not a path to
 * memory: the next-pointer linkage and the EOL rule are the operation, the
 * layout is declared by :pss:struct:`wb_dma_desc_s`, and ``write32`` is
 * merely how it lands. That is what makes it an operation where a generic
 * ``write_buffer()`` would not be.
 *
 * ``at`` must be reachable from interface 0: descriptors are fetched from
 * IF0 regardless of which interface the DATA moves on (§3.3).
 *
 * :param at:   where this descriptor goes
 * :param prev: the descriptor to link from; null/zero means "head of list"
 * :param desc: the descriptor contents; the caller's copy is not modified
 */
pssc_addr_t wb_dma_write_descriptor(wb_dma_t *s, pssc_addr_t at, pssc_addr_t prev, wb_dma_desc_t desc);

void wb_dma_ch_init(wb_dma_ch_t *self, const pssc_mem_if *bus, int id, pssc_addr_t bank);

/*
 * Block until the operation running on this channel reaches a terminal state.
 *
 * *§3.1.* Not an operation in its own right: it is the ONE place in this tree
 * that waits for a completion, and therefore the whole of what the end-to-end
 * operations add over their ``*_start()`` halves. Present on every profile --
 * these functions do not need a scheduler, they need a way to wait, and that
 * choice is made once, in ``wait_hint()``.
 *
 * Waiting is realised as ``repeat { probe_status; wait_hint }``, where
 * ``probe_status()`` is the same single CSR read ``check_completion()`` uses.
 * Nothing is edge-triggered: the condition is re-read from the device on every
 * iteration, waking threads test their own conditions, and a spurious wake is
 * harmless. That is what makes the loop correct whether ``wait_hint()``
 * suspends on an interrupt or merely spins -- the two differ in what a lap
 * costs, not in what the loop concludes. **The wake is a hint; CHn_CSR is the
 * event.**
 *
 * That sharing is the argument for the whole start/wait split. The
 * non-blocking core is not a second implementation to be kept in step with
 * this one -- it is the body of this one, hoisted. A SystemVerilog regression
 * that only ever calls ``transfer_single()`` still executes every register
 * access a firmware caller will make, in the same order, so the two paths
 * cannot drift. That is why there is no second regression for the firmware
 * profile.
 *
 * **The side-effect problem (§3.1.1).** ``probe_status()`` runs an unbounded
 * number of times and it consumes state: reading CHn_CSR clears ERR and the
 * three interrupt-source bits. It is safe because the value is captured by the
 * same read that observes it, the loop exits holding it, and AT MOST ONE
 * OPERATION PER CHANNEL AT A TIME makes the polling thread the sole consumer.
 * ``stop_channel()`` is the one deliberate exception.
 *
 * **The guard is released here** because an operation is over when its
 * completion has been reported, which is this return. Releasing here rather
 * than in each caller keeps the claim and the release one fact in two places
 * instead of one in three.
 *
 * A stale ``wake`` token costs one read, exactly, and only on the event-wait
 * profile: the loop probes BEFORE it ever waits, and ``wake``'s depth of 1
 * caps the leftover at one, so the worst case is probe, wait-immediate, probe,
 * wait-blocks. There is deliberately no drain step at entry -- it would cost
 * the same read it saves.
 *
 * .. warning::
 *    On the event-wait profile the routing prerequisite is load-bearing. A
 *    test that never called ``configure_interrupt_routing()`` raises no
 *    interrupt, so nothing calls ``notify_irq()``, so this blocks forever.
 *    Blind posting softens it -- any ONE routed channel's interrupt wakes
 *    every waiter -- so a partially routed test still makes progress and a
 *    test that routes nothing deadlocks. That is intended: a hang is a more
 *    honest result than a green test whose completion path was never real. If
 *    you are debugging a hang here, check INT_MSK_A/B before you look at the
 *    DMA. A polling profile has no such exposure, because ``wait_hint()``
 *    spins -- the routing requirement belongs to the wait primitive, not to
 *    this operation.
 */
wb_dma_status_t wb_dma_ch_wait_completion(wb_dma_ch_t *s);

/*
 * Run one transfer to completion and report how it ended.
 *
 * *§3.2 group 1, end-to-end.* Completes when the channel's DONE (or ERR)
 * interrupt has been observed and the CHn_CSR read has returned the status and
 * cleared the source. Waits for channel DONE or ERR -- this is the core driver
 * FSM: submit, RUNNING, completion.
 *
 * The body is the two halves, named. All of the device knowledge -- what to
 * program, in what order, which write arms the channel -- is in
 * ``transfer_single_start()``; all of the waiting is in ``wait_completion()``.
 * This function contributes the composition and the return type.
 *
 * .. warning::
 *    Two callers' obligations this signature does not encode, both stated in
 *    full on ``transfer_single_start()``. With
 *    ``mode == WB_DMA_HW_HANDSHAKE`` this call cannot complete on its own:
 *    something must be calling ``request_chunk()`` on the matching
 *    ``wb_dma_hs_c`` concurrently (§2.2). With ``cfg.auto_restart`` this call
 *    is DELIBERATELY NON-TERMINATING: another thread must clear ARS or abort
 *    the channel. It is a blocking read on a stream that ends when someone
 *    closes it, so an ARS transfer must never be the only operation a scenario
 *    waits on.
 *
 * :param cfg: what to program before arming
 */
wb_dma_status_t wb_dma_ch_transfer_single(wb_dma_ch_t *s, wb_dma_ch_cfg_t cfg);

/*
 * Run a descriptor chain to completion and report how it ended.
 *
 * *§3.2 group 3, end-to-end.* Completes when a descriptor with EOL set has
 * been processed -- the engine stops, sets DONE in CHn_CSR, and raises the
 * channel interrupt. Waits for EOL DONE, plus optional intermediate wakes:
 * RUNNING has internal structure here, being per-descriptor progress inside
 * one outstanding request.
 *
 * The four-step arming procedure of §3.3 lives in ``transfer_list_start()``,
 * along with the note about which configuration a descriptor does NOT carry
 * and must therefore come from a prior ``configure_channel()``.
 *
 * Unlike ``transfer_single()`` this completion is unconditional: ARS is
 * documented as meaningless and ignored with external descriptors (§3.3). Two
 * end-to-end operations differing only in completion contract is why neither
 * subsumes the other -- and the difference is entirely in the arming half, not
 * in the wait, which is why both share one ``wait_completion()``.
 *
 * :param head: head of the descriptor chain, as returned when the list was
 *              built; must be reachable from interface 0
 */
wb_dma_status_t wb_dma_ch_transfer_list(wb_dma_ch_t *s, pssc_addr_t head);

/*
 * Abort whatever is running on this channel and wait for the abort to land.
 *
 * *§3.2 group 1, end-to-end.* Completes when STOP has been written, the
 * channel has aborted, ERR is set, and the error interrupt (if enabled) has
 * been raised. Waits for channel ERR -- an abort path that completes the SAME
 * outstanding request from a second entry point.
 *
 * An abort is reported as an ERROR, not as a clean stop. Note the consequence
 * for the scenario layer: the aborted ``transfer_single()`` also returns, with
 * ``WB_DMA_ERROR``. Two end-to-end operations complete off one event.
 *
 * **It has its own loop rather than calling** ``wait_completion()``. By
 * definition it aborts a transfer that is still running, so it violates the
 * one-operation-per-channel rule that makes the polling read safe.
 * ``stop_channel_start()`` claims no token, so this function holds none -- and
 * ``wait_completion()`` ends by RELEASING one, which would take the aborted
 * transfer's. Hence the loop below: identical to ``wait_completion()``'s
 * except that it does not touch the guard. The duplication is five lines and
 * it is the honest shape; a "do not release" flag would hide the one place in
 * this model where two operations legitimately share a channel.
 *
 * See ``stop_channel_start()`` for what that sharing costs -- which read
 * consumes the ERR is not determined by this model -- and for open item §6.5.
 */
wb_dma_status_t wb_dma_ch_stop_channel(wb_dma_ch_t *s);

/*
 * Poll whether the operation running on this channel has finished.
 *
 * The non-blocking half of every end-to-end operation, present on every
 * profile -- this is what firmware polls. Completes immediately: one
 * register read, one answer. It never suspends and never spins; the caller
 * supplies the loop.
 *
 * **The contract is narrower than it looks.**
 *
 * 1. An operation must have been STARTED on this channel, by one of
 *    ``transfer_single_start()`` or ``transfer_list_start()``.
 * 2. Once this returns anything other than ``WB_DMA_PENDING``, the operation
 *    is over. DO NOT CALL AGAIN until the next ``*_start()``.
 *
 * Both rules exist because reading CHn_CSR is destructive: ERR and the three
 * interrupt-source bits are read-to-clear, so this call CONSUMES the
 * completion it reports. A second call after DONE does not re-report DONE --
 * it reads a channel whose status has already been taken and answers PENDING
 * forever. That failure is invisible from the device side, because a stale
 * read and a live one look identical.
 *
 * **How the guard works.** :pss:field:`inflight` holds one token for the
 * life of an operation. This takes it, reads, and puts it back only if the
 * answer was PENDING:
 *
 * ``try_get`` fails
 *     Rule 1 or rule 2 has been broken. Report it.
 * ``WB_DMA_PENDING``
 *     Restore the token; the operation continues.
 * ``WB_DMA_DONE`` / ``WB_DMA_ERROR``
 *     Leave it taken; the operation is over.
 *
 * Take-and-restore rather than a peek because ``channel_c`` has no peek
 * (§21.9.1 offers get/put/try_get/try_put and nothing else). It is safe
 * under the one-operation-per-channel rule that already governs this model:
 * the polling thread is the only one entitled to that token.
 *
 * .. note::
 *    "Report it" is weaker than it should be. This stdlib has no runtime
 *    ``error()``, so a violation is a message at ``NONE`` verbosity -- the
 *    loudest thing available, and still only a message. A runtime that wants
 *    it fatal should bind the model's message sink to one; the text is
 *    deliberately distinctive so it can be matched. Returning
 *    ``WB_DMA_ERROR`` was considered and rejected: it would make a
 *    PROGRAMMING error indistinguishable from a DEVICE error. It answers
 *    PENDING instead, because the state needed for an honest answer was
 *    consumed by whoever broke the rule.
 */
wb_dma_status_t wb_dma_ch_check_completion(wb_dma_ch_t *s);

/*
 * Program a channel's registers from a config, without arming it.
 *
 * *§3.2 group 1, configuration.* Completes when CHn_SZ / A0 / AM0 / A1 /
 * AM1 and the RW bits of CHn_CSR reflect ``cfg``; the channel is NOT
 * enabled. Waits for nothing -- straight-line stores, no driver state,
 * callable from any context including with a lock held.
 *
 * Kept alongside ``transfer_single()``, which takes the same config and
 * subsumes this for the common case, for exactly one reason:
 * ``transfer_list()`` needs CHK_SZ programmed BEFORE the chain is armed
 * (§3.3), and a descriptor carries no chunk size.
 *
 * The CSR is written whole rather than read-modify-written, because at this
 * point nothing is running on the channel and a read would consume the
 * read-to-clear status bits for no reason.
 *
 * :param cfg: what to program; capability-gated fields are skipped when the
 *             channel was built without the capability
 */
void wb_dma_ch_configure_channel(wb_dma_ch_t *s, wb_dma_ch_cfg_t cfg);

/*
 * Decode one read of CHn_CSR into a status. The unguarded primitive both
 * layers are built from.
 *
 * Not an operation, and not the API: no in-progress guard, no blocking, no
 * loop. It exists because the guard and the decode are separable concerns
 * and exactly one caller needs the decode without the guard.
 *
 * ``check_completion()``
 *     Guard plus this. The non-blocking API; firmware calls it.
 *
 * ``wait_completion()``
 *     This, in a loop, under a wake. The guard would be wrong inside a loop
 *     -- it is claimed once by the ``*_start()`` and released once by the
 *     operation that started it, not taken and put back on every poll.
 *
 * ``stop_channel()``
 *     This, in a loop, holding no token. Stop is the documented exemption
 *     from the one-operation-per-channel rule, so it has none to release.
 *
 * ERR is tested before DONE because the two are not exclusive: an aborted
 * transfer can retire with both set, and a stop that lands on an
 * already-completed channel certainly does. Reporting ERROR is the
 * conservative reading -- a scenario that expected DONE learns something
 * went wrong, where the reverse order would hide it.
 *
 * .. warning::
 *    Callers outside this component should use ``check_completion()``. PSS
 *    has no visibility control, so this cannot be enforced -- but reaching
 *    past the guard opts out of the only detector for the read-to-clear
 *    hazard, and the read is a side effect every time.
 */
wb_dma_status_t wb_dma_ch_probe_status(wb_dma_ch_t *s);

/*
 * Set or clear the channel's auto-restart bit.
 *
 * *§3.2 group 1, configuration.* Completes when ARS has been updated; waits
 * for nothing.
 *
 * Distinct from ``configure_channel()`` because clearing ARS mid-flight is
 * the documented way to terminate an auto-restarting channel (§3.2.1),
 * invoked on its own against a live channel from a parallel scenario branch.
 * Rewriting the whole register bank to do that would be wrong.
 *
 * It is therefore the TERMINATING EVENT for an auto-restarting
 * ``transfer_single()``: once ARS is clear, the in-flight iteration retires
 * and DONE asserts.
 *
 * .. warning::
 *    A read-modify-write against a live channel, so it shares the hazard
 *    described on ``stop_channel_start()``: the read consumes any pending
 *    read-to-clear status. Enabling ARS before arming is unaffected;
 *    disabling it mid-flight is the exposed case.
 *
 * :param enable: 1 to auto-restart on completion, 0 to stop after the
 *                current iteration
 */
void wb_dma_ch_set_auto_restart(wb_dma_ch_t *s, uint8_t enable);

/*
 * Publish how far a software reader has drained a FIFO in memory.
 *
 * *§3.2 group 1, configuration.* Completes when CHn_SWPTR has been updated
 * -- a channel stalled on the old pointer may resume as a side effect.
 * Waits for nothing.
 *
 * The consumer side of a FIFO in memory (§3.5): the DMA stalls rather than
 * overrun the software reader, and publishing a new pointer un-stalls it. So
 * this is invoked repeatedly during a live transfer, always concurrent with
 * a ``transfer_single()``.
 *
 * Note what that implies about scope: the FIFO's DATA is read on the test
 * writer's own memory path. This operation only publishes how far that
 * reader has got.
 *
 * Requires ``caps.cbuf``, and only means anything with a circular-buffer
 * address mask programmed on the same channel.
 *
 * :param ptr:    the new software pointer
 * :param enable: whether the pointer is honoured at all
 */
void wb_dma_ch_set_software_pointer(wb_dma_ch_t *s, uint32_t ptr, uint8_t enable);

/*
 * Write STOP to abort whatever is running on this channel, and return.
 *
 * *§3.2 group 1.* The non-blocking half of ``stop_channel()``, present on
 * every profile. Completes when STOP has been written -- the abort itself
 * has not necessarily happened yet. Waits for nothing.
 *
 * An abort is reported as an ERROR, not as a clean stop: the device sets ERR
 * on a STOP write (§3.2.2). That is carried into the contract verbatim.
 *
 * **This claims no** :pss:field:`inflight` **token, deliberately.** By
 * definition it aborts a transfer that is still running, so the channel it
 * targets is already holding one. Claiming would report the one case the
 * model explicitly permits as a violation. Stop is the documented exemption
 * from the one-operation-per-channel rule, and the exemption is now visible
 * in the code rather than only in a comment.
 *
 * **Two consequences a firmware caller must know.**
 *
 * The ``write_field`` below IS a read-modify-write: the LRM defines the
 * field-wise write as one (§21.14.1), so the CHn_CSR read is there even
 * though the call no longer spells it out, and it still clears ERR and the
 * interrupt sources. That read happens BEFORE STOP is written, so it can
 * only consume status that was already there -- the abort's own ERR is set
 * afterwards and is still seen by the aborted transfer's poll. What it can
 * lose is a completion that landed in the instant before the abort.
 *
 * Who reports the abort is NOT determined by this model. The aborted
 * transfer polls the same CSR, and whichever read lands first consumes the
 * ERR. On the non-blocking profile the loser's ``check_completion()``
 * answers PENDING forever -- a firmware hang rather than an action that does
 * not retire.
 *
 * There is no ``check_completion()`` pairing for stop: it holds no token, so
 * it has nothing to poll with. A caller aborts, then keeps polling the
 * TRANSFER it aborted, which is the operation that owns the completion.
 *
 * .. note::
 *    Open question (§6.5): is write-1-to-STOP acknowledged before or after
 *    the current WISHBONE cycle retires? That decides whether an abort can
 *    be considered delivered on return, which matters post-silicon.
 */
void wb_dma_ch_stop_channel_start(wb_dma_ch_t *s);

/*
 * Point a channel at a descriptor list and arm it, returning with the chain
 * running.
 *
 * *§3.2 group 3.* The non-blocking half of ``transfer_list()``, present on
 * every profile. Completes when the channel points at the list, external
 * descriptors are enabled, and the channel is armed. Waits for nothing.
 *
 * §3.3's four-step arming procedure IS this function's body, except step 2
 * (chunk size), which must come from a prior ``configure_channel()`` because
 * it outlives any single descriptor. A descriptor carries only src, dst,
 * tot_sz, the increment flags, the interface selects and EOL; mode,
 * priority, ARS, the address masks and CHK_SZ stay whatever the channel
 * registers hold.
 *
 * Unlike ``transfer_single_start()``, this one always has a completion: ARS
 * is documented as meaningless and ignored with external descriptors (§3.3),
 * so ``check_completion()`` is guaranteed to answer DONE or ERROR
 * eventually. Two end-to-end operations differing only in completion
 * contract is why neither subsumes the other -- and the difference was never
 * in the wait.
 *
 * Requires ``caps.ed``. Unlike the other capability-gated operations this
 * reports rather than returning quietly, because it has a completion
 * contract: a silent return would leave the caller waiting for a chain that
 * was never armed.
 *
 * :param head: head of the descriptor chain; must be reachable from
 *              interface 0
 */
void wb_dma_ch_transfer_list_start(wb_dma_ch_t *s, pssc_addr_t head);

/*
 * Program a channel and arm it, returning with the transfer running.
 *
 * *§3.2 group 1.* The non-blocking half of ``transfer_single()``, present on
 * every profile. Completes when the channel is programmed and armed -- NOT
 * when the transfer has moved anything. Waits for nothing.
 *
 * Program, arm, return. The caller then polls ``check_completion()`` until
 * it answers something other than PENDING, or calls ``transfer_single()``,
 * which is exactly this plus the wait. All of the device knowledge is here;
 * the end-to-end layer adds only the loop. That is why a SystemVerilog
 * regression that never calls this directly still tests it.
 *
 * **Two callers' obligations this signature does not encode.**
 *
 * ``mode == WB_DMA_HW_HANDSHAKE``: the transfer cannot complete on its own.
 * Something must be calling ``request_chunk()`` on the matching
 * ``wb_dma_hs_c`` concurrently (§2.2). Splitting arm from wait does not help
 * here -- the missing thing is a second initiator, not a second thread.
 *
 * ``cfg.auto_restart``: the transfer has NO completion event. CSR bit 11
 * sets DONE only once ARS is clear, so nothing this function starts will
 * ever make ``check_completion()`` answer DONE. Someone must clear ARS
 * (``set_auto_restart(0)``) or abort the channel (``stop_channel_start()``).
 * In the end-to-end layer that is a thread that never returns; here it is a
 * loop that never exits, which is a firmware hang rather than a stalled PSS
 * action. Same defect, less visible.
 *
 * Claims :pss:field:`inflight` FIRST, before touching a register, so a start
 * that would be the second on a live channel is reported without having
 * corrupted the configuration of the first.
 *
 * :param cfg: what to program before arming
 */
void wb_dma_ch_transfer_single_start(wb_dma_ch_t *s, wb_dma_ch_cfg_t cfg);

/*
 * Wait until the device may have progressed.
 *
 * The wait PRIMITIVE: the one function in this model whose body differs
 * between execution targets, and the only thing
 * ``wb_dma_cfg_pkg::HAS_EVENT_WAIT`` gates.
 *
 * **Contract: return when the device MAY have progressed.** Not "when it
 * has" -- this reports nothing and decides nothing. Every caller is a loop
 * that re-reads CHn_CSR afterwards and tests its own condition, so a
 * spurious return costs one register read and a late return costs latency.
 * Neither is a defect.
 *
 * This is the seam that lets the OPERATION SURFACE be profile-independent.
 * The two ways to wait have different requirements:
 *
 * ``wake.get()``
 *     Suspend until someone posts. Needs an event source (``notify_irq()``,
 *     hence configured interrupt routing) and a runtime that can suspend a
 *     caller. Costs nothing while waiting.
 *
 * ``yield``
 *     Spin. Needs NOTHING -- every target can spin, including a bare-metal
 *     single-threaded one. Costs the bus a read per iteration and, on a
 *     threaded target, whatever the scheduler charges.
 *
 * Only the first is a capability, so that is what the flag asks about and
 * this is where the answer is consumed. Every operation above it is written
 * once and compiles on both. See ``docs/op-model-c-embedded-design.md``
 * §5.4 and ``docs/target-cfg-contract.md``.
 *
 * .. warning::
 *    ``yield`` is a hint to the SCHEDULER, not to the device, and a backend
 *    spends it however its target charges for waiting. It must NOT be
 *    implemented as a wait on this device's interrupt: that would
 *    reintroduce the routing prerequisite this branch exists to avoid, and
 *    would deadlock the one caller that has no interrupt to wait for. The
 *    contract is stated in full in ``docs/op-model-export-design.md`` §4.4.
 */
void wb_dma_ch_wait_hint(wb_dma_ch_t *s);

#endif /* WB_DMA_H */
