/* Generated by Cython 0.29.32 */

#ifndef __PYX_HAVE_API__pssparser__pssast
#define __PYX_HAVE_API__pssparser__pssast
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"
#include "pssast.h"

static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExecStmt)(PyObject *, pssp::ast::IExecStmt *) = 0;
#define pssast_call_visitExecStmt __pyx_api_f_9pssparser_6pssast_pssast_call_visitExecStmt
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExpr)(PyObject *, pssp::ast::IExpr *) = 0;
#define pssast_call_visitExpr __pyx_api_f_9pssparser_6pssast_pssast_call_visitExpr
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExpr)(PyObject *, pssp::ast::IRefExpr *) = 0;
#define pssast_call_visitRefExpr __pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExpr
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamDeclList)(PyObject *, pssp::ast::ITemplateParamDeclList *) = 0;
#define pssast_call_visitTemplateParamDeclList __pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamDeclList
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamDecl)(PyObject *, pssp::ast::ITemplateParamDecl *) = 0;
#define pssast_call_visitTemplateParamDecl __pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamDecl
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitScopeChild)(PyObject *, pssp::ast::IScopeChild *) = 0;
#define pssast_call_visitScopeChild __pyx_api_f_9pssparser_6pssast_pssast_call_visitScopeChild
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamValueList)(PyObject *, pssp::ast::ITemplateParamValueList *) = 0;
#define pssast_call_visitTemplateParamValueList __pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamValueList
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamValue)(PyObject *, pssp::ast::ITemplateParamValue *) = 0;
#define pssast_call_visitTemplateParamValue __pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamValue
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamTypeValue)(PyObject *, pssp::ast::ITemplateParamTypeValue *) = 0;
#define pssast_call_visitTemplateParamTypeValue __pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamTypeValue
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamExprValue)(PyObject *, pssp::ast::ITemplateParamExprValue *) = 0;
#define pssast_call_visitTemplateParamExprValue __pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamExprValue
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmt)(PyObject *, pssp::ast::IConstraintStmt *) = 0;
#define pssast_call_visitConstraintStmt __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmt
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitScope)(PyObject *, pssp::ast::IScope *) = 0;
#define pssast_call_visitScope __pyx_api_f_9pssparser_6pssast_pssast_call_visitScope
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitNamedScopeChild)(PyObject *, pssp::ast::INamedScopeChild *) = 0;
#define pssast_call_visitNamedScopeChild __pyx_api_f_9pssparser_6pssast_pssast_call_visitNamedScopeChild
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitPackageImportStmt)(PyObject *, pssp::ast::IPackageImportStmt *) = 0;
#define pssast_call_visitPackageImportStmt __pyx_api_f_9pssparser_6pssast_pssast_call_visitPackageImportStmt
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataType)(PyObject *, pssp::ast::IDataType *) = 0;
#define pssast_call_visitDataType __pyx_api_f_9pssparser_6pssast_pssast_call_visitDataType
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExecScope)(PyObject *, pssp::ast::IExecScope *) = 0;
#define pssast_call_visitExecScope __pyx_api_f_9pssparser_6pssast_pssast_call_visitExecScope
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitProceduralStmtDataDeclaration)(PyObject *, pssp::ast::IProceduralStmtDataDeclaration *) = 0;
#define pssast_call_visitProceduralStmtDataDeclaration __pyx_api_f_9pssparser_6pssast_pssast_call_visitProceduralStmtDataDeclaration
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprBin)(PyObject *, pssp::ast::IExprBin *) = 0;
#define pssast_call_visitExprBin __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprBin
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprBitSlice)(PyObject *, pssp::ast::IExprBitSlice *) = 0;
#define pssast_call_visitExprBitSlice __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprBitSlice
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprBool)(PyObject *, pssp::ast::IExprBool *) = 0;
#define pssast_call_visitExprBool __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprBool
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprCast)(PyObject *, pssp::ast::IExprCast *) = 0;
#define pssast_call_visitExprCast __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprCast
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprCompileHas)(PyObject *, pssp::ast::IExprCompileHas *) = 0;
#define pssast_call_visitExprCompileHas __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprCompileHas
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprCond)(PyObject *, pssp::ast::IExprCond *) = 0;
#define pssast_call_visitExprCond __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprCond
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprDomainOpenRangeList)(PyObject *, pssp::ast::IExprDomainOpenRangeList *) = 0;
#define pssast_call_visitExprDomainOpenRangeList __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprDomainOpenRangeList
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprDomainOpenRangeValue)(PyObject *, pssp::ast::IExprDomainOpenRangeValue *) = 0;
#define pssast_call_visitExprDomainOpenRangeValue __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprDomainOpenRangeValue
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprHierarchicalId)(PyObject *, pssp::ast::IExprHierarchicalId *) = 0;
#define pssast_call_visitExprHierarchicalId __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprHierarchicalId
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprId)(PyObject *, pssp::ast::IExprId *) = 0;
#define pssast_call_visitExprId __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprId
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprIn)(PyObject *, pssp::ast::IExprIn *) = 0;
#define pssast_call_visitExprIn __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprIn
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprMemberPathElem)(PyObject *, pssp::ast::IExprMemberPathElem *) = 0;
#define pssast_call_visitExprMemberPathElem __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprMemberPathElem
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprNumber)(PyObject *, pssp::ast::IExprNumber *) = 0;
#define pssast_call_visitExprNumber __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprNumber
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprAggregateLiteral)(PyObject *, pssp::ast::IExprAggregateLiteral *) = 0;
#define pssast_call_visitExprAggregateLiteral __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprAggregateLiteral
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprOpenRangeList)(PyObject *, pssp::ast::IExprOpenRangeList *) = 0;
#define pssast_call_visitExprOpenRangeList __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprOpenRangeList
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprOpenRangeValue)(PyObject *, pssp::ast::IExprOpenRangeValue *) = 0;
#define pssast_call_visitExprOpenRangeValue __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprOpenRangeValue
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPath)(PyObject *, pssp::ast::IExprRefPath *) = 0;
#define pssast_call_visitExprRefPath __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPath
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathElem)(PyObject *, pssp::ast::IExprRefPathElem *) = 0;
#define pssast_call_visitExprRefPathElem __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathElem
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathStaticRooted)(PyObject *, pssp::ast::IExprRefPathStaticRooted *) = 0;
#define pssast_call_visitExprRefPathStaticRooted __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathStaticRooted
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprStaticRefPath)(PyObject *, pssp::ast::IExprStaticRefPath *) = 0;
#define pssast_call_visitExprStaticRefPath __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprStaticRefPath
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprString)(PyObject *, pssp::ast::IExprString *) = 0;
#define pssast_call_visitExprString __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprString
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprSubscript)(PyObject *, pssp::ast::IExprSubscript *) = 0;
#define pssast_call_visitExprSubscript __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprSubscript
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprUnary)(PyObject *, pssp::ast::IExprUnary *) = 0;
#define pssast_call_visitExprUnary __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprUnary
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitMethodParameterList)(PyObject *, pssp::ast::IMethodParameterList *) = 0;
#define pssast_call_visitMethodParameterList __pyx_api_f_9pssparser_6pssast_pssast_call_visitMethodParameterList
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTypeIdentifier)(PyObject *, pssp::ast::ITypeIdentifier *) = 0;
#define pssast_call_visitTypeIdentifier __pyx_api_f_9pssparser_6pssast_pssast_call_visitTypeIdentifier
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTypeIdentifierElem)(PyObject *, pssp::ast::ITypeIdentifierElem *) = 0;
#define pssast_call_visitTypeIdentifierElem __pyx_api_f_9pssparser_6pssast_pssast_call_visitTypeIdentifierElem
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExprTypeScopeGlobal)(PyObject *, pssp::ast::IRefExprTypeScopeGlobal *) = 0;
#define pssast_call_visitRefExprTypeScopeGlobal __pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExprTypeScopeGlobal
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExprTypeScopeContext)(PyObject *, pssp::ast::IRefExprTypeScopeContext *) = 0;
#define pssast_call_visitRefExprTypeScopeContext __pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExprTypeScopeContext
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExprScopeIndex)(PyObject *, pssp::ast::IRefExprScopeIndex *) = 0;
#define pssast_call_visitRefExprScopeIndex __pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExprScopeIndex
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateGenericTypeParamDecl)(PyObject *, pssp::ast::ITemplateGenericTypeParamDecl *) = 0;
#define pssast_call_visitTemplateGenericTypeParamDecl __pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateGenericTypeParamDecl
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateCategoryTypeParamDecl)(PyObject *, pssp::ast::ITemplateCategoryTypeParamDecl *) = 0;
#define pssast_call_visitTemplateCategoryTypeParamDecl __pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateCategoryTypeParamDecl
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateValueParamDecl)(PyObject *, pssp::ast::ITemplateValueParamDecl *) = 0;
#define pssast_call_visitTemplateValueParamDecl __pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateValueParamDecl
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintBlock)(PyObject *, pssp::ast::IConstraintBlock *) = 0;
#define pssast_call_visitConstraintBlock __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintBlock
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintScope)(PyObject *, pssp::ast::IConstraintScope *) = 0;
#define pssast_call_visitConstraintScope __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintScope
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtDefault)(PyObject *, pssp::ast::IConstraintStmtDefault *) = 0;
#define pssast_call_visitConstraintStmtDefault __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtDefault
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtDefaultDisable)(PyObject *, pssp::ast::IConstraintStmtDefaultDisable *) = 0;
#define pssast_call_visitConstraintStmtDefaultDisable __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtDefaultDisable
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtExpr)(PyObject *, pssp::ast::IConstraintStmtExpr *) = 0;
#define pssast_call_visitConstraintStmtExpr __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtExpr
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtField)(PyObject *, pssp::ast::IConstraintStmtField *) = 0;
#define pssast_call_visitConstraintStmtField __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtField
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtIf)(PyObject *, pssp::ast::IConstraintStmtIf *) = 0;
#define pssast_call_visitConstraintStmtIf __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtIf
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtUnique)(PyObject *, pssp::ast::IConstraintStmtUnique *) = 0;
#define pssast_call_visitConstraintStmtUnique __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtUnique
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitGlobalScope)(PyObject *, pssp::ast::IGlobalScope *) = 0;
#define pssast_call_visitGlobalScope __pyx_api_f_9pssparser_6pssast_pssast_call_visitGlobalScope
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitNamedScope)(PyObject *, pssp::ast::INamedScope *) = 0;
#define pssast_call_visitNamedScope __pyx_api_f_9pssparser_6pssast_pssast_call_visitNamedScope
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitPackageScope)(PyObject *, pssp::ast::IPackageScope *) = 0;
#define pssast_call_visitPackageScope __pyx_api_f_9pssparser_6pssast_pssast_call_visitPackageScope
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeArray)(PyObject *, pssp::ast::IDataTypeArray *) = 0;
#define pssast_call_visitDataTypeArray __pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeArray
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeBool)(PyObject *, pssp::ast::IDataTypeBool *) = 0;
#define pssast_call_visitDataTypeBool __pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeBool
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeChandle)(PyObject *, pssp::ast::IDataTypeChandle *) = 0;
#define pssast_call_visitDataTypeChandle __pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeChandle
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeEnum)(PyObject *, pssp::ast::IDataTypeEnum *) = 0;
#define pssast_call_visitDataTypeEnum __pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeEnum
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeInt)(PyObject *, pssp::ast::IDataTypeInt *) = 0;
#define pssast_call_visitDataTypeInt __pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeInt
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeString)(PyObject *, pssp::ast::IDataTypeString *) = 0;
#define pssast_call_visitDataTypeString __pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeString
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeUserDefined)(PyObject *, pssp::ast::IDataTypeUserDefined *) = 0;
#define pssast_call_visitDataTypeUserDefined __pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeUserDefined
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathContext)(PyObject *, pssp::ast::IExprRefPathContext *) = 0;
#define pssast_call_visitExprRefPathContext __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathContext
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathStatic)(PyObject *, pssp::ast::IExprRefPathStatic *) = 0;
#define pssast_call_visitExprRefPathStatic __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathStatic
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprSignedNumber)(PyObject *, pssp::ast::IExprSignedNumber *) = 0;
#define pssast_call_visitExprSignedNumber __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprSignedNumber
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprUnsignedNumber)(PyObject *, pssp::ast::IExprUnsignedNumber *) = 0;
#define pssast_call_visitExprUnsignedNumber __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprUnsignedNumber
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtForall)(PyObject *, pssp::ast::IConstraintStmtForall *) = 0;
#define pssast_call_visitConstraintStmtForall __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtForall
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtForeach)(PyObject *, pssp::ast::IConstraintStmtForeach *) = 0;
#define pssast_call_visitConstraintStmtForeach __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtForeach
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtImplication)(PyObject *, pssp::ast::IConstraintStmtImplication *) = 0;
#define pssast_call_visitConstraintStmtImplication __pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtImplication
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitTypeScope)(PyObject *, pssp::ast::ITypeScope *) = 0;
#define pssast_call_visitTypeScope __pyx_api_f_9pssparser_6pssast_pssast_call_visitTypeScope
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathStaticFunc)(PyObject *, pssp::ast::IExprRefPathStaticFunc *) = 0;
#define pssast_call_visitExprRefPathStaticFunc __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathStaticFunc
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathSuper)(PyObject *, pssp::ast::IExprRefPathSuper *) = 0;
#define pssast_call_visitExprRefPathSuper __pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathSuper
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitAction)(PyObject *, pssp::ast::IAction *) = 0;
#define pssast_call_visitAction __pyx_api_f_9pssparser_6pssast_pssast_call_visitAction
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitComponent)(PyObject *, pssp::ast::IComponent *) = 0;
#define pssast_call_visitComponent __pyx_api_f_9pssparser_6pssast_pssast_call_visitComponent
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitStruct)(PyObject *, pssp::ast::IStruct *) = 0;
#define pssast_call_visitStruct __pyx_api_f_9pssparser_6pssast_pssast_call_visitStruct
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitState)(PyObject *, pssp::ast::IState *) = 0;
#define pssast_call_visitState __pyx_api_f_9pssparser_6pssast_pssast_call_visitState
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitStream)(PyObject *, pssp::ast::IStream *) = 0;
#define pssast_call_visitStream __pyx_api_f_9pssparser_6pssast_pssast_call_visitStream
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitBuffer)(PyObject *, pssp::ast::IBuffer *) = 0;
#define pssast_call_visitBuffer __pyx_api_f_9pssparser_6pssast_pssast_call_visitBuffer
static PyObject *(*__pyx_api_f_9pssparser_6pssast_pssast_call_visitResource)(PyObject *, pssp::ast::IResource *) = 0;
#define pssast_call_visitResource __pyx_api_f_9pssparser_6pssast_pssast_call_visitResource
#if !defined(__Pyx_PyIdentifier_FromString)
#if PY_MAJOR_VERSION < 3
  #define __Pyx_PyIdentifier_FromString(s) PyString_FromString(s)
#else
  #define __Pyx_PyIdentifier_FromString(s) PyUnicode_FromString(s)
#endif
#endif

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, (char *)"__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
#if PY_VERSION_HEX >= 0x02070000
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
#else
    {const char *desc, *s1, *s2;
    desc = (const char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    s1 = desc; s2 = sig;
    while (*s1 != '\0' && *s1 == *s2) { s1++; s2++; }
    if (*s1 != *s2) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    tmp.p = PyCObject_AsVoidPtr(cobj);}
#endif
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif


static int import_pssparser__pssast(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("pssparser.pssast");
  if (!module) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExecStmt", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExecStmt, "PyObject *(PyObject *, pssp::ast::IExecStmt *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExpr", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExpr, "PyObject *(PyObject *, pssp::ast::IExpr *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitRefExpr", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExpr, "PyObject *(PyObject *, pssp::ast::IRefExpr *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTemplateParamDeclList", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamDeclList, "PyObject *(PyObject *, pssp::ast::ITemplateParamDeclList *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTemplateParamDecl", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamDecl, "PyObject *(PyObject *, pssp::ast::ITemplateParamDecl *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitScopeChild", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitScopeChild, "PyObject *(PyObject *, pssp::ast::IScopeChild *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTemplateParamValueList", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamValueList, "PyObject *(PyObject *, pssp::ast::ITemplateParamValueList *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTemplateParamValue", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamValue, "PyObject *(PyObject *, pssp::ast::ITemplateParamValue *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTemplateParamTypeValue", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamTypeValue, "PyObject *(PyObject *, pssp::ast::ITemplateParamTypeValue *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTemplateParamExprValue", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateParamExprValue, "PyObject *(PyObject *, pssp::ast::ITemplateParamExprValue *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintStmt", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmt, "PyObject *(PyObject *, pssp::ast::IConstraintStmt *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitScope", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitScope, "PyObject *(PyObject *, pssp::ast::IScope *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitNamedScopeChild", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitNamedScopeChild, "PyObject *(PyObject *, pssp::ast::INamedScopeChild *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitPackageImportStmt", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitPackageImportStmt, "PyObject *(PyObject *, pssp::ast::IPackageImportStmt *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitDataType", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataType, "PyObject *(PyObject *, pssp::ast::IDataType *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExecScope", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExecScope, "PyObject *(PyObject *, pssp::ast::IExecScope *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitProceduralStmtDataDeclaration", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitProceduralStmtDataDeclaration, "PyObject *(PyObject *, pssp::ast::IProceduralStmtDataDeclaration *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprBin", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprBin, "PyObject *(PyObject *, pssp::ast::IExprBin *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprBitSlice", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprBitSlice, "PyObject *(PyObject *, pssp::ast::IExprBitSlice *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprBool", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprBool, "PyObject *(PyObject *, pssp::ast::IExprBool *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprCast", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprCast, "PyObject *(PyObject *, pssp::ast::IExprCast *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprCompileHas", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprCompileHas, "PyObject *(PyObject *, pssp::ast::IExprCompileHas *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprCond", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprCond, "PyObject *(PyObject *, pssp::ast::IExprCond *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprDomainOpenRangeList", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprDomainOpenRangeList, "PyObject *(PyObject *, pssp::ast::IExprDomainOpenRangeList *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprDomainOpenRangeValue", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprDomainOpenRangeValue, "PyObject *(PyObject *, pssp::ast::IExprDomainOpenRangeValue *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprHierarchicalId", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprHierarchicalId, "PyObject *(PyObject *, pssp::ast::IExprHierarchicalId *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprId", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprId, "PyObject *(PyObject *, pssp::ast::IExprId *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprIn", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprIn, "PyObject *(PyObject *, pssp::ast::IExprIn *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprMemberPathElem", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprMemberPathElem, "PyObject *(PyObject *, pssp::ast::IExprMemberPathElem *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprNumber", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprNumber, "PyObject *(PyObject *, pssp::ast::IExprNumber *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprAggregateLiteral", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprAggregateLiteral, "PyObject *(PyObject *, pssp::ast::IExprAggregateLiteral *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprOpenRangeList", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprOpenRangeList, "PyObject *(PyObject *, pssp::ast::IExprOpenRangeList *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprOpenRangeValue", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprOpenRangeValue, "PyObject *(PyObject *, pssp::ast::IExprOpenRangeValue *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprRefPath", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPath, "PyObject *(PyObject *, pssp::ast::IExprRefPath *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprRefPathElem", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathElem, "PyObject *(PyObject *, pssp::ast::IExprRefPathElem *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprRefPathStaticRooted", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathStaticRooted, "PyObject *(PyObject *, pssp::ast::IExprRefPathStaticRooted *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprStaticRefPath", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprStaticRefPath, "PyObject *(PyObject *, pssp::ast::IExprStaticRefPath *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprString", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprString, "PyObject *(PyObject *, pssp::ast::IExprString *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprSubscript", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprSubscript, "PyObject *(PyObject *, pssp::ast::IExprSubscript *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprUnary", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprUnary, "PyObject *(PyObject *, pssp::ast::IExprUnary *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitMethodParameterList", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitMethodParameterList, "PyObject *(PyObject *, pssp::ast::IMethodParameterList *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTypeIdentifier", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTypeIdentifier, "PyObject *(PyObject *, pssp::ast::ITypeIdentifier *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTypeIdentifierElem", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTypeIdentifierElem, "PyObject *(PyObject *, pssp::ast::ITypeIdentifierElem *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitRefExprTypeScopeGlobal", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExprTypeScopeGlobal, "PyObject *(PyObject *, pssp::ast::IRefExprTypeScopeGlobal *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitRefExprTypeScopeContext", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExprTypeScopeContext, "PyObject *(PyObject *, pssp::ast::IRefExprTypeScopeContext *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitRefExprScopeIndex", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitRefExprScopeIndex, "PyObject *(PyObject *, pssp::ast::IRefExprScopeIndex *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTemplateGenericTypeParamDecl", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateGenericTypeParamDecl, "PyObject *(PyObject *, pssp::ast::ITemplateGenericTypeParamDecl *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTemplateCategoryTypeParamDecl", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateCategoryTypeParamDecl, "PyObject *(PyObject *, pssp::ast::ITemplateCategoryTypeParamDecl *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTemplateValueParamDecl", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTemplateValueParamDecl, "PyObject *(PyObject *, pssp::ast::ITemplateValueParamDecl *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintBlock", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintBlock, "PyObject *(PyObject *, pssp::ast::IConstraintBlock *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintScope", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintScope, "PyObject *(PyObject *, pssp::ast::IConstraintScope *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintStmtDefault", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtDefault, "PyObject *(PyObject *, pssp::ast::IConstraintStmtDefault *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintStmtDefaultDisable", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtDefaultDisable, "PyObject *(PyObject *, pssp::ast::IConstraintStmtDefaultDisable *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintStmtExpr", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtExpr, "PyObject *(PyObject *, pssp::ast::IConstraintStmtExpr *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintStmtField", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtField, "PyObject *(PyObject *, pssp::ast::IConstraintStmtField *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintStmtIf", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtIf, "PyObject *(PyObject *, pssp::ast::IConstraintStmtIf *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintStmtUnique", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtUnique, "PyObject *(PyObject *, pssp::ast::IConstraintStmtUnique *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitGlobalScope", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitGlobalScope, "PyObject *(PyObject *, pssp::ast::IGlobalScope *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitNamedScope", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitNamedScope, "PyObject *(PyObject *, pssp::ast::INamedScope *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitPackageScope", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitPackageScope, "PyObject *(PyObject *, pssp::ast::IPackageScope *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitDataTypeArray", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeArray, "PyObject *(PyObject *, pssp::ast::IDataTypeArray *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitDataTypeBool", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeBool, "PyObject *(PyObject *, pssp::ast::IDataTypeBool *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitDataTypeChandle", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeChandle, "PyObject *(PyObject *, pssp::ast::IDataTypeChandle *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitDataTypeEnum", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeEnum, "PyObject *(PyObject *, pssp::ast::IDataTypeEnum *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitDataTypeInt", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeInt, "PyObject *(PyObject *, pssp::ast::IDataTypeInt *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitDataTypeString", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeString, "PyObject *(PyObject *, pssp::ast::IDataTypeString *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitDataTypeUserDefined", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitDataTypeUserDefined, "PyObject *(PyObject *, pssp::ast::IDataTypeUserDefined *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprRefPathContext", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathContext, "PyObject *(PyObject *, pssp::ast::IExprRefPathContext *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprRefPathStatic", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathStatic, "PyObject *(PyObject *, pssp::ast::IExprRefPathStatic *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprSignedNumber", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprSignedNumber, "PyObject *(PyObject *, pssp::ast::IExprSignedNumber *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprUnsignedNumber", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprUnsignedNumber, "PyObject *(PyObject *, pssp::ast::IExprUnsignedNumber *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintStmtForall", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtForall, "PyObject *(PyObject *, pssp::ast::IConstraintStmtForall *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintStmtForeach", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtForeach, "PyObject *(PyObject *, pssp::ast::IConstraintStmtForeach *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitConstraintStmtImplication", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitConstraintStmtImplication, "PyObject *(PyObject *, pssp::ast::IConstraintStmtImplication *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitTypeScope", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitTypeScope, "PyObject *(PyObject *, pssp::ast::ITypeScope *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprRefPathStaticFunc", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathStaticFunc, "PyObject *(PyObject *, pssp::ast::IExprRefPathStaticFunc *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitExprRefPathSuper", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitExprRefPathSuper, "PyObject *(PyObject *, pssp::ast::IExprRefPathSuper *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitAction", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitAction, "PyObject *(PyObject *, pssp::ast::IAction *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitComponent", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitComponent, "PyObject *(PyObject *, pssp::ast::IComponent *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitStruct", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitStruct, "PyObject *(PyObject *, pssp::ast::IStruct *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitState", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitState, "PyObject *(PyObject *, pssp::ast::IState *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitStream", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitStream, "PyObject *(PyObject *, pssp::ast::IStream *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitBuffer", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitBuffer, "PyObject *(PyObject *, pssp::ast::IBuffer *)") < 0) goto bad;
  if (__Pyx_ImportFunction(module, "pssast_call_visitResource", (void (**)(void))&__pyx_api_f_9pssparser_6pssast_pssast_call_visitResource, "PyObject *(PyObject *, pssp::ast::IResource *)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__pssparser__pssast */
