/* Generated by Cython 0.29.32 */

#ifndef __PYX_HAVE__pssparser__pssast
#define __PYX_HAVE__pssparser__pssast

#include "Python.h"

#ifndef __PYX_HAVE_API__pssparser__pssast

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *pssast_call_visitExecStmt(PyObject *, pssp::ast::IExecStmt *);
__PYX_EXTERN_C PyObject *pssast_call_visitExpr(PyObject *, pssp::ast::IExpr *);
__PYX_EXTERN_C PyObject *pssast_call_visitRefExpr(PyObject *, pssp::ast::IRefExpr *);
__PYX_EXTERN_C PyObject *pssast_call_visitTemplateParamDeclList(PyObject *, pssp::ast::ITemplateParamDeclList *);
__PYX_EXTERN_C PyObject *pssast_call_visitTemplateParamDecl(PyObject *, pssp::ast::ITemplateParamDecl *);
__PYX_EXTERN_C PyObject *pssast_call_visitScopeChild(PyObject *, pssp::ast::IScopeChild *);
__PYX_EXTERN_C PyObject *pssast_call_visitTemplateParamValueList(PyObject *, pssp::ast::ITemplateParamValueList *);
__PYX_EXTERN_C PyObject *pssast_call_visitTemplateParamValue(PyObject *, pssp::ast::ITemplateParamValue *);
__PYX_EXTERN_C PyObject *pssast_call_visitTemplateParamTypeValue(PyObject *, pssp::ast::ITemplateParamTypeValue *);
__PYX_EXTERN_C PyObject *pssast_call_visitTemplateParamExprValue(PyObject *, pssp::ast::ITemplateParamExprValue *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintStmt(PyObject *, pssp::ast::IConstraintStmt *);
__PYX_EXTERN_C PyObject *pssast_call_visitScope(PyObject *, pssp::ast::IScope *);
__PYX_EXTERN_C PyObject *pssast_call_visitNamedScopeChild(PyObject *, pssp::ast::INamedScopeChild *);
__PYX_EXTERN_C PyObject *pssast_call_visitPackageImportStmt(PyObject *, pssp::ast::IPackageImportStmt *);
__PYX_EXTERN_C PyObject *pssast_call_visitDataType(PyObject *, pssp::ast::IDataType *);
__PYX_EXTERN_C PyObject *pssast_call_visitExecScope(PyObject *, pssp::ast::IExecScope *);
__PYX_EXTERN_C PyObject *pssast_call_visitProceduralStmtDataDeclaration(PyObject *, pssp::ast::IProceduralStmtDataDeclaration *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprBin(PyObject *, pssp::ast::IExprBin *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprBitSlice(PyObject *, pssp::ast::IExprBitSlice *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprBool(PyObject *, pssp::ast::IExprBool *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprCast(PyObject *, pssp::ast::IExprCast *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprCompileHas(PyObject *, pssp::ast::IExprCompileHas *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprCond(PyObject *, pssp::ast::IExprCond *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprDomainOpenRangeList(PyObject *, pssp::ast::IExprDomainOpenRangeList *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprDomainOpenRangeValue(PyObject *, pssp::ast::IExprDomainOpenRangeValue *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprHierarchicalId(PyObject *, pssp::ast::IExprHierarchicalId *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprId(PyObject *, pssp::ast::IExprId *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprIn(PyObject *, pssp::ast::IExprIn *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprMemberPathElem(PyObject *, pssp::ast::IExprMemberPathElem *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprNumber(PyObject *, pssp::ast::IExprNumber *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprAggregateLiteral(PyObject *, pssp::ast::IExprAggregateLiteral *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprOpenRangeList(PyObject *, pssp::ast::IExprOpenRangeList *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprOpenRangeValue(PyObject *, pssp::ast::IExprOpenRangeValue *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprRefPath(PyObject *, pssp::ast::IExprRefPath *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprRefPathElem(PyObject *, pssp::ast::IExprRefPathElem *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprRefPathStaticRooted(PyObject *, pssp::ast::IExprRefPathStaticRooted *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprStaticRefPath(PyObject *, pssp::ast::IExprStaticRefPath *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprString(PyObject *, pssp::ast::IExprString *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprSubscript(PyObject *, pssp::ast::IExprSubscript *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprUnary(PyObject *, pssp::ast::IExprUnary *);
__PYX_EXTERN_C PyObject *pssast_call_visitMethodParameterList(PyObject *, pssp::ast::IMethodParameterList *);
__PYX_EXTERN_C PyObject *pssast_call_visitTypeIdentifier(PyObject *, pssp::ast::ITypeIdentifier *);
__PYX_EXTERN_C PyObject *pssast_call_visitTypeIdentifierElem(PyObject *, pssp::ast::ITypeIdentifierElem *);
__PYX_EXTERN_C PyObject *pssast_call_visitRefExprTypeScopeGlobal(PyObject *, pssp::ast::IRefExprTypeScopeGlobal *);
__PYX_EXTERN_C PyObject *pssast_call_visitRefExprTypeScopeContext(PyObject *, pssp::ast::IRefExprTypeScopeContext *);
__PYX_EXTERN_C PyObject *pssast_call_visitRefExprScopeIndex(PyObject *, pssp::ast::IRefExprScopeIndex *);
__PYX_EXTERN_C PyObject *pssast_call_visitTemplateGenericTypeParamDecl(PyObject *, pssp::ast::ITemplateGenericTypeParamDecl *);
__PYX_EXTERN_C PyObject *pssast_call_visitTemplateCategoryTypeParamDecl(PyObject *, pssp::ast::ITemplateCategoryTypeParamDecl *);
__PYX_EXTERN_C PyObject *pssast_call_visitTemplateValueParamDecl(PyObject *, pssp::ast::ITemplateValueParamDecl *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintBlock(PyObject *, pssp::ast::IConstraintBlock *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintScope(PyObject *, pssp::ast::IConstraintScope *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintStmtDefault(PyObject *, pssp::ast::IConstraintStmtDefault *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintStmtDefaultDisable(PyObject *, pssp::ast::IConstraintStmtDefaultDisable *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintStmtExpr(PyObject *, pssp::ast::IConstraintStmtExpr *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintStmtField(PyObject *, pssp::ast::IConstraintStmtField *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintStmtIf(PyObject *, pssp::ast::IConstraintStmtIf *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintStmtUnique(PyObject *, pssp::ast::IConstraintStmtUnique *);
__PYX_EXTERN_C PyObject *pssast_call_visitGlobalScope(PyObject *, pssp::ast::IGlobalScope *);
__PYX_EXTERN_C PyObject *pssast_call_visitNamedScope(PyObject *, pssp::ast::INamedScope *);
__PYX_EXTERN_C PyObject *pssast_call_visitPackageScope(PyObject *, pssp::ast::IPackageScope *);
__PYX_EXTERN_C PyObject *pssast_call_visitDataTypeArray(PyObject *, pssp::ast::IDataTypeArray *);
__PYX_EXTERN_C PyObject *pssast_call_visitDataTypeBool(PyObject *, pssp::ast::IDataTypeBool *);
__PYX_EXTERN_C PyObject *pssast_call_visitDataTypeChandle(PyObject *, pssp::ast::IDataTypeChandle *);
__PYX_EXTERN_C PyObject *pssast_call_visitDataTypeEnum(PyObject *, pssp::ast::IDataTypeEnum *);
__PYX_EXTERN_C PyObject *pssast_call_visitDataTypeInt(PyObject *, pssp::ast::IDataTypeInt *);
__PYX_EXTERN_C PyObject *pssast_call_visitDataTypeString(PyObject *, pssp::ast::IDataTypeString *);
__PYX_EXTERN_C PyObject *pssast_call_visitDataTypeUserDefined(PyObject *, pssp::ast::IDataTypeUserDefined *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprRefPathContext(PyObject *, pssp::ast::IExprRefPathContext *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprRefPathStatic(PyObject *, pssp::ast::IExprRefPathStatic *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprSignedNumber(PyObject *, pssp::ast::IExprSignedNumber *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprUnsignedNumber(PyObject *, pssp::ast::IExprUnsignedNumber *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintStmtForall(PyObject *, pssp::ast::IConstraintStmtForall *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintStmtForeach(PyObject *, pssp::ast::IConstraintStmtForeach *);
__PYX_EXTERN_C PyObject *pssast_call_visitConstraintStmtImplication(PyObject *, pssp::ast::IConstraintStmtImplication *);
__PYX_EXTERN_C PyObject *pssast_call_visitTypeScope(PyObject *, pssp::ast::ITypeScope *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprRefPathStaticFunc(PyObject *, pssp::ast::IExprRefPathStaticFunc *);
__PYX_EXTERN_C PyObject *pssast_call_visitExprRefPathSuper(PyObject *, pssp::ast::IExprRefPathSuper *);
__PYX_EXTERN_C PyObject *pssast_call_visitAction(PyObject *, pssp::ast::IAction *);
__PYX_EXTERN_C PyObject *pssast_call_visitComponent(PyObject *, pssp::ast::IComponent *);
__PYX_EXTERN_C PyObject *pssast_call_visitStruct(PyObject *, pssp::ast::IStruct *);
__PYX_EXTERN_C PyObject *pssast_call_visitState(PyObject *, pssp::ast::IState *);
__PYX_EXTERN_C PyObject *pssast_call_visitStream(PyObject *, pssp::ast::IStream *);
__PYX_EXTERN_C PyObject *pssast_call_visitBuffer(PyObject *, pssp::ast::IBuffer *);
__PYX_EXTERN_C PyObject *pssast_call_visitResource(PyObject *, pssp::ast::IResource *);

#endif /* !__PYX_HAVE_API__pssparser__pssast */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpssast(void);
#else
PyMODINIT_FUNC PyInit_pssast(void);
#endif

#endif /* !__PYX_HAVE__pssparser__pssast */
