"""Emission entry point for the ``cpp-progseq`` target.

Assembles the single generated header (namespace -> value unions -> reg-group
classes -> export/import APIs -> component class) and copies the core
``pssc_reg.hpp`` alongside.
"""
from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import List

from ..progseq_model import walk_tree, CompKind

_log = logging.getLogger("pssc.progseq.cpp")
_CORE_HEADER = "pssc_reg.hpp"


def _resolver(ctx):
    tm = getattr(ctx, "type_map", {}) or {}

    def resolve(dtype):
        ref = getattr(dtype, "ref_name", None)
        if ref and ref in tm:
            return tm[ref]
        return dtype

    return resolve


def _cpp_core_dir() -> Path:
    from ...cli import cpp_core_dir
    return cpp_core_dir()


def generate(ctx, root, namespace: str, out_dir: Path, *,
             dispatch: str = "virtual", copy_core: bool = True) -> List[Path]:
    if dispatch == "template":
        raise NotImplementedError(
            "cpp-progseq --dispatch template is not yet implemented; "
            "use --dispatch virtual (the default)")

    tree = walk_tree(root, _resolver(ctx))
    _log.info("cpp-progseq: root=%s namespace=%s components: %d regular, %d reg-group",
              tree.name, namespace, _count(tree, CompKind.REGULAR),
              _count(tree, CompKind.REG_GROUP))

    from .lower_reg_model import lower_value_unions, lower_reg_groups
    from .lower_progseq import lower_component

    cls = namespace          # class/interface prefix == namespace
    unions = lower_value_unions(root)
    groups = lower_reg_groups(root)
    comp = lower_component(root, cls)

    guard = f"{namespace.upper()}_HPP"
    h: List[str] = []
    h.append("// Generated by pssc (cpp-progseq) -- do not edit.")
    h.append(f"// Root component: {tree.name}; dispatch: {dispatch}.")
    h.append("// Value layouts assume little-endian bitfield allocation"
             " (gcc/clang, x86/ARM, LP64/LLP64).")
    h.append(f"#ifndef {guard}")
    h.append(f"#define {guard}")
    h.append("")
    for inc in ("<array>", "<cstdint>", "<memory>", "<utility>"):
        h.append(f"#include {inc}")
    h.append(f'#include "{_CORE_HEADER}"')
    h.append("")
    h.append(f"namespace {namespace} {{")
    h.append("")
    for section in (unions, groups, comp):
        h.append(section)
        h.append("")
    h.append(f"}}  // namespace {namespace}")
    h.append("")
    h.append(f"#endif  // {guard}")
    h.append("")

    out_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    hpp = out_dir / f"{namespace}.hpp"
    hpp.write_text("\n".join(h))
    written.append(hpp)

    if copy_core:
        dst = out_dir / _CORE_HEADER
        shutil.copy2(str(_cpp_core_dir() / _CORE_HEADER), str(dst))
        written.append(dst)

    _log.info("cpp-progseq: wrote %d file(s): %s",
              len(written), ", ".join(p.name for p in written))
    return written


def _count(node, kind, seen=None) -> int:
    seen = seen if seen is not None else set()
    if id(node) in seen:
        return 0
    seen.add(id(node))
    n = 1 if node.kind == kind else 0
    for c in node.children:
        n += _count(c, kind, seen)
    return n
