"""Emission entry point for the ``sv-progseq`` target.

Assembles the generated SV package for the root component's subtree and writes
it to the output directory (copying the core ``pssc_reg_pkg.sv`` alongside).

Current coverage: register model (value structs + reg-group classes). Export/
import API, impl, adapter, and factory land in Phases 4-5.
"""
from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import List

from .progseq_model import walk_tree, CompKind
from .sv.lower_reg_model import lower_register_model
from .sv.lower_api_types import lower_api_types
from .sv.lower_progseq import (lower_component_api, emit_import_api,
                               emit_component, emit_subcomponent_class,
                               uses_yield)

_log = logging.getLogger("pssc.progseq")


def _resolver(ctx):
    """Return resolve(dtype)->defining-component-datatype (follows DataTypeRef)."""
    tm = getattr(ctx, "type_map", {}) or {}

    def resolve(dtype):
        ref = getattr(dtype, "ref_name", None)
        if ref and ref in tm:
            return tm[ref]
        return dtype

    return resolve


def _core_pkg_path() -> Path:
    from ..cli import sv_core_dir, SV_CORE_PKG
    return sv_core_dir() / SV_CORE_PKG


def generate(ctx, root, pkg_name: str, out_dir: Path, copy_core: bool = True,
             reg_fields: str = "named") -> List[Path]:
    """Generate the SV programming-sequence package for ``root``.

    ``reg_fields`` controls how a folded masked write is SPELLED, not what it
    does. ``named`` restores the field name the mask came from
    (``csr.write_field(WB_DMA_CH_CSR_ars, ..)``); ``folded`` emits the literal
    (mask, value) pair the reduction produced, which is what every other backend
    consumes and what this target emitted before the naming existed. The two
    generate identical bus traffic -- ``folded`` exists so the collapsed form
    stays reachable for diffing against the C target and for debugging a
    suspected naming bug.

    Returns the list of written file paths.
    """
    # Legality FIRST, before any file is opened. Two reasons beyond reporting
    # every offender in one run: a failure part-way through emission would leave
    # a truncated artifact that a later dv-flow run treats as up-to-date, and
    # `driver.compile` checks `ctx.errors` only BEFORE the target runs -- so a
    # target that accumulates errors has to raise for itself.
    from .validate_calls import validate_calls
    from ..driver import CompileError
    bad = validate_calls(root, ctx, "op-model-sv")
    if bad:
        raise CompileError(
            f"{len(bad)} call(s) cannot be lowered to SystemVerilog", bad)

    tree = walk_tree(root, _resolver(ctx))
    _log.info("progseq: root=%s package=%s components: %d regular, %d reg-group",
              tree.name, pkg_name, _count(tree, CompKind.REGULAR),
              _count(tree, CompKind.REG_GROUP))

    # Regular components (root + regular sub-components), parents after children
    # so a parent's accessors can refer to already-declared child APIs.
    regular = _regular_components(tree)

    # The register model spans the whole tree: a per-channel bank is reached
    # through its channel component, not through the root's own fields, so
    # lowering only the root's registers emitted an empty file for any model
    # that puts registers where the operations that use them are.
    reg_body, struct_names, group_names = lower_register_model(
        [c.dtype for c in regular])

    # One namer per component: receiver paths resolve against that component's
    # own fields. `folded` leaves them all None, which disables the rewrite.
    from .sv.reg_field_names import FieldNamer
    type_map = getattr(ctx, "type_map", {}) or {}
    namers = ({id(c.dtype): FieldNamer(c.dtype, type_map) for c in regular}
              if reg_fields == "named" else {})

    _assert_api_is_not_empty(regular)

    pkg = []
    pkg.append(f"// Generated by pssc (sv-progseq) -- do not edit.")
    pkg.append(f"// Root component: {tree.name}")
    pkg.append("")
    pkg.append(f"package {pkg_name};")
    pkg.append("  import pssc_reg_pkg::*;")
    pkg.append("")
    pkg.append(reg_body)
    api_types = lower_api_types([c.dtype for c in regular], _value_structs(regular))
    if api_types:
        pkg.append(api_types)
    for comp in regular:
        pkg.append(f"  // ----- Programming API: {comp.name} -----")
        pkg.append(lower_component_api(comp.dtype))
        pkg.append("")
    # SV has no forward references inside a package, so declaration order is
    # part of the output being correct, not a matter of taste:
    #   export interfaces -> import interface -> sub-component classes -> root.
    # The root constructs the sub-components and the sub-components take the
    # import interface as their bus.
    pkg.append(f"  // ----- Import API (root: {tree.name}) -----")
    needs_yield = uses_yield([c.dtype for c in regular])
    pkg.append(emit_import_api(root, needs_yield))
    pkg.append("")
    for comp in regular:
        if comp.dtype is root:
            continue
        pkg.append(f"  // ----- Implementation: {comp.name} -----")
        pkg.append(emit_subcomponent_class(comp.dtype, root,
                                           namers.get(id(comp.dtype))))
        pkg.append("")
    pkg.append(f"  // ----- Component handle/factory: {tree.name} -----")
    pkg.append(emit_component(root, needs_yield, namers.get(id(root))))
    pkg.append("")
    pkg.append(f"endpackage")
    pkg.append("")

    out_dir.mkdir(parents=True, exist_ok=True)

    # COMPILATION ORDER, not creation order. The returned list is what a build
    # system hands the compiler (dv-flow's `classify_outputs` preserves it), and
    # the generated package uses `addr_handle_t` and `pss_mem_if` from the core
    # package -- so the core has to come first. Emitting the generated package
    # first still lints standalone, and fails only once something else compiles
    # both together.
    written: List[Path] = []

    if copy_core:
        core_src = _core_pkg_path()
        core_dst = out_dir / core_src.name
        shutil.copy2(str(core_src), str(core_dst))
        written.append(core_dst)

    pkg_file = out_dir / f"{pkg_name}.sv"
    pkg_file.write_text("\n".join(pkg))
    written.append(pkg_file)

    _log.info("progseq: wrote %d file(s): %s",
              len(written), ", ".join(p.name for p in written))
    return written


def _value_structs(regular) -> List[object]:
    """Register value structs across the tree -- emitted by the register model,
    so the API-type pass must not emit them a second time."""
    from .progseq_model import collect_reg_groups, collect_value_structs
    groups = []
    seen = set()
    for c in regular:
        for g in collect_reg_groups(c.dtype):
            if id(g) not in seen:
                seen.add(id(g))
                groups.append(g)
    return collect_value_structs(groups)


def _assert_api_is_not_empty(regular) -> None:
    """An export API with no operations at all is an error, not a warning.

    This is the shape every front-end defect in this generator's history took:
    the model translated, the package was written, the run exited 0, and the
    file contained interface classes with nothing in them. Nobody reads a
    warning printed by a successful build.
    """
    from .progseq_model import func_kind, FuncKind
    total = sum(1 for c in regular for fn in c.dtype.functions
                if func_kind(fn) is FuncKind.EXPORT_OP)
    if total == 0:
        names = ", ".join(c.name for c in regular)
        raise ValueError(
            "progseq: the generated export API would contain zero operations "
            f"(components walked: {names or '(none)'}). Either --root names a "
            "component with no operations, or the operations did not survive "
            "translation -- check that `extend component` bodies reached the IR.")


def _regular_components(tree, seen=None, out=None):
    """Post-order list of unique regular CompNodes (children before parents)."""
    seen = seen if seen is not None else set()
    out = out if out is not None else []
    if id(tree) in seen:
        return out
    seen.add(id(tree))
    for c in tree.children:
        _regular_components(c, seen, out)
    if tree.kind == CompKind.REGULAR:
        out.append(tree)
    return out


def _count(node, kind, seen=None) -> int:
    seen = seen if seen is not None else set()
    if id(node) in seen:
        return 0
    seen.add(id(node))
    n = 1 if node.kind == kind else 0
    for c in node.children:
        n += _count(c, kind, seen)
    return n
