"""Emission entry point for the ``sv-progseq`` target.

Assembles the generated SV package for the root component's subtree and writes
it to the output directory (copying the core ``pssc_reg_pkg.sv`` alongside).

Current coverage: register model (value structs + reg-group classes). Export/
import API, impl, adapter, and factory land in Phases 4-5.
"""
from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import List

from .progseq_model import walk_tree, CompKind
from .sv.lower_reg_model import lower_register_model
from .sv.lower_progseq import lower_component_api, lower_root_glue

_log = logging.getLogger("pssc.progseq")


def _resolver(ctx):
    """Return resolve(dtype)->defining-component-datatype (follows DataTypeRef)."""
    tm = getattr(ctx, "type_map", {}) or {}

    def resolve(dtype):
        ref = getattr(dtype, "ref_name", None)
        if ref and ref in tm:
            return tm[ref]
        return dtype

    return resolve


def _core_pkg_path() -> Path:
    from ..cli import sv_core_dir, SV_CORE_PKG
    return sv_core_dir() / SV_CORE_PKG


def generate(ctx, root, pkg_name: str, out_dir: Path, copy_core: bool = True) -> List[Path]:
    """Generate the SV programming-sequence package for ``root``.

    Returns the list of written file paths.
    """
    tree = walk_tree(root, _resolver(ctx))
    _log.info("progseq: root=%s package=%s components: %d regular, %d reg-group",
              tree.name, pkg_name, _count(tree, CompKind.REGULAR),
              _count(tree, CompKind.REG_GROUP))

    reg_body, struct_names, group_names = lower_register_model(root)

    # Regular components (root + regular sub-components), parents after children
    # so a parent's accessors can refer to already-declared child APIs.
    regular = _regular_components(tree)

    pkg = []
    pkg.append(f"// Generated by pssc (sv-progseq) -- do not edit.")
    pkg.append(f"// Root component: {tree.name}")
    pkg.append("")
    pkg.append(f"package {pkg_name};")
    pkg.append("  import pssc_reg_pkg::*;")
    pkg.append("")
    pkg.append(reg_body)
    for comp in regular:
        pkg.append(f"  // ----- Programming API: {comp.name} -----")
        pkg.append(lower_component_api(comp.dtype))
        pkg.append("")
    pkg.append(f"  // ----- Import API + component handle/factory (root: {tree.name}) -----")
    pkg.append(lower_root_glue(root))
    pkg.append("")
    pkg.append(f"endpackage")
    pkg.append("")

    out_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []

    pkg_file = out_dir / f"{pkg_name}.sv"
    pkg_file.write_text("\n".join(pkg))
    written.append(pkg_file)

    if copy_core:
        core_src = _core_pkg_path()
        core_dst = out_dir / core_src.name
        shutil.copy2(str(core_src), str(core_dst))
        written.append(core_dst)

    _log.info("progseq: wrote %d file(s): %s",
              len(written), ", ".join(p.name for p in written))
    return written


def _regular_components(tree, seen=None, out=None):
    """Post-order list of unique regular CompNodes (children before parents)."""
    seen = seen if seen is not None else set()
    out = out if out is not None else []
    if id(tree) in seen:
        return out
    seen.add(id(tree))
    for c in tree.children:
        _regular_components(c, seen, out)
    if tree.kind == CompKind.REGULAR:
        out.append(tree)
    return out


def _count(node, kind, seen=None) -> int:
    seen = seen if seen is not None else set()
    if id(node) in seen:
        return 0
    seen.add(id(node))
    n = 1 if node.kind == kind else 0
    for c in node.children:
        n += _count(c, kind, seen)
    return n
