"""Emission entry point for the ``sv-progseq`` target.

Assembles the generated SV package for the root component's subtree and writes
it to the output directory (copying the core ``pssc_reg_pkg.sv`` alongside).

Current coverage: register model (value structs + reg-group classes). Export/
import API, impl, adapter, and factory land in Phases 4-5.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import List

from . import op_model as om
from .progseq_model import CompKind
from .sv.lower_reg_model import lower_register_model
from .sv.lower_api_types import lower_api_types
from .sv.lower_progseq import (lower_component_api, emit_import_api,
                               emit_component, emit_subcomponent_class,
                               uses_yield)

_log = logging.getLogger("pssc.progseq")


#: The core SV package the generated package imports. `ProgSeqTarget` copies it
#: (via `OpModelTarget.install_core`); this module only names it.
SV_CORE_PKG = "pssc_reg_pkg.sv"


def generate(model, pkg_name: str, reg_fields: str = "named") -> List[Path]:
    """Emit the SV programming-sequence package for an elaborated ``model``.

    ``reg_fields`` controls how a folded masked write is SPELLED, not what it
    does. ``named`` restores the field name the mask came from
    (``csr.write_field(WB_DMA_CH_CSR_ars, ..)``); ``folded`` emits the literal
    (mask, value) pair the reduction produced, which is what every other backend
    consumes and what this target emitted before the naming existed. The two
    generate identical bus traffic -- ``folded`` exists so the collapsed form
    stays reachable for diffing against the C target and for debugging a
    suspected naming bug.

    The walk, the component order, the register collection and the legality
    gate all happened before this was called, and copying the core package
    happens after -- see `OpModelTarget`. What is left here is SystemVerilog.

    Returns the list of written file paths.
    """
    ctx, root, tree = model.ctx, model.root, model.tree
    out_dir = model.out_dir
    _log.info("progseq: root=%s package=%s components: %d regular, %d reg-group",
              tree.name, pkg_name, om.count(tree, CompKind.REGULAR),
              om.count(tree, CompKind.REG_GROUP))

    # Regular components, parents after children so a parent's accessors can
    # refer to already-declared child APIs.
    regular = model.components

    # The register model spans the whole tree: a per-channel bank is reached
    # through its channel component, not through the root's own fields, so
    # lowering only the root's registers emitted an empty file for any model
    # that puts registers where the operations that use them are.
    reg_body, struct_names, group_names = lower_register_model(
        model.comp_dtypes)

    # One namer per component: receiver paths resolve against that component's
    # own fields. `folded` leaves them all None, which disables the rewrite.
    from .sv.reg_field_names import FieldNamer
    type_map = getattr(ctx, "type_map", {}) or {}
    namers = ({id(c.dtype): FieldNamer(c.dtype, type_map) for c in regular}
              if reg_fields == "named" else {})

    pkg = []
    pkg.append(f"// Generated by pssc (sv-progseq) -- do not edit.")
    pkg.append(f"// Root component: {tree.name}")
    pkg.append("")
    pkg.append(f"package {pkg_name};")
    pkg.append("  import pssc_reg_pkg::*;")
    pkg.append("")
    pkg.append(reg_body)
    api_types = lower_api_types(model.comp_dtypes, model.value_structs,
                                model.ctor_names)
    if api_types:
        pkg.append(api_types)
    for comp in regular:
        pkg.append(f"  // ----- Programming API: {comp.name} -----")
        pkg.append(lower_component_api(comp.dtype, model.ctor_names))
        pkg.append("")
    # SV has no forward references inside a package, so declaration order is
    # part of the output being correct, not a matter of taste:
    #   export interfaces -> import interface -> sub-component classes -> root.
    # The root constructs the sub-components and the sub-components take the
    # import interface as their bus.
    pkg.append(f"  // ----- Import API (root: {tree.name}) -----")
    needs_yield = uses_yield(model.comp_dtypes)
    pkg.append(emit_import_api(root, needs_yield, model.ctor_names))
    pkg.append("")
    for comp in regular:
        if comp.dtype is root:
            continue
        pkg.append(f"  // ----- Implementation: {comp.name} -----")
        pkg.append(emit_subcomponent_class(comp.dtype, root,
                                           namers.get(id(comp.dtype)),
                                           model.ctor_names))
        pkg.append("")
    pkg.append(f"  // ----- Component handle/factory: {tree.name} -----")
    pkg.append(emit_component(root, needs_yield, namers.get(id(root)),
                              model.ctor_names))
    pkg.append("")
    pkg.append(f"endpackage")
    pkg.append("")

    out_dir.mkdir(parents=True, exist_ok=True)

    pkg_file = out_dir / f"{pkg_name}.sv"
    pkg_file.write_text("\n".join(pkg))
    written: List[Path] = [pkg_file]

    _log.info("progseq: wrote %s", pkg_file.name)
    return written
