"""The built-in C operation-model backend, as an object.

`COpModelBackend` assembles the generated header (+ optional ``.c``) from the
lowered pieces. It exists so that a mid-weight extension -- one that needs
something the style policy did not think to ask about, like an extra member on
the handle struct or a generated register-map header beside the API -- can
subclass and override one method instead of copying a 200-line function.

Two properties make that usable rather than merely possible, and both are
tested:

  1. **Every method returns text.** Only `generate` and `write_files` touch the
     filesystem, so a subclass can call `super()` and wrap, prepend, filter or
     reindent the result. A method that wrote as a side effect could not be
     wrapped, which is the whole point of the mid-weight path.
  2. **One instance per generation.** `prepare()` computes the derived state
     (prefixes, component order, the accessor map, the bodies) once and the
     section emitters read it; nothing recomputes a lowering to answer a
     question about it.

Design: docs/generator-style-extensions-design.md §2.6.1.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import List

from ..overridable import overridable, overridable_attr
from ..sections import Section
from .style import CSettings, CStylePolicy, coerce as _coerce_style

_log = logging.getLogger("pssc.progseq.c")


#: The one thing that can be stubbed, and the reason nothing else can.
STUBS_BANNER = """\
/* Generated by pssc (c-progseq) -- WEAK STUBS. Link this ONLY until the
 * platform side exists.
 *
 * `pssc_message` is stubbed because DOING NOTHING IS A CORRECT IMPLEMENTATION
 * of it: a driver that logs nothing still drives the device correctly. That is
 * the entire test for whether something belongs in this file, and nothing else
 * in the seam passes it.
 *
 * NOT STUBBED, and never will be:
 *
 *   * the memory primitives (pssc_r32/pssc_w32/...). A bus access that silently
 *     succeeds is a driver that reports the device is fine because it never
 *     talked to it -- the single worst failure this generator could produce.
 *     An unresolved symbol at link is the correct outcome.
 *   * model-declared imports (`import target/solve function`). Same rule: an
 *     empty `plat_delay_us` is a delay that does not delay, and the poll loop
 *     above it becomes a spin that can never be right. What each one must do
 *     is stated by the model, not guessable here.
 *
 * WEAK, so a real definition anywhere else in the link wins with no build
 * change and no warning. Under a toolchain with no weak-symbol support this
 * file defines a strong symbol -- so remove it from the link rather than
 * expecting it to be overridden.
 */
#include <stdarg.h>

#if defined(__GNUC__) || defined(__clang__)
#  define PSSC_WEAK __attribute__((weak))
#else
#  define PSSC_WEAK
#endif

PSSC_WEAK void pssc_message(const char *fmt, ...) { (void)fmt; }
"""


class COpModelBackend:
    """The built-in C backend. Subclass to change what you need."""

    #: The collaborators, swapped wholesale by a subclass that needs different
    #: body rendering or a different default policy. Instantiated through the
    #: attribute rather than named directly, which is the only thing that makes
    #: the swap take effect (P6a.T3).
    style_cls = CStylePolicy

    def __init__(self, style=None):
        self.style = _coerce_style(style) if style is not None \
            else self.style_cls()
        self.model = None
        self.settings = None

    #: The body emitter used for operation bodies. `None` means "the module's
    #: own", resolved in `prepare()` so a subclass sees a class, not None.
    body_emitter_cls = None

    #: The two collaborators are part of the published surface as much as the
    #: methods are, and a class attribute cannot carry a decorator.
    #: `style_cls` is stable -- a policy is the tier-A contract and is already
    #: pinned by `test_style_policy.py`. `body_emitter_cls` is provisional:
    #: `_BodyEmitter`'s method set is what Phase 7's `BodyWalker` is expected
    #: to replace, and publishing it as stable now would promise a shape that
    #: is under active redesign.
    overridable_attrs = {
        "style_cls": overridable_attr(since="0.1", stability="stable"),
        "body_emitter_cls": overridable_attr(since="0.1",
                                             stability="provisional"),
    }

    # -- derived state ------------------------------------------------------

    @overridable(since='0.1', stability='provisional')
    def prepare(self, model, s: CSettings) -> None:
        """Compute everything the section emitters read, once.

        The bodies are lowered here even for a header-only build, because that
        is where they end up: `impl` is a string that lands either in the .c or
        inside the include guard, and which one is not a difference in what gets
        generated.
        """
        from .lower_progseq import Prefixes, parse_prefix_map, _BodyEmitter
        from .lower_reg_model import accessor_map

        self.model, self.settings = model, s
        self.prefixes = Prefixes(model, s.prefix,
                                 parse_prefix_map(list(s.prefix_map)))
        self.comps = model.comp_dtypes_root_first
        self.imports = model.imports
        self.emitter_cls = self.body_emitter_cls or _BodyEmitter
        self.accs = accessor_map(self.comps, self.prefixes, self.style)
        _log.info("c-progseq: prefixes: %s",
                  ", ".join(f"{getattr(c, 'name', '?')}->{self.prefixes[c]}"
                            for c in self.comps))
        self.impl = self.emit_impl(model, s)

    # -- sections -----------------------------------------------------------
    #
    # Each returns the LINES it contributes, including its own trailing blank,
    # so the assembled header is the concatenation of the section list and
    # nothing else decides layout.

    @overridable(since='0.1', stability='stable')
    def emit_banner(self, model, s: CSettings) -> List[str]:
        """The header's opening comment block, already comment-delimited.

        Returns LINES. The policy writes it (`style.banner`); override this to
        put something in front of the policy's, which is where a company
        prologue belongs when it must precede even the generated-file notice.
        """
        return list(self.style.banner(model, s))

    @overridable(since='0.1', stability='stable', pairs_with=['emit_guard_close'])
    def emit_guard_open(self, model, s: CSettings) -> List[str]:
        """`#ifndef`/`#define` opening the header's include guard.

        Returns LINES. Paired with `emit_guard_close`: the two agree on one
        macro name, so overriding either alone gives a header that never ends
        or one whose halves disagree. `#pragma once` is the usual reason to
        override, and it needs both (the close returning nothing).
        """
        guard = self.style.include_guard(s.prefix)
        return [f"#ifndef {guard}", f"#define {guard}", ""]

    @overridable(since='0.1', stability='stable', pairs_with=['emit_guard_open'])
    def emit_guard_close(self, model, s: CSettings) -> List[str]:
        """`#endif` closing the include guard. Returns LINES.

        Paired with `emit_guard_open` -- see there.
        """
        return [f"#endif /* {self.style.include_guard(s.prefix)} */", ""]

    @overridable(since='0.1', stability='stable')
    def emit_includes(self, model, s: CSettings) -> List[str]:
        """The header's `#include` block. Returns LINES.

        The order is the policy's (`style.include_order`), which is where an
        extra include belongs if it is a NAMING decision. Override this when
        the include set itself differs -- a house runtime header that must
        precede the seam, for instance.
        """
        return list(self.style.include_order(model, s)) + [""]

    @overridable(since='0.1', stability='stable', pairs_with=['emit_value_unions'])
    def emit_api_types(self, model, s: CSettings) -> List[str]:
        """The enums and plain structs the API mentions.

        BEFORE the handles and the prototypes, both of which name them: C has
        no forward reference for a type used by value.
        """
        from .lower_api_types import lower_api_types
        return self._block(lower_api_types(self.comps, model.value_structs,
                                           model.ctor_names))

    @overridable(since='0.1', stability='stable', pairs_with=['emit_api_types'])
    def emit_value_unions(self, model, s: CSettings) -> List[str]:
        """The register VALUE structs/unions. Returns LINES.

        Paired with `emit_api_types`, which deliberately skips these: the two
        partition one set of type declarations between them, and an overlap
        declares one type twice -- incompatibly, since the layouts differ.
        """
        from .lower_reg_model import lower_value_unions
        return self._block(lower_value_unions(self.comps,
                                              reg_style=s.reg_style))

    @overridable(since='0.1', stability='stable')
    def emit_handles(self, model, s: CSettings) -> List[str]:
        """The component handle structs (`<prefix>_t`) and their accessors.

        Returns LINES. The struct an extension most often wants a member on --
        override, call `super()`, and splice. The MEMBERS are the model's:
        adding one that the generated bodies do not maintain gives a field
        that is always zero.
        """
        from .lower_progseq import lower_handles
        return self._block(lower_handles(model, self.prefixes,
                                         link_style=s.link_style,
                                         style=self.style))

    @overridable(since='0.1', stability='provisional')
    def emit_accessors(self, model, s: CSettings) -> List[str]:
        """The inline register accessors (`<base>_read_val`, ...).

        Returns LINES. Provisional: `mem_access.py` owns both the naming scheme
        and the access rendering, and this method is the DEFINITION side of a
        pairing whose call side is inside the body emitter -- renaming here
        without renaming there is a link error, and the surface does not yet
        state that as a pair it can check.
        """
        from .lower_reg_model import lower_accessors
        return self._block(lower_accessors(self.comps, self.prefixes,
                                           link_style=s.link_style,
                                           style=self.style))

    @overridable(since='0.1', stability='provisional')
    def emit_import_decls(self, model, s: CSettings) -> List[str]:
        """C4.1. Read off the model's own declarations, so adding a platform
        hook is a model edit and not a generator edit.

        Emitted BEFORE the bodies that call them and before the export API, so
        a generated call is checked against a declaration rather than becoming
        an implicit one (which C99 rejects, but only with -Werror).
        """
        from .lower_progseq import lower_imports
        return self._block(lower_imports(self.imports))

    @overridable(since='0.1', stability='stable')
    def emit_decls(self, model, s: CSettings) -> List[str]:
        """The exported function prototypes and the lifecycle declarations.

        Returns LINES. Under `--header-only` these carry `static inline` and
        the definitions follow in the same file; otherwise they are what the
        caller compiles against. A signature changed here must be changed in
        `emit_operation` too -- C will say so, loudly, which is why the two are
        not a checked pair.
        """
        from .lower_progseq import lower_decls
        return self._block(lower_decls(model, self.prefixes,
                                       link_style=s.link_style,
                                       static_inline=s.header_only,
                                       lifecycle=s.lifecycle,
                                       style=self.style))

    @overridable(since='0.1', stability='provisional')
    def emit_impl_inline(self, model, s: CSettings) -> List[str]:
        """The bodies, for a header-only build. Empty otherwise."""
        return self._block(self.impl) if s.header_only else []

    @overridable(since='0.1', stability='stable')
    def emit_operation(self, fn, ctx) -> List[str]:
        """ONE exported operation -- doc comment, signature, body, brace.

        The per-operation seam, and the one a mid-weight extension reaches for
        most: a trace call in every operation, a lock around every operation, a
        house prologue. Wrapping this gets the whole rendered function as lines,
        which `body_emitter_cls` cannot -- that swaps how STATEMENTS render and
        never sees the signature.

        ``ctx`` is an `OpCtx`: the component, its prefix, the qualifier and the
        body emitter in force. A record, so that a new lowering detail does not
        change this signature and break every override.
        """
        from .lower_progseq import lower_operation
        return lower_operation(fn, ctx)

    @overridable(since='0.1', stability='provisional')
    def emit_impl(self, model, s: CSettings) -> str:
        """Lifecycle + operation bodies. Text, wherever it ends up."""
        from .lower_progseq import lower_impl
        return lower_impl(model, self.prefixes,
                          emit_operation=self.emit_operation,
                          link_style=s.link_style,
                          static_inline=s.header_only,
                          reg_style=s.reg_style,
                          yield_mode=s.yield_mode,
                          match_default=s.match_default,
                          message_style=s.message_style,
                          lifecycle=s.lifecycle,
                          imports=self.imports,
                          style=self.style,
                          accs=self.accs,
                          emitter_cls=self.emitter_cls)

    @staticmethod
    def _block(text: str) -> List[str]:
        """A section's text plus its separating blank line -- or nothing at all
        when the section is empty, which is why the blank belongs to the
        section rather than to the assembler."""
        return [text, ""] if text else []

    # -- files --------------------------------------------------------------

    @overridable(since='0.1', stability='stable')
    def header_text(self, model, s: CSettings) -> str:
        """The whole header, as text: `header_sections()` assembled.

        Override to post-process the finished file (a reformatter, a license
        stamp on every line); to change WHAT is in it, override a section or
        the section list instead -- this method cannot tell them apart.
        """
        return self.assemble(self.header_sections(model, s), model, s)

    @overridable(since='0.1', stability='provisional')
    def assemble(self, sections, model, s: CSettings) -> str:
        """A file is the concatenation of its sections and nothing else.

        No separator, no trailing fixup: anything the assembler added would be
        layout that `header_sections()` does not show, which is exactly what a
        subclass reading the list would then get wrong.
        """
        out: List[str] = []
        for section in sections:
            out += section.emit(model, s)
        return "\n".join(out)

    @overridable(since='0.1', stability='stable')
    def header_sections(self, model, s: CSettings):
        """The header's named, ordered sections.

        ORDER is the backend's business, not a policy's: C has no forward
        reference for a type used by value, so api_types precedes the handles
        that hold them and the prototypes that pass them, and the imports
        precede the export API that may call them. A subclass reorders at its
        own risk; it inserts and replaces freely.
        """
        return [
            Section("banner",      self.emit_banner),
            Section("guard_open",  self.emit_guard_open),
            Section("includes",    self.emit_includes),
            Section("api_types",   self.emit_api_types),
            Section("reg_values",  self.emit_value_unions),
            Section("handles",     self.emit_handles),
            Section("accessors",   self.emit_accessors),
            Section("imports",     self.emit_import_decls),
            Section("decls",       self.emit_decls),
            Section("impl",        self.emit_impl_inline),
            Section("guard_close", self.emit_guard_close),
        ]

    @overridable(since='0.1', stability='stable')
    def impl_sections(self, model, s: CSettings):
        """The ``.c`` file's sections. Fewer, and still a list: the company
        prologue an extension wants to add goes at the top of a generated
        source file at least as often as it goes in the header."""
        return [
            Section("banner",   self.emit_impl_banner),
            Section("includes", self.emit_impl_includes),
            Section("impl",     self.emit_impl_body),
        ]

    @overridable(since='0.1', stability='stable')
    def emit_impl_banner(self, model, s: CSettings) -> List[str]:
        """The generated ``.c``'s opening comment. Returns LINES."""
        return ["/* Generated by pssc (c-progseq) -- do not edit. */"]

    @overridable(since='0.1', stability='stable')
    def emit_impl_includes(self, model, s: CSettings) -> List[str]:
        """The generated ``.c``'s `#include` block. Returns LINES.

        Separate from the header's: something the bodies need and no caller
        should see belongs here (`--include-impl`).
        """
        return list(self.style.impl_includes(model, s)) + [""]

    @overridable(since='0.1', stability='provisional')
    def emit_impl_body(self, model, s: CSettings) -> List[str]:
        """The lowered bodies, as the ``.c``'s main section. Returns LINES.

        This is placement, not content: the text is `emit_impl`'s, computed
        once in `prepare`. Wrap `emit_impl` or `emit_operation` to change what
        the bodies SAY.
        """
        return [self.impl, ""]

    @overridable(since='0.1', stability='stable')
    def impl_text(self, model, s: CSettings) -> str:
        """The whole generated ``.c``, as text: `impl_sections()` assembled.

        Empty-string is not a legitimate return: `generate` decides whether
        there is a ``.c`` at all, from `--header-only` and whether anything was
        lowered.
        """
        return self.assemble(self.impl_sections(model, s), model, s)

    @overridable(since='0.1', stability='stable')
    def stubs_text(self, model, s: CSettings) -> str:
        """The optional `<prefix>_stubs.c`, as text.

        Only `pssc_message` is stubbed, and the file's own banner states the
        rule for what may ever join it: doing nothing must be a CORRECT
        implementation. An override that stubs a memory primitive or a
        model-declared import produces a driver that silently does not drive.
        """
        return STUBS_BANNER

    @overridable(since='0.1', stability='stable')
    def emit_extra_files(self, model, s: CSettings):
        """`{filename: text}` for anything a subclass wants beside the API --
        a register-map header, a linker fragment, a doc page. Empty here.

        TEXT, not paths, like every other `emit_*`: the writing stays in
        `write_files` so a subclass cannot half-produce a directory, and so an
        extra file is reported to the build system through the same list as the
        API it accompanies.
        """
        return {}

    # -- the only two places that write ------------------------------------

    def generate(self, model, s: CSettings) -> List[Path]:
        """Write the API, and return the paths IN COMPILATION ORDER.

        The order is a contract, not an artifact of dict insertion. It is:
        the header, the ``.c``, the stubs, then the extras -- each artifact
        after the one it depends on, and the extras last because an extra file
        may include the generated header while nothing generated includes an
        extra. The seam headers the target copies come after all of it
        (`c_progseq_tgt.emit`): a C header is found by name, so the copy has no
        compilation order to honour and stays out of the way of the list a
        build system reads first.
        """
        self.prepare(model, s)
        files = {self.style.header_name(s.prefix): self.header_text(model, s)}
        if not s.header_only and self.impl:
            files[self.style.impl_name(s.prefix)] = self.impl_text(model, s)
        if s.emit_stubs:
            files[self.style.stubs_name(s.prefix)] = self.stubs_text(model, s)
        for name, text in self.emit_extra_files(model, s).items():
            if name in files:
                raise ValueError(
                    f"emit_extra_files returned '{name}', which is already "
                    f"generated by this backend. An extra file that overwrites "
                    f"the API silently replaces it -- rename it, or override "
                    f"the method that produces it")
            files[name] = text
        return self.write_files(model.out_dir, files)

    @overridable(since='0.1', stability='provisional')
    def write_files(self, out_dir: Path, files) -> List[Path]:
        """Write `{name: text}` into ``out_dir``; return the paths written.

        The only method here that touches the filesystem, and the reason every
        other one returns text. Override to write somewhere else, to write
        atomically, or to skip a file whose content has not changed -- the
        RETURNED LIST is what the target reports to the build system, so a file
        left unwritten must still appear in it.
        """
        out_dir.mkdir(parents=True, exist_ok=True)
        written = []
        for name, text in files.items():
            path = out_dir / name
            path.write_text(text)
            written.append(path)
        _log.info("c-progseq: wrote %d file(s): %s",
                  len(written), ", ".join(p.name for p in written))
        return written
