"""Emission entry point for the ``c-progseq`` target.

Assembles the generated C header (+ optional ``.c``) for the root component's
subtree and writes it to the output directory, copying the selected core seam
header(s) alongside so the directory is self-contained.

Phase 3 ships the skeleton (walk + seam copy + header banner); the register
model (Phase 4) and export API / bodies (Phase 5) fill the sections.
"""
from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import List

from ..progseq_model import walk_tree, CompKind

_log = logging.getLogger("pssc.progseq.c")

#: Core seam header(s) copied per link style. pssc_mem.h is always needed.
_SEAM_HEADERS = {
    "vtable": ["pssc_mem.h", "pssc_mem_vtable.h"],
    "direct": ["pssc_mem.h", "pssc_mem_direct.h"],
    "mmio":   ["pssc_mem.h", "pssc_mem_mmio.h"],
}
#: The style-specific header the generated <prefix>.h #includes.
_SEAM_INCLUDE = {
    "vtable": "pssc_mem_vtable.h",
    "direct": "pssc_mem_direct.h",
    "mmio":   "pssc_mem_mmio.h",
}


def _resolver(ctx):
    """Return resolve(dtype)->defining-component-datatype (follows DataTypeRef)."""
    tm = getattr(ctx, "type_map", {}) or {}

    def resolve(dtype):
        ref = getattr(dtype, "ref_name", None)
        if ref and ref in tm:
            return tm[ref]
        return dtype

    return resolve


def _c_core_dir() -> Path:
    from ...cli import c_core_dir
    return c_core_dir()


def generate(ctx, root, prefix: str, out_dir: Path, *,
             link_style: str = "vtable", reg_style: str = "bitfields",
             header_only: bool = False, copy_core: bool = True) -> List[Path]:
    """Generate the C programming-sequence API for ``root``.

    Returns the list of written file paths.
    """
    tree = walk_tree(root, _resolver(ctx))
    _log.info("c-progseq: root=%s prefix=%s link=%s reg=%s components: %d regular, %d reg-group",
              tree.name, prefix, link_style, reg_style,
              _count(tree, CompKind.REGULAR), _count(tree, CompKind.REG_GROUP))

    from .lower_reg_model import lower_value_unions, lower_accessors
    from .lower_progseq import emit_handle, lower_decls, lower_impl

    seam_inc = _SEAM_INCLUDE[link_style]
    unions = lower_value_unions(root, reg_style=reg_style)
    handle = emit_handle(prefix, link_style=link_style)
    accessors = lower_accessors(root, prefix, link_style=link_style)
    # In header-only mode the bodies live in the header as `static inline`, which
    # are self-declaring -- emitting separate extern prototypes would clash.
    decls = "" if header_only else lower_decls(root, prefix, link_style=link_style)
    impl = lower_impl(root, prefix, link_style=link_style,
                      static_inline=header_only, reg_style=reg_style)

    guard = f"{prefix.upper()}_H"
    h: List[str] = []
    h.append(f"/* Generated by pssc (c-progseq) -- do not edit. */")
    h.append(f"/* Root component: {tree.name}; link-style: {link_style}. */")
    h.append(f"/* Register value layouts assume little-endian bitfield allocation"
             f" (gcc/clang, x86/ARM, LP64/LLP64). */")
    h.append(f"#ifndef {guard}")
    h.append(f"#define {guard}")
    h.append("")
    h.append("#include <stdint.h>")
    if header_only:
        h.append("#include <stdlib.h>")    # bodies (create/destroy) live here
    h.append(f'#include "{seam_inc}"')
    h.append("")
    for section in (unions, handle, accessors, decls):
        if section:
            h.append(section)
            h.append("")
    if header_only and impl:
        h.append(impl)
        h.append("")
    h.append(f"#endif /* {guard} */")
    h.append("")

    out_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []

    hdr = out_dir / f"{prefix}.h"
    hdr.write_text("\n".join(h))
    written.append(hdr)

    if not header_only and impl:
        c: List[str] = []
        c.append(f"/* Generated by pssc (c-progseq) -- do not edit. */")
        c.append(f'#include "{prefix}.h"')
        c.append("#include <stdlib.h>")
        c.append("")
        c.append(impl)
        c.append("")
        src = out_dir / f"{prefix}.c"
        src.write_text("\n".join(c))
        written.append(src)

    if copy_core:
        core = _c_core_dir()
        for name in _SEAM_HEADERS[link_style]:
            dst = out_dir / name
            shutil.copy2(str(core / name), str(dst))
            written.append(dst)

    _log.info("c-progseq: wrote %d file(s): %s",
              len(written), ", ".join(p.name for p in written))
    return written


def _count(node, kind, seen=None) -> int:
    seen = seen if seen is not None else set()
    if id(node) in seen:
        return 0
    seen.add(id(node))
    n = 1 if node.kind == kind else 0
    for c in node.children:
        n += _count(c, kind, seen)
    return n
