name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-linux:
    runs-on: 'ubuntu-latest'
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
        matrix:
            include:
            - pyversion: 'cp37-cp37m'
            - pyversion: 'cp38-cp38'
            - pyversion: 'cp39-cp39'
            - pyversion: 'cp310-cp310'
            - pyversion: 'cp311-cp311'
            - pyversion: 'cp312-cp312'
    steps:
      - uses: actions/checkout@v1
      - name: Fetch python build dependencies
        run: |
          yum update -y
          yum install -y glibc-static 
          yum install -y java-11-openjdk-devel uuid-devel libuuid-devel
          py=${{ matrix.pyversion }}
          /opt/python/${py}/bin/python -m pip install ivpm
      - name: Fetch source dependencies
        run: |
          py=${{ matrix.pyversion }}
          /opt/python/$py/bin/python -m ivpm update -a
          ./packages/python/bin/python -m pip install ninja wheel cython ivpm twine auditwheel
      - name: Build packages
        run: |
          echo "BUILD_NUM=$GITHUB_RUN_ID" >> python/zsp_parser/__build_num__.py
          ./packages/python/bin/python setup.py bdist_wheel
      - name: Audit Wheels
        run: |
          export LD_LIBRARY_PATH=`pwd`/build/lib:`pwd`/build/lib64
          for whl in dist/*.whl; do
              ./packages/python/bin/auditwheel -v show $whl
              ./packages/python/bin/auditwheel -v repair $whl
              rm $whl
          done
          cp wheelhouse/*.whl dist
      - name: Publish to PyPi
        if: startsWith(github.ref, 'refs/heads/main')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  ci-linux-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3
          python3 -m pip install ivpm
          python3 -m ivpm update --anonymous-git
      - name: Build Docs
        run: |
          ./packages/python/bin/python -m sphinx.cmd.build -M html \
            ./doc/source doc/build
          touch doc/build/html/.nojekyll
      - name: Deploy Docs
        if: startsWith(github.ref, 'refs/heads/main')
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: doc/build/html

  ci-windows:
    runs-on: ${{ matrix.platform }}
    strategy:
        matrix:
            include:
            - platform: windows-latest
              build_arch: x64
              python_arch: x64
              spec: '3.8'
            - platform: windows-latest
              build_arch: x64
              python_arch: x64
              spec: '3.9'
            - platform: windows-latest
              build_arch: x64
              python_arch: x64
              spec: '3.10'
            - platform: windows-latest
              build_arch: x64
              python_arch: x64
              spec: '3.11'
            - platform: windows-latest
              build_arch: x64
              python_arch: x64
              spec: '3.12'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Install Python ${{ matrix.spec }}
      uses: actions/setup-python@v2
      with:
        architecture: ${{ matrix.python_arch }}
        python-version: ${{ matrix.spec }}
    - uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: ${{ matrix.build_arch }}
    - name: Build/Test Package
      env:
        BUILD_NUM: ${{ github.run_id }}
      run: |
        python -m pip install ivpm
        python -m ivpm update -a
        ./packages/python/Scripts/python -m pip install ninja cython setuptools wheel build twine
        echo "BUILD_NUM=$env:BUILD_NUM" > python/zsp_parser/__build_num__.py
        $env:PYTHONPATH = '$PWD.Path/packages/pyastbuilder/src'
        echo "PYTHONPATH: $env:PYTHONPATH"
        ./packages/python/Scripts/python setup.py build bdist_wheel
            

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch dependencies
        run: |
          python3 --version
          python3 -m pip install ivpm
          python3 -m ivpm update -a
          ./packages/python/bin/python3 -m pip install cython setuptools wheel build twine
      - name: Build wheel
        env:
          BUILD_NUM: ${{ github.run_id }}
        run: |
          echo "BUILD_NUM=${BUILD_NUM}" > python/zsp_parser/__build_num__.py
          ./packages/python/bin/python3 setup.py bdist_wheel
      - name: Publish to PyPi
        if: startsWith(github.ref, 'refs/heads/main')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          ./packages/python/bin/python3 -m twine  upload dist/*.whl      
